### DISCUSSION TITLE
Want to run an npm 'global' command from a moon task. Can tasks use standard input as args?

### DISCUSSION THREAD

**Discussion by lukastransom** [moonrepo/moon#1023] [Q&A] [answered]
As specified in the ["Astro Example" in the moon Guides](https://moonrepo.dev/docs/guides/examples/astro#setup), I'd like to use the npm 'global' cli [`astro`](https://docs.astro.build/en/reference/cli-reference/) command from moon's tasks to do all the things `astro` can do. However, passing in a sub-command and/or package name results in an error.

`moon run astro:astro add @sanity/astro`

```shell
Error: project_graph::missing_from_path

  × No project could be located starting from path ..
```

```yml
# /apps/astro/moon.yml

tasks:
    astro:
        command: 'astro'
        local: true
...
```

Are there any other ways to accomplish this? Sorry if I'm overlooking a basic setting somewhere.
moon has been great for everything else so far! Thanks!

- macOS 13.5.1
- moon 1.12.0
- Alacritty + mksh
