### DISCUSSION TITLE
Passthrough args in deps

### DISCUSSION THREAD

**Discussion by paularmstrong** [moonrepo/moon#1240] [Q&A] [answered]
Use case: I am using Prisma and after I generate the schema, I'd like to automatically run eslint and prettier on the output (which goes to another project). My tasks look like so:

```yaml
  prisma:
    command: prisma
    env:
      NODE_ENV: production
      CHECKPOINT_DISABLE: "1"
    inputs:
      - ./prisma/**/*

  generate-schema:
    options:
      runDepsInParallel: false
    deps:
      - prisma -- generate
      - api-schema:lint
      - api-schema:format
    inputs:
      - ./prisma/**/*
```

This normally works fine for the case of calling the prisma task directly:

```sh
moon api:prisma -- generate
```

However the result of `moon api:generate-schema` is an error:

```
Error: config::parse::failed

  × Failed to parse apps/api/moon.yml.
  ╰─▶   × tasks.generate-schema.deps[0]: Invalid target ~:prisma -- generate, must be in the format of "scope:task", with acceptable identifier characters.

  help: https://moonrepo.dev/docs/config/project
```

Is this something not implemented, or am I missing some details on setting this up?
