### DISCUSSION TITLE
Bundling local typescript declarations

### DISCUSSION THREAD

**Discussion by gxxcastillo** [moonrepo/moon#1307] [Q&A]
My moonrepo has 6 different packages, but of the 6 I only want to publish 1.  The one published package has direct dependencies on 2 of the other packages and they in turn depend on the others.  How do I go about including the type declarations from the other 5 packages when I publish my 1 package?

My current workaround is to do the following each time I publish:
1 - manually copy over the type declarations from the other packages to my published package
1 - manually update the package.json for my published package to remove the dependencies on the other packages

**Comment by milesj** [comment]
Yeah since this is a unique situation, I think you would need a custom JS script to do this. In moon, you could chain 2 tasks to accomplish this.

```yaml
tasks:
  build-first:
    command: 'build-the-package'
  build:
    command: 'node ./copyTypes.js'
    deps: ['build-first']
```
