### DISCUSSION TITLE
How can I force the CI trigger when one library changes but there is no direct dependency

### DISCUSSION THREAD

**Discussion by apescione** [moonrepo/moon#1391] [Q&A]
I have a library in my monorepo and some projects use it not directly but through a CLI. Is there a way to force these projects to run their own CI when some files have touched into that library?
I tried dependOn, but it doesn't run the CI because moon doesn't see any touched files

**Comment by milesj** [comment]
Great question. There is a way around this right now using task deps (below), but I want to make this easier in the future.

In the shared library, you would basically add a noop task that has inputs on its files.

```yaml
tasks:
  changed:
    command: 'noop'
    inputs: ['**/*']
```

And in all the other projects that "use" it, you can have tasks that depend on it.

```yaml
tasks:
  build:
    command: '...'
    deps: ['library:changed']
```
