### DISCUSSION TITLE
Can I create a task can run another tasks?

### DISCUSSION THREAD

**Discussion by nhattran998** [moonrepo/moon#1461] [Q&A] [answered]
In our cases, we have 4 types of linting: lint overview with @biomejs, lint circular, lint type-check, and lint useless files/func with KNIP. So how can I create a task with the name: `lint` --> call 4 tasks. 

When I read the docs, the config file task.yml only had an option to extend, but it's extended only a task. https://moonrepo.dev/docs/config/project#extends

**Comment by milesj** [comment, marked as answer]
@harrytran998 You would create separates tasks for each, then create another task that depends on them all.

```yaml
tasks:
  lint-biome:
    # ...
  lint-circular:
    # ...
  lint-typecheck:
    # ...
  lint-useless:
    # ...
  lint:
    command: noop
    deps:
      - lint-biome
      - lint-circular
      - lint-typecheck
      - lint-useless
```
