### DISCUSSION TITLE
How can I run mutiple command in a task with seperate lines command(array) instead of a string

### DISCUSSION THREAD

**Discussion by nhattran998** [moonrepo/moon#1462] [Q&A] [answered]
When I read the docs: https://moonrepo.dev/docs/faq#how-to-run-multiple-commands-within-a-task, I only see the way we can run multiple commands with the `& or ;` operator.

So how we can do this like [command](https://moonrepo.dev/docs/config/project#command), can use an array, like

```yaml
tasks:
  multiple:
    command: 
		- task 1
		- task 2
		- task 3
		- task 4
		- task 5
    platform: 'system'
```
