### DISCUSSION TITLE
How can I trigger vsc hooks like husky?

### DISCUSSION THREAD

**Discussion by nhattran998** [moonrepo/moon#1464] [Q&A]
When I read the docs, seems like I just need to configure like bellow --> git hooks can work, but did not! So do you have any suggestions or guides to make this work like husky(https://github.com/typicode/husky)

```
vcs:
  defaultBranch: main
  manager: git
  syncHooks: true
  hooks:
    commit-msg:
      - scripts/git/commit-msg.sh
    pre-commit:
      - scripts/git/pre-commit.sh
    pre-push:
      - scripts/git/pre-push.sh
    prepare-commit-msg:
      - scripts/git/commit-msg.sh
    post-checkout:
      - scripts/git/post-checkout.sh
```
