### DISCUSSION TITLE
Is there a way to control the order of tasks?

### DISCUSSION THREAD

**Discussion by suin** [moonrepo/moon#1501] [Q&A]
First, I want to thank you for creating such a fantastic tool!

I created the following `moon.yml` and ran `moon run reset -c 1 --cache off`:

```yaml
tasks:
  build:
    local: true
    deps:
      - build-1
      - build-2
    options:
      runDepsInParallel: false
      persistent: false

  build-1:
    command: node -e 'setTimeout(() => console.log("build-1 done"), 200)'

  build-2:
    command: node -e 'setTimeout(() => console.log("build-1 done"), 200)'

  clean:
    command: node -e 'setTimeout(() => console.log("clean done"), 300)'
    local: true
    options:
      persistent: false

  reset:
    deps:
      - clean
      - build
    local: true
    options:
      runDepsInParallel: false
      persistent: false
```

I expected the tasks to run in the following order:

1. clean
2. build-1
3. build-2
4. build

However, the actual order was:

1. build-1
2. clean
3. build-2
4. build

![](https://github.com/moonrepo/moon/assets/855338/0862c6c7-3720-474e-acfe-b60a8e0f17d5)

From the action graph , it appears that `clean` and `build-1` & `build-2` are running concurrently.

![](https://github.com/moonrepo/moon/assets/855338/e5088f34-ee49-4b80-93ad-045bcb384c06)

While the `reset` task can control its direct dependencies (`clean` and `build`) with `runDepsInParallel`, is there a way for the `reset` task to control the execution timing of its nested dependencies (`build-1` and `build-2`) to ensure they run after `clean`?

**Comment by suin** [comment]
I found a workaround for my question:

```yaml
reset:
  command: "$SHELL -c 'moon run clean && moon run build'"
  local: true
  options:
    persistent: false
    shell: false
```

If there are any other methods to achieve the same result, I would love to hear them. Thank you!
