### DISCUSSION TITLE
Sharing a Quick Method to Create a TOML Plugin for Proto

### DISCUSSION THREAD

**Discussion by suin** [moonrepo/moon#1505] [Show and tell]
Hello moonrepo community,

I wanted to share a helpful guide created by my colleague, @kahirokunn, on how to quickly create a TOML file for moonrepo's proto tools. This tool is extremely useful and can save you a lot of time. Below is the translated version of [his article (Japanese)](https://qiita.com/kahirokunn/items/523e912fa0cfce02d374) for your convenience.

# How to Create a TOML for moonrepo's proto tools in 30 Seconds

## Prerequisite

This refers to moonrepo's proto tools, not gRPC's proto.

[moonrepo's proto tools documentation](https://moonrepo.dev/docs/proto/tools)

The assumption is that there are artifacts on GitHub.

### 1. List the assets

```sh
gh release view v4.44.1 --repo mikefarah/yq --json assets | pbcopy
```

### 2. Paste the content into the monnrepo-proto-tools-toml-creator using ChatGPT

[ChatGPT's monnrepo-proto-tools-toml-creator](https://chatgpt.com/g/g-HM8WnI0OZ-monnrepo-proto-tools-toml-creator)

![CleanShot 2024-06-13 at 10.54.07@2x.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/141711/3bf25a48-91a0-cf5e-37a2-cf08d8411e85.png)

A TOML file like the one below will be generated. That's it.

```toml
name = "neovim"
type = "cli"

[platform.linux]
download-file = "nvim-linux64.tar.gz"
checksum-file = "nvim-linux64.tar.gz.sha256sum"

[platform.macos]
download-file = "nvim-macos-{arch}.tar.gz"
checksum-file = "nvim-macos-{arch}.tar.gz.sha256sum"

[platform.windows]
download-file = "nvim-win64.{ext}"
checksum-file = "nvim-win64.{ext}.sha256sum"

[install]
download-url = "https://github.com/neovim/neovim/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "x86_64"

[install.ext]
msi = "msi"
zip = "zip"

[resolve]
git-url = "https://github.com/neovim/neovim"
```

---

I hope you find this tool as useful as I did. Feel free to check out the original article [here](https://qiita.com/kahirokunn/items/523e912fa0cfce02d374) and give @kahirokunn a follow for more insightful posts.
