### DISCUSSION TITLE
Introducing `appthrust/moon-ci-retrospect`: Enhance the Readability of Your `moon ci` Logs

### DISCUSSION THREAD

**Discussion by suin** [moonrepo/moon#1515] [Show and tell]
Hi Moonrepo Community,

I'm excited to share a new GitHub Action I've developed: [`appthrust/moon-ci-retrospect`](https://github.com/appthrust/moon-ci-retrospect). This action is designed specifically for projects using Moonrepo, aiming to make the test results of the `moon ci` command more readable in GitHub Actions logs.

### Why Use `moon-ci-retrospect`?

The `moon ci` command typically executes numerous tasks in parallel, which often results in long and complex logs. These lengthy logs can make it difficult to pinpoint the cause of CI failures. `moon-ci-retrospect` addresses this issue by improving the readability of the `moon ci` results, making it easier to identify the reasons for CI failures.

Here's a quick look at what you can expect:

![screenshot0](https://github.com/moonrepo/moon/assets/855338/3d06f886-e5e3-416a-ac8c-d3332b38a3d5)

### How to Use

Integrating `moon-ci-retrospect` into your workflow is simple. Just add the following steps to your GitHub Actions workflow:

```yaml
jobs:
  ci:
    name: "CI"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "moonrepo/setup-toolchain@v0"
      - run: "moon ci --color"
      # Add this↓
      - uses: appthrust/moon-ci-retrospect@v0
        if: success() || failure()
```

By including this action in your workflow, you can enhance the visibility of test results, making it easier to diagnose and address issues that arise during continuous integration.

### See It in Action

If you'd like to see a demo of the output, please check out this [example run](https://github.com/suinplayground/github-actions-log-formats/actions/runs/9589738341/job/26444016414#step:5:1).

### Get Started

Check out the [GitHub repository](https://github.com/appthrust/moon-ci-retrospect) for more details and to start using `moon-ci-retrospect` in your projects. I look forward to your feedback and hope this tool helps streamline your CI processes.

Happy coding!
