### DISCUSSION TITLE
How to pass the args from comandline to the tasks

### DISCUSSION THREAD

**Discussion by nhattran998** [moonrepo/moon#1709] [Q&A]
We have some db migration tasks. And a command-like script below. So what if I want to run the command like `prisma resolve --applied "file_name"`  --> `moon api:db.apply filename` --> not worked

I already traced the docs, but it might be hard for me right now. Could anyone suggest a solution for this thing?

```yml
tasks:
  db.apply:
    preset: "server"
    command: "prisma resolve --applied"
```

**Comment by milesj** [comment]
@harrytran998 You just need to add `--` between the moon command and the args to pass down, so it'll probably be: `moon api:db.apply -- filename`

**Reply by airtonix** [reply]
This doesn't behave as I'd expect it to: 

```yml
tasks:

  echo:
    command: |
      echo "\[ARG: ${*} \]"

```

```sh
> moon run user-app:echo -- help me
▪▪▪▪ user-app:echo
[ARG: ] help me
▪▪▪▪ user-app:echo (1ms)

Tasks: 1 completed
 Time: 2ms
```

Now with a normal bash file: 

```sh
#!/bin/bash
echo "[ARG: ${*}]"
```

and using it
```sh
> ./test.sh help me
[ARG: help me]
```

**Reply by milesj** [reply]
@airtonix Try `script` instead of `command`.

**Reply by airtonix** [reply]
@milesj Thanks for the idea, but it still doesn't feel right:

```yml
tasks:
  echo:
    script: |
      echo "Hello World" && echo "[ARG ${*} ]"
```


```sh
> moon run user-app:echo -- test
▪▪▪▪ user-app:echo
Hello World
[ARG  ]
▪▪▪▪ user-app:echo (1ms)

Tasks: 1 completed
 Time: 2ms
```

**Reply by airtonix** [reply]
@milesj perhaps you meant this? https://moonrepo.dev/docs/config/project#script.

nvm. it's exactly what you meant.

**Reply by milesj** [reply]
Not sure what to say, we literally just execute the command like `spawn(command, ...args)`.

**Reply by anotheri** [reply]
I also find this behaviour a bit confusing. For example it doesn't work for me either when i try to pass filename as parameter into a Vitest task

```yaml
  # Run unit tests
  test:
    command: 'vitest run'
    inputs:
      - '@group(vitest)'
      - '@group(sources)'
      - '@group(tests)'
```

and i run it like this

```sh
moon app:test -- MyComponent.test.tsx
```

for some reasons vitest executes all the files.

But it accepts filename and works as expected (i.e. executes tests only for the file(s) that match this path) when i do the same for the following task:

```yaml
# Watch for test changes
  test-watch:
    command: 'vitest watch'
    preset: 'watcher'
```

and i run it the same way

```sh
moon app:test-watch -- MyComponent.test.tsx
```

If i run `vitest run` command via `pnpm test MyComponent` script, it works as expected. 
When instead of `command: 'vitest run'` i use `script: 'pnpm test'` and run it via moon:

```sh
moon app:test -- MyComponent
```

it passes no argument(s) either. So it would be great if you could take a look into these inconsistencies, @milesj. 
I'm on the latest versions of moon/proto/pnpm/vitest. Thanks in advance!

**Reply by milesj** [reply]
@anotheri  Does it work if you do `moon run app:test` instead of `moon app:test`? Theres a bunch of hacks in to get that shorthand working and this may be a bug with it.

**Reply by anotheri** [reply]
@milesj no, `moon run app:test -- MyComponent` doesn't work neither, and no matter what I try:

- command/script variations:
  - `command: 'vitest run'`
  - `command: 'vitest'`
  - `script: 'pnpm test'` that calls `vitest run`
  - `script: 'pnpm test'` that calls `vitest`;
- with/without `inputs`
- with/without `preset: 'server'` or `preset: 'watcher'`

And when I use `script` (the only way i can see actual logs of executed script, `command` doesn't provide such logs and i didn't find a way to see them via options) it doesn't even pass the argument into `pnpm test` call, see the difference between using moon task `script` and pnpm script call below:
<img width="1050" height="137" alt="Image 2025-10-17 09-49-46" src="https://github.com/user-attachments/assets/c19ebbf4-1e41-407f-9ff6-948f5216acfe" />


and it's there when i call `pnpm test` with this argument directly: 
<img width="1048" height="117" alt="Image 2025-10-17 09-52-00" src="https://github.com/user-attachments/assets/1e9dadb4-4f60-4f17-bc8a-a0e1ebd9971c" />

Let me know if i can help with any additional testing.

**Reply by anotheri** [reply]
@milesj it seems i've found the source of _my problem_. 

I have a conflict between `.moon/tasks.yml` and `apps/dashboard/moon.yml` like this:

```yaml
# .moon/tasks.yml
test:
  command: "vitest run ."
```

```yaml
# apps/dashboard/moon.yml
test:
  command: 'vitest run'
```


And whatever i've tried before (mentioned in previous comment) I put into the `apps/dashboard/moon.yml` assuming it'll override global tasks. But as far as i've got from reading docs a bit more it will utilize [merge strategies](https://moonrepo.dev/docs/concepts/task-inheritance#merge-strategies), so i can either adjust those stragies by using something like `options.merge` or `options.mergeArgs`:

```yaml
# apps/dashboard/moon.yml
test:
  command: 'vitest run'
  options:
    mergeArgs: 'replace'
```

Or to override global task completely I can explicitly `exclude` global task via [`inheritedTasks`](https://moonrepo.dev/docs/config/project#inheritedtasks).

So now with `command: 'vitest run'` inside the project it works as expected.

But nevertheless (even if I remove the global `test` task completely and) if I have a project scoped task `test` with `script: 'pnpm test'` that calls `vitest run` it still doesn't pass an argument as i've explained above (i guess it's the same issue @airtonix mentioned before).

UPD: And by the way, is there a way to check what the merged result of a certain task look like? as shown in the end of the [merge strategies section](https://moonrepo.dev/docs/concepts/task-inheritance#merge-strategies) but via cli command... It might be helpful to catch/debug such issues.
