### DISCUSSION TITLE
[Q*A] Moon cannot access the current package "bin" to execute the command

### DISCUSSION THREAD

**Discussion by nhattran998** [moonrepo/moon#1717] [Q&A] [answered]
**Basic Infor**
- Moon v **1.29.0**
- `pnpm` workspace: **9.12.3**
- MacOS 13.5 Intel

**Apps infos**
- Use monorepo with pnpm
- Have `apps/api` folder - contains `nodemon` devDependencies. Then the API folder had `apps/api/node_modules/.bin/nodemon` cli. But when I run the command `moon api:dev` --> Cannot found `nodemon` module.

But when I run `pnpm -C apps/api dev` --> Worked.

So, what is the thing or config I need to update here? Thanks

Here is the moon.yml

```yml
tasks:
  dev:
    command: "nodemon"
```

**Comment by milesj** [comment, marked as answer]
@harrytran998 What is the platform of `moon task api:dev`? It should be Node.js. If it is not, you can do this:

```
tasks:
  dev:
    command: "nodemon"
    platform: "node"
```

If this still doesn't work, then the nodemon may be one of those binaries that just doesn't work without calling it though npm/pnpm/yarn.

**Reply by nhattran998** [reply]
Thank u for pointing out to me about this. After looking at this, I upgraded the toolchain configuration to use NodeJs. 
Before this, we used the `bun` toolchain, but we had a problem with the mono repo with bun --> Then we switched to `node` but forgot to add the node toolchain config. 

Here is the config for anyone have the same problem like us: `toolchain.yml`

```yml
node:
  version: "22.11.0"
  packageManager: "pnpm"
  pnpm:
    version: "9.12.3"
  addEnginesConstraint: true
  syncPackageManagerField: true
```
