### DISCUSSION TITLE
How to use moon to generate dynamic gitlab ci pipeline?

### DISCUSSION THREAD

**Discussion by mortyccp** [moonrepo/moon#1727] [General]
I want to setup a gitlab ci pipeline that only triggers affected projects pipelines. I tried to look into the generator and try to use the query command to pass affected projects information to the generator context, but the data type support only supports string or enumeration which is not as effective as JSON.

Would like to know what’s the suggestion to workaround this? Will moon add support for JSON variable for generator? OR will generator can access the moon cli?

**Comment by milesj** [comment]
@mortyccp Do you have a pseudo example of what you're trying to achieve? I don't understand why the generator (I'm guessing `moon generate`?) would be necessary for CI pipeline/affected stuff.

**Reply by mortyccp** [reply]
Sure.

Consider a project that has multiple applications that need to be built and deployed. After deployment, there are various optional tasks that run for that deployment , like testing etc, which we would like to allow developers to trigger them individually in the gitlab pipeline interface. To do that we’re defining the pipeline file for each project in their own project folder. And would like to use https://docs.gitlab.com/ee/ci/pipelines/downstream_pipelines.html#dynamic-child-pipelines to trigger these pipelines for affected projects

**Reply by milesj** [reply]
@mortyccp So basically something like this:

```
generate-config:
  stage: build
  script: moon [some command] > generated-config.yml
  artifacts:
    paths:
      - generated-config.yml
```

What does the `generated-config.yml` look like?

**Reply by mortyccp** [reply]
```
trigger-project-a:
  trigger:
    include:
      - local: apps/a/gitlab-pipeline.yml

trigger-project-b:
  trigger:
    include:
      - local: apps/b/gitlab-pipeline.yml
```

Like this, and expect only affected projects will  be generated

**Reply by milesj** [reply]
My suggestion would to have a custom script, maybe Bash or Node.js, that pieces this all together. Here's some pseudo code:

```bash 
data = exec('moon query projects --affected --json')

for project in data.graph.nodes {
  echo `
trigger-project-${project.id}:
  trigger:
    include:
      - local: ${project.source}/gitlab-pipeline.yml
  `
}
```

And then in the pipeline, you can call that script:

```
generate-config:
  stage: build
  script: bash generate-configs-from-moon.sh > generated-config.yml
  artifacts:
    paths:
      - generated-config.yml
```
