### DISCUSSION TITLE
How to start multiple watchers with correct output style with prefix in each output?

### DISCUSSION THREAD

**Discussion by mortyccp** [moonrepo/moon#1728] [General]
# Context 
In a project that contains sdk and app and app depends on sdk and both are javascript that need to be built.
In local development, when developing the app in hot reload, would expect the sdk to also start in watch mode too.
To simulate, create the following tasks for testing.

```

# https://moonrepo.dev/docs/config/project
$schema: 'https://moonrepo.dev/schemas/project.json'

language: 'javascript'
stack: 'frontend'
type: 'application'
dependsOn:
  - 'sdk'

tasks:
  all:
    command: noop
    deps:
      - 'ping'
      - 'pong'
    options:
      persistent: true
      outputStyle: stream

  ping:
    script: 'while true; do echo ping; sleep 1; done'
    options:
      persistent: true
      outputStyle: stream
    deps: 
      - 'pong'

  pong:
    script: 'while true; do echo pong; sleep 1; done'
    options:
      persistent: true
      outputStyle: stream
  
  all-watcher-preset:
    preset: 'watcher'
    command: noop
    deps:
      - 'ping-watcher-preset'
      - 'pong-watcher-preset'

  ping-watcher-preset:
    preset: 'watcher'
    script: 'while true; do echo ping; sleep 1; done'
    deps: 
      - 'pong-watcher-preset'

  pong-watcher-preset:
    preset: 'watcher'
    script: 'while true; do echo pong; sleep 1; done'

  # invalid:
  #   command: 'noop'
  #   options:
  #     persistent: true
  #     interactive: true
```

# Results
1.  Start a noop tasks that depends on both tasks. Outputs are prefixed correctly.
<img width="312" alt="image" src="https://github.com/user-attachments/assets/6cc119a1-689c-4042-bcba-ac6b4556f2d2">

2. Start the task that depends on another task. The started task output is not prefixed.
<img width="266" alt="image" src="https://github.com/user-attachments/assets/d8471e7e-5b75-45c0-8027-f3267d79971b">

3. Set with `preset: 'watcher'`. Start a noop tasks that depends on both tasks. Outputs are not prefixed.
<img width="301" alt="image" src="https://github.com/user-attachments/assets/4a1016c4-f396-43cd-af3f-f01e9ad7d979">

4. Set with `preset: 'watcher'`. Start the task that depends on another task. Outputs are not prefixed.
<img width="324" alt="image" src="https://github.com/user-attachments/assets/7b9f4bf8-e91c-4cfa-8cb2-dbde1eda11fb">

6. Can't manually set `persistent: true` and ` interactive: true` which should be the same with`preset: 'watcher'` 
<img width="636" alt="image" src="https://github.com/user-attachments/assets/b52aef09-7889-4e2f-ad0e-46cf1dff4f95">

Questions
1. What's the suggested way to achieve start both watchers with proper prefixed output?
2. Why can't manually set `persistent: true` and ` interactive: true`?
