### DISCUSSION TITLE
Rust/Cargo: Changing a relative dependency source does not invalidate the project hash

### DISCUSSION THREAD

**Discussion by alexander-heimbuch** [moonrepo/moon#1802] [Q&A] [answered]
I want to use moon for managing a rust monorepo with multiple workspaces. So far it seems to be a good fit but I encountered an issue when changing something in a used library that an application depends on. Even when declaring a `dependsOn` in the application`moon.yml` it replays a cached build task when changing something in the library source.

I guess this is either a quirky workspaces setup or a misconfiguration but couldn't figure it out so far :/

Example:
```
libs
  example-lib
      src/
        ...
      Cargo.toml
      moon.yml
  Cargo.toml <-- Workspace
apps
  example-app
    src/
      ...
    Cargo.toml
    moon.yml
  Cargo.toml <-- Workspace
``` 

> libs/example-lib/moon.yml
```yaml
language: rust
type: library
```
> apps/example-lib/moon.yml
```yaml
language: rust
type: application

tasks:
  build:
    command: 'cargo build'
    inputs:
      - '@globs(sources)'
 dependsOn:
   - 'example-lib' 
 ```
> apps/example-lib/Cargo.toml
```toml
[dependencies]
lib = { path = "../../libs/example-lib" }
```

**Comment by milesj** [comment, marked as answer]
Only task `deps` are included in a task's hash, not a project's deps. https://moonrepo.dev/docs/config/project#deps

If you want don't want to reference another task in the lib, you can create a "fake" task that is simple used as a touched check.

```yaml
# lib
tasks:
  touched:
    command: noop

# app 
tasks:
  build:
    command: 'cargo build'
    inputs:
      - '@globs(sources)'
    deps:
      - 'lib:touched'
```
