### DISCUSSION TITLE
Concatenation of global task arguments

### DISCUSSION THREAD

**Discussion by d-corler** [moonrepo/moon#1854] [Q&A] [answered]
If I understand correctly this [documentation](https://moonrepo.dev/docs/concepts/task-inheritance) we can only merge a global task with a local definition of a project

```
📁 /
├── 📁 .moon
│   └── 📁 tasks
│       └── tag-vite.yml
└── 📁 projects
    └── 📁 example
        └── moon.yaml
```

I define the command in a global task
```yaml
# .moon/tasks/tag-vite.yml
tasks:
  cleanup:
    command:
      - pnpm
      - exec
      - rimraf
    local: true
```

I import the global task with the `tag` and extend it with an argument
```yaml
# projects/example/moon.yml
tags: [vite]

tasks:
  cleanup:
    args:
      - dist
```

---

🤔 What can be the strategy if I want to "build" a command trough multiple global tasks definition ? 

For example, I want to flavour my `rimraf` command to suit different paradigms using tags

```
📁 /
├── 📁 .moon
│   └── tasks.yml
│   └── 📁 tasks
│       ├── tag-vite.yml
│       └── tag-vitest.yml
└── 📁 projects
    └── 📁 example
        └── moon.yaml
```

The general task, to define the beginning of the command
```yaml
# .moon/tasks.yml
tasks:
  cleanup:
    command:
      - pnpm
      - exec
      - rimraf
    local: true
```

The `vite` extension of the command
```yaml
# .moon/tasks/tag-vite.yml
tasks:
  cleanup:
    args:
      - dist
```

The `vitest` extension of the command
```yaml
# .moon/tasks/tag-vitest.yml
tasks:
  cleanup:
    args:
      - coverage
```

Usage of tags in the project manifest
| Tags              | `cleanup` command composition                          |
| ----------------- | -------------------------------- |
| `vite`            | `pnpm exec rimraf dist`          |
| `vitest`          | `pnpm exec rimraf coverage`      |
| `vite` + `vitest` | `pnpm exec rimraf dist coverage` |

It's currently possible or do I need to fine tune each arguments at project level ?
