### DISCUSSION TITLE
How to properly handle lock file diffs in CI?

### DISCUSSION THREAD

**Discussion by akostylev0** [moonrepo/moon#1866] [Q&A] [answered]
I have a monorepo with Yarn and Cargo (both using workspaces). I'm using Dependabot to update dependencies, and sometimes only the lock file changes. However, my CI, configured as shown below, does not trigger in such cases.

Would it be correct to add `/Cargo.lock` and `/yarn.lock` to inputs? And if I do so, will a build be triggered by a dependency update in a different project?

Is it possible to configure moon so that it triggers only when a project's dependencies changes, and if so, how?

```yaml
fileGroups:
  sources:
    - 'src/**/*'
    - 'Cargo.toml'

tasks:
  build:
    command: 'cargo build --release'
    inputs:
      - '@globs(sources)'
    outputs:
      - '/target/release/app'
   ```

btw, Thanks for your work — really awesome project!
