### DISCUSSION TITLE
[Question] Why moon auto run bun install in each repo instead only one install in root folder?

### DISCUSSION THREAD

**Discussion by nhattran998** [moonrepo/moon#1907] [Q&A] [answered]
I ran the build command --> Moon started to run `bun install` --> but did not install it in the root, but installed it on each package --> Each package will generate a `bun.lock` file + failed command.
I don't know what's happening here, but it is pretty lmao in this case. 
 
<img width="486" alt="image" src="https://github.com/user-attachments/assets/f55520cf-794b-407e-a475-00035adbf3c5" />

## More Context

Latest moon + proto version
Here is  `toolchains.yml` file:

```yml
$schema: 'https://moonrepo.dev/schemas/toolchain.json'

node:
  version: "22.14.0"
  packageManager: bun
  bun:
    version: "1.2.6"
  addEnginesConstraint: true
  syncPackageManagerField: true

bun:
  version: "1.2.6"
  syncProjectWorkspaceDependencies: true

rust:
  version: "1.85.1"
  syncToolchainConfig: true
```
