### DISCUSSION TITLE
Tag-based targets in task `deps` not properly added to project `dependencies`

### DISCUSSION THREAD

**Discussion by arthur-leclerc** [moonrepo/moon#1956] [Q&A]
Hey, I have some trouble with tag-based targets in task dependencies.

When using tag-based targets in a task deps of a project, the targeted project of the dependency is not being automatically added to the project where the task is defined, despite the task having the dependency in its deps.

Let me illustrate this with a concrete example.

With the following global task in `.moon/tasks/tag-terraform.yml`:

```yaml
tasks:
  terraform/docs:
    toolchain: system
    command: terraform-docs
    args:
      - markdown
      - document
      - --config
      - $workspaceRoot/.github/configs/terraform-docs/docs.yaml
      - --header-from
      - docs/header.md
      - .
    inputs:
      - /.github/configs/terraform-docs/docs.yaml
      - docs/header.md
      - '**/*.tf'
    outputs:
      - docs/index.md
    options:
      outputStyle: buffer-only-failure
```

And x project, for example `terraform/project-x/moon.yml` using it:

```yaml
id: terraform/project-x

tags:
  - terraform
```

When configuring a task dependency using a tag-based target on another project, let say `apps/docs/moon.yml`:

The project dependency is not automatically added when using a tag-based target, but are when using a direct project reference.

```yaml
id: docs

tasks:
  build:
    description: |-
      Build the documentation.
    command: $projectRoot/.venv/bin/mkdocs
    args:
      - build
      - --config-file
      - mkdocs.yml
      - --strict
      - --site-dir
      - $projectRoot/site/
    deps:
      - '#terraform:terraform/docs'            # <- Why this doesn't add the targeted projects as a dependency?
      - 'terraform/project-3:terraform/docs'  # <- This work as expected

    env:
      SOURCE_DATE_EPOCH: '0'
    inputs:
      - /mkdocs.yml
      - '**/*'
    outputs:
      - site/
    options:
      runFromWorkspaceRoot: true
```

What I don't understand is that when I list the `docs:build` task, I can see all the dependencies, including those using tag:

```shell
$ ❯ moon task docs:build
About  ────

  Build the documentation.

  Target: docs:build
  Project: docs
  Task: build
  Toolchain: python
  Type: build

Process ────
  [...]
  Depends on:
    - terraform/project-1:terraform/docs
    - terraform/project-2:terraform/docs
    - terraform/project-3:terraform/docs
    - terraform/project-4:terraform/docs
    - terraform/project-5:terraform/docs
```

But at the project level, I only see the one with the directly referenced project.

```shell
❯ moon project docs
Metadata ────

  Documentation for the DevOps team

  Name: DevOps - Docs

About  ────

  Project: docs
  Alias: docs
  Source: apps/docs
  Depends on:
    - terraform/project-3 (implicit, build)   # <- Why I'm not seeing project added as a dependency here when using a tag-based target?
```

When calling the `docs:build` task, I'm seeing the right behavior, Moon build each Terraform project docs before building the documentation.

However, when trying to detect if the project have been touched, I'm not getting the right result:

```
moon query touched-files | moon query projects --affected --id docs --downstream direct
```

Will return nothing if I modify a file in any Terraform project as these projects are not added as dependencies to the `docs` project.

Similarly, when using `moon project-graph docs`, I don't see my Terraform projects as dependencies when using tag-based targets.

Do I really need to list all the projects here? What's the point of using tag-based targets then?

Thank you for your help!
