### DISCUSSION TITLE
how does `platform: system` work for shell/bash?

### DISCUSSION THREAD

**Discussion by tomdavidson** [moonrepo/moon#413] [Q&A] [answered]
I have a few one-off root-level tasks that I do not necessarily want a long list of args nor write an external script.

Command from string works:  
```yaml
  relink:
    command: |
      bash -c "
      find . -name "node_modules" -type d -prune -print -exec rm -rf "{}" \;
      pnpm install --recursive 
      "
    platform:
      system
```
But, Id rather:
```yaml
  relink:
    command: |
      find . -name "node_modules" -type d -prune -print -exec rm -rf "{}" \;
      pnpm install --recursive 
    platform:
      system
```

Why do I need to invoke bash with the command from string, even when I say the platform is system?
