### ISSUE TITLE
[feature] Globally override task configs

### ISSUE THREAD

**Issue by maastrich** [moonrepo/moon#1012]
**Is your feature request related to a problem? Please describe.**

I want to be able to define global task settings to avoid duplications across tasks definitions

**Describe the solution you'd like**

```yaml
# .moon/tasks.yml

defaults:
  options:
    shell: false
  env:
    NODE_ENV: development
    SHELL: /bin/bash

tasks:
  task-1:
    command: ls # runs in the shell the user is currently in
  task-2:
    command: ls # runs on a bash spawned by moon
    options:
       shell: true
```

> the `defaults` key is obviously a suggestion but anything explicit is fine

**Describe alternatives you've considered**

Since the last release it is possible to extends a task, a possibility would be to create a `base` task and extend it everywhere (not implicit enough in my opinion)
 
```yaml
# .moon/tasks.yml

tasks:
  base: 
    command: noop
    options:
      shell: false
    env:
      NODE_ENV: development
      SHELL: /bin/bash
  task-1:
    extends: ['base']
    command: ls # runs in the shell the user is currently in
  task-2:
    extends: ['base']
    command: ls # runs on a bash spawned by moon
    options:
       shell: true
```

**Additional context**

Specifying the shell is really useful for users using a `fish` as default shell and whose syntax may defer from bash and similars

**Comment by milesj** [comment]
@maastrich There's a 3rd option that's not really documented, using yaml refs/anchors:

```yaml
# .moon/tasks.yml

tasks:
  task-1: &base-task
    command: ls # runs in the shell the user is currently in
    options:
      shell: false
    env:
      NODE_ENV: development
      SHELL: /bin/bash
  task-2:
    <<: *base-task
    command: ls # runs on a bash spawned by moon
    options:
       shell: true
```

I'm just worried about adding yet another way to configure tasks, and how it would work with inheritance/merging/etc. Seems like a lot of cognitive overhead for people to understand.
