### ISSUE TITLE
[bug] It isn't clear what task failed when you run multiple tasks at once

### ISSUE THREAD

**Issue by mrobinsn** [moonrepo/moon#1014]
With the following `moon.yml`:
```yaml
$schema: https://moonrepo.dev/schemas/project.json
language: go
tasks:
  task1:
    command: bash -euo pipefail -c
    inputs: []
    args:
    - echo "task1" && exit 1
  task2:
    command: bash -euo pipefail -c
    inputs: []
    args:
    - echo "task2"
  task3:
    command: bash -euo pipefail -c
    inputs: []
    args:
    - echo "task3"
```

If I run multiple tasks at once like this:
```bash
❯ moon run task1 task2 task3
▪▪▪▪ moon-multi-task-fail-repro:task1
▪▪▪▪ moon-multi-task-fail-repro:task2
▪▪▪▪ moon-multi-task-fail-repro:task3
moon-multi-task-fail-repro:task3 | task3
moon-multi-task-fail-repro:task2 | task2
moon-multi-task-fail-repro:task1 | task1
▪▪▪▪ moon-multi-task-fail-repro:task2 (11ms)
▪▪▪▪ moon-multi-task-fail-repro:task3 (11ms)
▪▪▪▪ moon-multi-task-fail-repro:task1 (11ms)
Error:   × Failed to run bash (exit code 1)
```

It's not clear what task failed. This can be confusing when there are many dependencies and the output is very long.
