### ISSUE TITLE
[bug] moon incorrectly caches failures

### ISSUE THREAD

**Issue by mrobinsn** [moonrepo/moon#1024]
Steps to reproduce:
1. Initialize a git repo (required so that the moon cache kicks in)
2. Initialize moon with a root project
3. Configure a root `moon.yml` like so:
    ```yaml
    $schema: https://moonrepo.dev/schemas/project.json
    language: go
    tasks:
    mytask:
        command: bash -euo pipefail -c
        args:
        - echo "test" > output.txt && exit 1
        inputs:
        - input.txt
        outputs:
        - output.txt
    ```
4. Touch `input.txt` so that it exists
5. Run the task and see it fail:
    ```bash
    ❯ moon run mytask
    ▪▪▪▪ moon-fail-repro:mytask
    ▪▪▪▪ moon-fail-repro:mytask (6ms, fc4cd76a)
    Error:   × Failed to run bash (exit code 1)
    ```
6. Run the task again:
    ```bash
    ❯ moon run mytask
    ▪▪▪▪ moon-fail-repro:mytask (cached from previous run, fc4cd76a)

    Tasks: 1 completed (1 cached)
    Time: 6ms ❯❯❯❯ to the moon
    ```

I expected moon to either:
* Remember that the task failed and carry forward that cached failure (although this would have weird side-effects where you'd have to disable the cache to actually retry the task in cases where it can fail because of non-hash-changing variables (like network connectivity, etc))

or

* To not cache failures

The current behavior is really strange, especially when the failing task is in the middle of a long dependency chain, because moon doesn't "see" that the task failed it will still run everything that was dependent on it succeeding.
