### ISSUE TITLE
[bug] `moon task` command broke in v1.11.0 with cross-project dependencies

### ISSUE THREAD

**Issue by mrobinsn** [moonrepo/moon#1039]
The `moon task <target>` command is no longer working as expected.

Steps to reproduce:
1) A `.moon/workspace.yml` like so:
    ```yaml
    $schema: 'https://moonrepo.dev/schemas/workspace.json'
    projects:
      - '.'
      - 'sub-project'
    ```
2) A root `moon.yml` like so:
    ```yaml
    $schema: https://moonrepo.dev/schemas/project.json
    language: go
    tasks:
      test:
        command: echo "test"
        deps:
        - sub-project:test
        ```
3) A sub-project `sub-project/moon.yml` like so:
    ```yaml
    $schema: https://moonrepo.dev/schemas/project.json
    language: go
    tasks:
      test:
        command: echo "test"
    ```
4) With moon `=v1.10.1`:
    ```bash
    ❯ moon task moon-query-task-repro:test

    MOON-QUERY-TASK-REPRO:TEST

    Task: test
    Project: moon-query-task-repro
    Platform: system
    Type: test
    ... <expected output> ...
    ```
5) With moon `>=v1.11.0`:
    ```bash
    ❯ moon task moon-query-task-repro:test
    Error: task_expander::unknown_target

    × Invalid dependency sub-project:test for moon-query-task-repro:test, target does not
    │ exist.
    ```
