### ISSUE TITLE
[bug] moon 1.13.1 Main thread panicked at /app/crates/node/tool/src/pnpm_tool.rs:36:40

### ISSUE THREAD

**Issue by cherrot** [moonrepo/moon#1042]
**Describe the bug**

```shell
$ moon run :lint                            
Error:   × Main thread panicked.
  ├─▶ at /app/crates/node/tool/src/pnpm_tool.rs:36:40
  ╰─▶ called `Option::unwrap()` on a `None` value
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Environment**

<details><summary>`npx envinfo` output</summary>
<p>

```yaml
  System:
    OS: Linux 6.4 Arch Linux
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 20.35 GB / 31.04 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /usr/bin/node
    npm: 9.8.1 - /usr/bin/npm
    pnpm: 8.7.4 - /usr/bin/pnpm
  Managers:
    Cargo: 1.61.0 - /usr/bin/cargo
    pip3: 23.2.1 - /usr/bin/pip3
  Utilities:
    CMake: 3.27.4 - /usr/bin/cmake
    Make: 4.4.1 - /usr/bin/make
    GCC: 13.2.1 - /usr/bin/gcc
    Git: 2.42.0 - /usr/bin/git
    Clang: 16.0.6 - /usr/bin/clang
    Ninja: 1.11.1 - /usr/bin/ninja
    FFmpeg: 6.0 - /usr/bin/ffmpeg
    Curl: 8.2.1 - /usr/bin/curl
  Virtualization:
    Docker: 24.0.5 - /usr/bin/docker
  IDEs:
    Vim: 9.0 - /usr/bin/vim
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Go: 1.21.0 - /usr/bin/go
    Perl: 5.38.0 - /usr/bin/perl
    Python: 3.11.5 - /usr/bin/python
    Python3: 3.11.5 - /usr/bin/python3
    Rust: 1.61.0 - /usr/bin/rustc
  Databases:
    SQLite: 3.43.0 - /usr/bin/sqlite3
```

</p>
</details> 

<details><summary>toolchain versions</summary>
<p>

```yaml
$ pnpm version
{
  '@catalyst/source': '0.0.0',
  npm: '9.8.1',
  node: '16.20.2',
  v8: '9.4.146.26-node.26',
  uv: '1.46.0',
  zlib: '1.2.13',
  brotli: '1.0.9',
  ares: '1.19.1',
  modules: '93',
  nghttp2: '1.55.1',
  napi: '8',
  llhttp: '6.0.11',
  openssl: '3.1.2',
  cldr: '43.1',
  icu: '73.2',
  tz: '2023c',
  unicode: '15.0'
}
```

```shell
$ pnpm --version
8.7.4
$ moon --version
moon 1.13.1
```

</p>
</details>
