### ISSUE TITLE
[bug] `moon run` in Github Action on PR branch looks for `main` branch, fails

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#1060]
**Describe the bug**

I setup a github action that runs some moon commands, and the action is explicitly setup not to check out moon, but only the latest commit from a PR. It appears that moon is attempting to perform an action against `main` even though it's not present, as the `actions/checkout` hasn't pulled `main`.

**Steps to reproduce**

This workflow https://github.com/shellscape/jsx-email/actions/runs/6243091511/job/16947973874#step:10:1 has trace logging for the failure

**Expected behavior**

- Not failing a `moon run` command when the `main` branch doesn't exist.
- Alerting the user that an expected branch doesn't exist, rather than the current error output
- Warning rather than Erroring

**Screenshots**

See link above

**Environment**

```
Github Actions, Ubuntu
```

**Additional context**

**Comment by shellscape** [comment]
Viable workaround in the meantime:

```yml
      - name: Force Update Main
        run: |
          git fetch origin
          git branch -f main origin/main
```
