### ISSUE TITLE
[feature] Ability to specify additional configuration for task dependencies

### ISSUE THREAD

**Issue by marcus-sa** [moonrepo/moon#1071]
I've used Nx extensively for a very long time, so I'm excited to see what Moon has to offer, but unfortunately, the customization is lacking.

https://nx.dev/reference/project-configuration#dependson

**Is your feature request related to a problem? Please describe.**
I have the following task configuration:
```yaml
fileGroups:
  build:
    - 'build/**/*.js'

tasks:
  deploy:
    command: 'bos components deploy'
    inputs:
      - '@globs(sources)'
    deps:
      - build

  build:
    command: 'rollup -c $workspaceRoot/components/rollup.config.mjs'
    inputs:
      - '@globs(sources)'
    outputs:
      - 'build'

  load:
    command: 'sleep 1 && bos-loader marcus-sa.near --path $projectRoot/build'
    local: true
    inputs:
      - '@globs(build)'

  dev:
    command: noop
    local: true
    deps:
      - build
      - load

```
When the `load` task is run, I'd like to pass a `--watch` flag to the `build` task dependency.

**Describe the solution you'd like**

A configuration option to pass additional configuration to the task dependencies.

Example API:

```yaml
tasks:
  dev:
    command: noop
    deps:
      - task: build
        env: {}
        args:
          - '--watch'

      - load
```

I tried to make a separate task called `build-watch` and use that for `load`, but that wasn't possible because two commands cannot have the same outputs.

**Comment by milesj** [comment]
@marcus-sa This requests is on the roadmap, but in the meantime, you could do something like this:

```yaml
  build:
    command: 'rollup -c $workspaceRoot/components/rollup.config.mjs'
    inputs:
      - '@globs(sources)'
    outputs:
      - 'build'

  build-watch:
    extends: build
    args: --watch

  dev:
    command: noop
    local: true
    deps:
      - build-watch
      - load
```

**Comment by marcus-sa** [comment]
> @marcus-sa This requests is on the roadmap, but in the meantime, you could do something like this:
> 
> ```yaml
>   build:
>     command: 'rollup -c $workspaceRoot/components/rollup.config.mjs'
>     inputs:
>       - '@globs(sources)'
>     outputs:
>       - 'build'
> 
>   build-watch:
>     extends: build
>     args: --watch
> 
>   dev:
>     command: noop
>     local: true
>     deps:
>       - build-watch
>       - load
> ```

× Tasks X:build, X:build-watch have configured the same output components/X/build. Overlapping outputs is not supported as it can cause non-deterministic results.

**Comment by milesj** [comment]
Ah yeah, you can do something like this, but at this point you may as well duplicate the task.

```
  build-watch:
    extends: build
    args: --watch
    outputs: []
    options:
      mergeOutputs: replace
```

**Comment by milesj** [comment]
@marcus-sa Have a question for you, maybe you know with your Nx experience and how they solved it.

The reason this hasn't been implemented yet, is because I'm unsure how to solve it within the dependency graph + task runner. Say we have 2 separate tasks that depend on the same `build` task, but pass different args. In this case, `build --esm` and `build --cjs`.

In the task runner, the chance both of these `build` tasks running at the same time is possible, resulting in a collision, or separate processes reading/writing the same files, which is also problematic. There needs to be some kind of guard rail that avoids this, or some guarantee they don't run at the same time.

**Comment by hckhanh** [comment]
I have the same issue, I am using Vite to build production files.

```
vite build --mode staging
```

and

```
vite build --mode production
```

If I use moon, it should be:

```yml
  build-staging:
    command: 'vite'
    type: 'build'
    args:
      - 'build'
      - '--mode'
      - 'staging'
    options:
      mergeOutputs: replace
    inputs:
      - 'src/**/*'
      - '!src/**/*.cy.*'
      - 'index.html'
      - 'package.json'
      - 'public/**/*'
      - 'vite.config.ts'
    outputs:
      - 'dist/**/*'
  build-production:
    command: 'vite'
    type: 'build'
    args:
      - 'build'
      - '--mode'
      - 'production'
    options:
      mergeOutputs: replace
```

But for now it show me the error

Tasks `project:build-production`, `project:build-staging` have configured the same output `dist/**/*`. Overlapping outputs is not supported as it can cause non-deterministic results.
