### ISSUE TITLE
[bug] setup command doesn't work in github actions

### ISSUE THREAD

**Issue by marcus-sa** [moonrepo/moon#1072]
**Describe the bug**
```
Run moon setup
▪▪▪▪ installing node 20.7.0
Error: plugin::http

  × Failed to make HTTP request.
  ├─▶ request or response body error: error reading a body from connection:
  │   stream error received: unexpected internal error encountered
  ├─▶ error reading a body from connection: stream error received: unexpected
  │   internal error encountered
  ╰─▶ stream error received: unexpected internal error encountered
```

**Steps to reproduce**
- Setup Node.js toolchain
- Add the following steps to a workflow job
	```yaml
	- uses: moonrepo/setup-moon-action@v1
	  with:
	    version: 1.14.0
	
	- run: moon setup
	```
- Run it and watch it fail

**Expected behavior**

For `moon setup` to work in CI.
