### ISSUE TITLE
[bug] pnpm command not found in Github Actions

### ISSUE THREAD

**Issue by marcus-sa** [moonrepo/moon#1073]
**Describe the bug**
`pnpm: command not found`

**Steps to reproduce**
Setup node & pnpm toolchain

Create a Github Actions workflow job:
```yaml
permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: moonrepo/setup-moon-action@v1

      - run: moon setup

      - run: pnpm -v
```

**Expected behavior**

For `pnpm` to work in CI.

**Comment by milesj** [comment]
@marcus-sa I'm assuming your using moon's toolchain? The toolchain doesn't make the tools globally available on `PATH`. They're only used by tasks ran within moon.

IMO you shouldn't need to be running these globally anyways, what's your use case?

**Comment by milesj** [comment]
I suppose the action could append `~/.proto/bin` to `PATH`.

**Comment by marcus-sa** [comment]
> @marcus-sa I'm assuming your using moon's toolchain? The toolchain doesn't make the tools globally available on `PATH`. They're only used by tasks ran within moon.
> 
> IMO you shouldn't need to be running these globally anyways, what's your use case?

I want to install dependencies separately of moon in a composite GitHub Action.

**Comment by marcus-sa** [comment]
@milesj why doesn't `moon setup` install dependencies? I'd kind of expect that from that.

**Comment by milesj** [comment]
@marcus-sa moon will automatically install dependencies for you when running `moon ci` or `moon run`. You don't really need to do it yourself.

**Comment by marcus-sa** [comment]
> @marcus-sa moon will automatically install dependencies for you when running `moon ci` or `moon run`. You don't really need to do it yourself.

Yes, but that's not very good DX. It's better to separate the use cases

**Comment by marcus-sa** [comment]
> We suggest against `moon setup` since it's not perfect and is overzealous. If you run tasks, it will only setup/install things that are required.

Interesting approach, why?

The more a command does the harder it is to debug.

**Comment by marcus-sa** [comment]
Also how is that gonna work with caching of dependencies in continuous integration? You usually have separate jobs for that.

**Comment by marcus-sa** [comment]
I reckon people are gonna have a very difficult time migrating to moon because it does everything drastically different for no apparent reason.

**Comment by milesj** [comment]
@marcus-sa What workflow are you trying to achieve exactly? Can probably help guide you.


The reason against `moon setup`, is say you have a repo comprised of 3 languages, Node.js, Go, and Python. There can be any number of moon projects in this repo, with any number of tasks. However, a PR only changes 1 line in 1 file, which only affects (at minimum) 1 project instead of all of them.

In CI, we only want to run tasks for that 1 project. When we do this via `moon ci` or `moon run`, moon will automatically install the language for the required project (let's say Node.js in this case), and will also install dependencies (node_modules). This installs the bare minimum required for CI to complete.

If using `moon setup`, this would unnecessarily install Node.js, Go, and Python, and any dependencies required. This is a ton of unnecessary overhead that moon aims to eliminate.

**Comment by milesj** [comment]
If you don't want this, you can simply not use the toolchain stuff by not setting versions in `toolchain.yml`. At this point, you'll have to setup things yourself using `actions/setup-node`, etc.

**Comment by marcus-sa** [comment]
> @marcus-sa What workflow are you trying to achieve exactly? Can probably help guide you.
> 
> The reason against `moon setup`, is say you have a repo comprised of 3 languages, Node.js, Go, and Python. There can be any number of moon projects in this repo, with any number of tasks. However, a PR only changes 1 line in 1 file, which only affects (at minimum) 1 project instead of all of them.
> 
> In CI, we only want to run tasks for that 1 project. When we do this via `moon ci` or `moon run`, moon will automatically install the language for the required project (let's say Node.js in this case), and will also install dependencies (node_modules). This installs the bare minimum required for CI to complete.
> 
> If using `moon setup`, this would unnecessarily install Node.js, Go, and Python, and any dependencies required. This is a ton of unnecessary overhead that moon aims to eliminate.

Well, but how would you cache installed dependencies then?
Also, afaik rustup is a prerequisite to using the Rust toolchain in `moon ci`, so technically we're already require to install an unnecessary dependency.

**Comment by marcus-sa** [comment]
> If you don't want this, you can simply not use the toolchain stuff by not setting versions in `toolchain.yml`. At this point, you'll have to setup things yourself using `actions/setup-node`, etc.

Yeah, but we'd still like to use toolchains for local development...

**Comment by milesj** [comment]
> How would you cache installed dependencies in continuous integration then?

Are you referring to `node_modules` in this case? You can cache them using `actions/cache`.

**Comment by marcus-sa** [comment]
> > How would you cache installed dependencies in continuous integration then?
> 
> Are you referring to `node_modules` in this case? You can cache them using `actions/cache`.

Yes, but I'm referring to it in regards to affected projects...

**Comment by milesj** [comment]
Yeah if you want to go the "install and cache everything route", you can do that. But I'm still wondering why you want to run `pnpm` commands directly. Something like this should work:

```
permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - uses: moonrepo/setup-moon-action@v1

      - run: moon setup

      - run: moon ci :build :lint :etc
```

But like I said in my other post, I could have the action update `PATH` so tools installed via `moon setup` would be available.
