### ISSUE TITLE
[bug] `query projects` stack overflow

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#1079]
**Describe the bug**

Running `moon query projects` results in:

```
thread 'tokio-runtime-worker' has overflowed its stack
fatal runtime error: stack overflow
```

**Steps to reproduce**

Not entirely sure how to reproduce this, since it probably relies on the repo structure. Here's the `workspace.yml` file:

```yml
# https://moonrepo.dev/docs/config/workspace
$schema: 'https://moonrepo.dev/schemas/workspace.json'

projects:
  - 'apps/*'
  - 'infra/core'
  - 'services/*'
  - '.'

vcs:
  manager: 'git'
  defaultBranch: 'dev'
```

`--log trace` output is 6k+ lines long, so I dumped it into a gist and redacted sensitive bits: https://gist.github.com/shellscape/765445ce5a77bf11cbf73118e1643d09

**Expected behavior**

Project list to be output to console

**Screenshots**

**Environment**

```
MacOS Ventura
Node 18
Moon 1.14.1
```

**Additional context**
