### ISSUE TITLE
[bug] A dependency cycle has been detected for (unknown)

### ISSUE THREAD

**Issue by hckhanh** [moonrepo/moon#1095]
I get this bug when upgrading to 1.14.4

```bash
PS C:\Users\hoang\WebstormProjects\saladin-admin> moon ci :build-staging
▪▪▪▪ Gathering touched files
  .github/workflows/test.yml
▪▪▪▪ Gathering runnable targets
  :build-staging
▪▪▪▪ Generating dependency graph
Target count: 1
Action count: 1
▪▪▪▪ Running targets
Error:   × A dependency cycle has been detected for (unknown).
```

## tasks.yml

```yml
# https://moonrepo.dev/docs/config/tasks
$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  # Dev tasks are used for local development and ci testing.

  dev:
    command: 'vite'
    type: 'run'
    local: true
    args:
      - '--port'
      - '3000'
      - '--host'
    deps:
      - 'vault-pull'
  dev-test:
    command: 'vite'
    type: 'run'
    outputs:
      - 'node_modules/.vite/**/*'
    options:
      persistent: true
    args:
      - '--mode'
      - 'test'
      - '--port'
      - '3000'
      - '--logLevel'
      - 'warn'
      - '--host'

  # Vault tasks are used for managing secrets.

  vault-login:
    command: 'dotenv-vault'
    type: 'build'
    local: true
    args:
      - 'login'
  vault-pull:
    command: 'dotenv-vault'
    type: 'build'
    local: true
    args:
      - 'pull'

  # Test tasks are used for running tests.

  test:
    command: 'cypress'
    type: 'test'
    local: true
    args: 'run'
    deps:
      - 'dev-test'
  cypress:
    command: 'cypress'
    type: 'run'
    local: true
    args: 'open'
    deps:
      - 'dev-test'

  # Lint tasks are used for running linters.

  lints:
    command: null
    type: 'test'
    deps:
      - 'types'
      - 'prettier'
      - 'eslint'
      - 'stylelint'
  types:
    command: 'tsc'
    type: 'test'
    inputs:
      - '**/*.ts'
      - '**/*.tsx'
  prettier:
    command: 'prettier'
    type: 'test'
    args: '--check .'
    inputs:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.json'
      - '**/*.js'
      - '**/*.md'
      - 'index.html'
  eslint:
    command: 'eslint'
    type: 'test'
    args: '**/*.{ts,tsx}'
    inputs:
      - '**/*.ts'
      - '**/*.tsx'
  stylelint:
    command: 'stylelint'
    type: 'test'
    args: 'src/**/*.css'
    inputs:
      - 'src/**/*.css'

  # Report tasks are used for generating reports for sonarcloud.

  reports:
    command: null
    type: 'build'
    deps:
      - 'eslint-report'
      - 'stylelint-report'
  eslint-report:
    command: 'eslint'
    type: 'build'
    args:
      - '--output-file'
      - 'eslint-report.json'
      - '--format'
      - 'json'
      - '**/*.{ts,tsx}'
    inputs:
      - '**/*.ts'
      - '**/*.tsx'
    outputs:
      - 'eslint-report.json'
  stylelint-report:
    command: 'stylelint'
    type: 'build'
    args:
      - '--output-file'
      - 'stylelint-report.json'
      - '--formatter'
      - 'json'
      - 'src/**/*.css'
    inputs:
      - 'src/**/*.css'
    outputs:
      - 'stylelint-report.json'

  # Build tasks are used for building the project.

  build-staging:
    command: 'vite'
    type: 'build'
    args:
      - 'build'
      - '--mode'
      - 'staging'
    options:
      mergeOutputs: replace
    inputs:
      - 'src/**/*'
      - '!src/**/*.cy.*'
      - 'index.html'
      - 'package.json'
      - 'public/**/*'
      - 'vite.config.ts'
    outputs:
      - 'dist/**/*'
  build-production:
    command: 'vite'
    type: 'build'
    args:
      - 'build'
      - '--mode'
      - 'production'
    options:
      mergeOutputs: replace
    inputs:
      - 'src/**/*'
      - '!src/**/*.cy.*'
      - 'index.html'
      - 'package.json'
      - 'public/**/*'
      - 'vite.config.ts'
    outputs:
      - 'dist/**/*'
  notify:
    command: 'node'
    type: 'build'
    args: './scripts/notify-release.js'
    inputs:
      - 'src/**/*'
      - '!src/**/*.cy.*'
      - 'index.html'
      - 'package.json'
      - 'public/**/*'
      - 'vite.config.ts'
```
