### ISSUE TITLE
[bug] allow to opt out of automatic peerDependencies

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#1112]
v0.15 adds automatic peer dependencies for packages.json. This will not always work specially if the package depends on a project that is not a node project.

In my case I have a root moon.yml which is a rust workspace and runs [typeshare](https://github.com/1Password/typeshare) which generates typescript code for rust structs/enums. This is an issue because it then add `
peerDependencies": { "server" : "0.0.0" }` which doesn't make sense. `server` is a rust project so it will never be published to the npm and when I do publish I will be including the generated file as part of the npm package so others don't need to run any build tools.

Moon should either auto detect that it isn't a npm project so don't add peerDependencies or allow us to specify if we want to opt out of automatic peer dependency.

**Comment by milesj** [comment]
The syncing doesn't care what kind of project it is, just that a `package.json` exists in the directory, hence where this is coming from.

Let me think about this. The automatic peer is required for dependent chains to work correctly.

**Comment by bryanjswift** [comment]
This automatic peering is making it so many projects depend on the root workspace as a peer dependency because I have tasks I only want to execute one time in the action graph defined within the root project.

**Comment by milesj** [comment]
@bryanjswift 

> I also have a different case where this added projects as peer dependencies despite the fact they were already direct dependencies of the project.

This should not be the case. We only add the peer if it's already not a dependency. Do you have an example config?

**Comment by prabirshrestha** [comment]
I'm using pnpm workspace so might be if it has `pnpm-workspace.yaml` along side `package.json` don't add it as peer dependencies?

**Comment by bryanjswift** [comment]
> @bryanjswift
> 
> > I also have a different case where this added projects as peer dependencies despite the fact they were already direct dependencies of the project.
> 
> This should not be the case. We only add the peer if it's already not a dependency. Do you have an example config?

It looks like not _all_ of them were listed as direct dependencies so the ones that were listed as direct dependencies as well as the ones that were not got added.

I'm fairly confident this task is the culprit for why the peer dependencies were added

```yml
  artifacts:
    command: 'make'
    args:
      - 'packages/infrastructure/build/AdminApiDependenciesLayer.zip'
      - 'packages/infrastructure/build/AdminApiLambda.zip'
      - 'packages/infrastructure/build/ApiAuthorizerLambda.zip'
      - 'packages/infrastructure/build/ApiIngestAnalyticsLambda.zip'
      - 'packages/infrastructure/build/ApiPublishedAttendeeLambda.zip'
      - 'packages/infrastructure/build/AnalyticsHandlers.zip'
      - 'packages/infrastructure/build/AssetManagementHandlers.zip'
      - 'packages/infrastructure/build/AssetManagementTransformHandler.zip'
      - 'packages/infrastructure/build/BitmovinResourceHandler.zip'
      - 'packages/infrastructure/build/ChromecastReceiver.zip'
      - 'packages/infrastructure/build/CpixHandlers.zip'
      - 'packages/infrastructure/build/DomainManagementHandlers.zip'
      - 'packages/infrastructure/build/EmailHandlers.zip'
      - 'packages/infrastructure/build/LiveSiteApiHandler.zip'
      - 'packages/infrastructure/build/LiveSiteUpdateHandler.zip'
      - 'packages/infrastructure/build/LiveSiteViewHandler.zip'
      - 'packages/infrastructure/build/PusherNotificationLambda.zip'
      - 'packages/infrastructure/build/RemixBuilderAssets.zip'
      - 'packages/infrastructure/build/RemixBuilderHandler.zip'
      - 'packages/infrastructure/build/ShowPublishHandlers.zip'
      - 'packages/infrastructure/build/SitePublishDataDeployHandler.zip'
      - 'packages/infrastructure/build/SitePublishListObjectsHandler.zip'
      - 'packages/infrastructure/build/SitePublishSnapshotPageHandler.zip'
      - 'packages/infrastructure/build/UiSite.zip'
      - 'packages/infrastructure/build/migration-lambda.jar'
    deps:
      - 'database-migrations:artifacts'
      - 'pusher-notification-lambda:artifactsCrate'
      - '@backstage/bitmovin-resource-handler:artifacts'
      - '@backstage/chromecast-receiver:artifacts'
      - '@backstage/messaging-api:artifacts'
      - '@backstage/site-builder:artifacts'
      - '@backstage/ui:artifacts'
      - '@backstage-services/analytics:artifacts'
      - '@backstage-services/asset-management:artifacts'
      - '@backstage-services/cpix:artifacts'
      - '@backstage-services/domain-management:artifacts'
      - '@backstage-services/email:artifacts'
      - '@backstage-services/live-site-view:artifacts'
      - '@backstage-services/show-publish:artifacts'
      - '@backstage-services/site-publish:artifacts'
    options:
      cache: false
      runFromWorkspaceRoot: true
      runInCI: true
      outputStyle: 'buffer-only-failure'
    platform: 'system'
```

Below is the package.json before moon modified it. Moon added all of the workspace dependencies as peer deps along with the other `@backstage/` prefaces packages listed in the `deps` array.

```json
{
  "name": "@backstage/infrastructure",
  "version": "0.1.0",
  "bin": "bin/infrastructure.sh",
  "devDependencies": {
    "@aws-sdk/client-ec2": "^3.420.0",
    "@tsconfig/node18": "^18.2.0",
    "@types/jest": "^29.5.3",
    "@types/node": "^18.17.4",
    "aws-cdk": "^2.99.0",
    "enhanced-resolve": "^5.15.0",
    "jest": "^29.6.2",
    "jest-junit": "^16.0.0",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "@aws-cdk/aws-apigatewayv2-alpha": "^2.99.0-alpha.0",
    "@aws-cdk/aws-apigatewayv2-authorizers-alpha": "^2.99.0-alpha.0",
    "@aws-cdk/aws-apigatewayv2-integrations-alpha": "^2.99.0-alpha.0",
    "@backstage-services/analytics": "workspace:1.0.0",
    "@backstage-services/asset-management": "workspace:1.0.0",
    "@backstage-services/cpix": "workspace:1.0.0",
    "@backstage-services/domain-management": "workspace:1.0.0",
    "@backstage-services/email": "workspace:1.0.0",
    "@backstage-services/live-site-view": "workspace:1.0.0",
    "@backstage-services/livekit": "workspace:1.0.0",
    "@backstage-services/show-publish": "workspace:1.0.0",
    "@backstage-services/site-publish": "workspace:1.0.0",
    "@backstage/api-types": "workspace:1.0.0",
    "@backstage/constructs": "workspace:1.0.0",
    "aws-cdk-lib": "^2.99.0",
    "constructs": "^10.2.70",
    "source-map-support": "^0.5.21"
  },
  "volta": {
    "extends": "../../package.json"
  }
}
```

In this configuration the packages are each responsible for building `.zip` files which are used by CDK when deploying infrastructure and I want to ensure all the `.zip` artifacts exist. The `@backstage/infrastructure` package doesn't have any explicit code dependency on the other projects. The `make` command copies the `.zip` files from the `artifacts` directory of each project into the `packages/infrastructure/build` directory. It works this way because I could not figure out how to get the other projects to write into `packages/infrastructure/build` in a way that didn't break moon caching.
