### ISSUE TITLE
[bug] moon tries to run 'npm install' before running a task

### ISSUE THREAD

**Issue by niieani** [moonrepo/moon#1113]
**Describe the bug**

moon tries to run 'npm install' before running a task, despite being configured to use `yarn`

**Steps to reproduce**

Here are my files:

.moon/tasks.yml
```yml
$schema: https://moonrepo.dev/schemas/tasks.json
fileGroups:
  sources:
    - ./**/*.{ts,tsx,mts,cts,js,jsx,mjs,cjs,json}
  tests:
    - ./**/*.test.{ts,tsx,mts,cts,js,jsx,mjs,cjs,json}
tasks:
  build:
    deps:
      - ~:tsc-esm
  tsc-esm:
    command: tsc --project tsconfig.json
```

.moon/toolchain.yml
```yml
$schema: https://moonrepo.dev/schemas/toolchain.json
node:
  version: 20.7.0
  yarn:
    version: 4.0.0-rc.52
typescript:
  routeOutDirToCache: false
  syncProjectReferences: true
  syncProjectReferencesToPaths: true
  createMissingConfig: true
  rootOptionsConfigFileName: tsconfig.options.json
```

.moon/workspace.yml
```yml
$schema: https://moonrepo.dev/schemas/workspace.json
projects:
  globs:
    - packages/features/*
    - packages/platform/*
  sources: {}
vcs:
  defaultBranch: main
```

1. Created a package in `packages/features/eslint/package.json`.
2. I don't have a moon.yml in the package folder (I'm depending on task inheritance)
3. Trying to run the `tsc-esm` task: `moon run eslint:tsc-esm`
4. Results in `npm install --no-audit --no-fund (in workspace)` getting called, even though moon is configured to use `yarn` in `.moon/toolchain.yml` (as seen above).

**Expected behavior**

The task executes.

**Screenshots**

<img width="699" alt="Screenshot 2023-10-10 at 00 02 50" src="https://github.com/moonrepo/moon/assets/563469/69761ba3-12bb-4a62-b2f4-1ecd3e63fd79">

**Environment**

Not relevant.

**Additional context**
