### ISSUE TITLE
Automatic peer dependencies creating undesired dependencies

### ISSUE THREAD

**Issue by bryanjswift** [moonrepo/moon#1117]
_Originally posted by @bryanjswift in https://github.com/moonrepo/moon/issues/1112#issuecomment-1755987492_

## Context

I have a monorepo where individual packages are responsible for building `.zip` files which are used by CDK (in the `@backstage/infrastructure` package) when deploying infrastructure and I want to ensure all the `.zip` artifacts exist. The `@backstage/infrastructure` package doesn't have any explicit code dependency on the other projects but rather on the presence of artifact files they are responsible for creating. For ease of building I created an `artifacts` target in the `infrastructure` package that lists the other `:artifacts` targets as `deps`.

The `make` target copies the `.zip` files from the `artifacts` directory of each project into the `packages/infrastructure/build` directory. It works this way because I could not figure out how to get the other projects to write into `packages/infrastructure/build` in a way that didn't break moon caching.

## Issue

As a result of the automatic `peerDependency` changes in 1.15 this setup is creating duplicates of `dependencies` in `peerDependencies` as well as defining inaccurate `peerDependencies` because of a convenience task.

## Clues

Not _all_ of the targets in the `deps` of the `infrastructure:artifacts` task were listed as direct dependencies. The ones that were listed as direct dependencies as well as the ones that were not got added as `peerDependencies`.

## Config Files

`packages/infrastructure/moon.yml`

```yml
  artifacts:
    command: 'make'
    args:
      - 'packages/infrastructure/build/AdminApiDependenciesLayer.zip'
      - 'packages/infrastructure/build/AdminApiLambda.zip'
      - 'packages/infrastructure/build/ApiAuthorizerLambda.zip'
      - 'packages/infrastructure/build/ApiIngestAnalyticsLambda.zip'
      - 'packages/infrastructure/build/ApiPublishedAttendeeLambda.zip'
      - 'packages/infrastructure/build/AnalyticsHandlers.zip'
      - 'packages/infrastructure/build/AssetManagementHandlers.zip'
      - 'packages/infrastructure/build/AssetManagementTransformHandler.zip'
      - 'packages/infrastructure/build/BitmovinResourceHandler.zip'
      - 'packages/infrastructure/build/ChromecastReceiver.zip'
      - 'packages/infrastructure/build/CpixHandlers.zip'
      - 'packages/infrastructure/build/DomainManagementHandlers.zip'
      - 'packages/infrastructure/build/EmailHandlers.zip'
      - 'packages/infrastructure/build/LiveSiteApiHandler.zip'
      - 'packages/infrastructure/build/LiveSiteUpdateHandler.zip'
      - 'packages/infrastructure/build/LiveSiteViewHandler.zip'
      - 'packages/infrastructure/build/PusherNotificationLambda.zip'
      - 'packages/infrastructure/build/RemixBuilderAssets.zip'
      - 'packages/infrastructure/build/RemixBuilderHandler.zip'
      - 'packages/infrastructure/build/ShowPublishHandlers.zip'
      - 'packages/infrastructure/build/SitePublishDataDeployHandler.zip'
      - 'packages/infrastructure/build/SitePublishListObjectsHandler.zip'
      - 'packages/infrastructure/build/SitePublishSnapshotPageHandler.zip'
      - 'packages/infrastructure/build/UiSite.zip'
      - 'packages/infrastructure/build/migration-lambda.jar'
    deps:
      - 'database-migrations:artifacts'
      - 'pusher-notification-lambda:artifactsCrate'
      - '@backstage/bitmovin-resource-handler:artifacts'
      - '@backstage/chromecast-receiver:artifacts'
      - '@backstage/messaging-api:artifacts'
      - '@backstage/site-builder:artifacts'
      - '@backstage/ui:artifacts'
      - '@backstage-services/analytics:artifacts'
      - '@backstage-services/asset-management:artifacts'
      - '@backstage-services/cpix:artifacts'
      - '@backstage-services/domain-management:artifacts'
      - '@backstage-services/email:artifacts'
      - '@backstage-services/live-site-view:artifacts'
      - '@backstage-services/show-publish:artifacts'
      - '@backstage-services/site-publish:artifacts'
    options:
      cache: false
      runFromWorkspaceRoot: true
      runInCI: true
      outputStyle: 'buffer-only-failure'
    platform: 'system'
```

Below is the package.json before moon modified it. Moon added all of the workspace dependencies as peer deps along with the other `@backstage/` prefaces packages listed in the `deps` array.

```json
{
  "name": "@backstage/infrastructure",
  "version": "0.1.0",
  "bin": "bin/infrastructure.sh",
  "devDependencies": {
    "@aws-sdk/client-ec2": "^3.420.0",
    "@tsconfig/node18": "^18.2.0",
    "@types/jest": "^29.5.3",
    "@types/node": "^18.17.4",
    "aws-cdk": "^2.99.0",
    "enhanced-resolve": "^5.15.0",
    "jest": "^29.6.2",
    "jest-junit": "^16.0.0",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "@aws-cdk/aws-apigatewayv2-alpha": "^2.99.0-alpha.0",
    "@aws-cdk/aws-apigatewayv2-authorizers-alpha": "^2.99.0-alpha.0",
    "@aws-cdk/aws-apigatewayv2-integrations-alpha": "^2.99.0-alpha.0",
    "@backstage-services/analytics": "workspace:1.0.0",
    "@backstage-services/asset-management": "workspace:1.0.0",
    "@backstage-services/cpix": "workspace:1.0.0",
    "@backstage-services/domain-management": "workspace:1.0.0",
    "@backstage-services/email": "workspace:1.0.0",
    "@backstage-services/live-site-view": "workspace:1.0.0",
    "@backstage-services/livekit": "workspace:1.0.0",
    "@backstage-services/show-publish": "workspace:1.0.0",
    "@backstage-services/site-publish": "workspace:1.0.0",
    "@backstage/api-types": "workspace:1.0.0",
    "@backstage/constructs": "workspace:1.0.0",
    "aws-cdk-lib": "^2.99.0",
    "constructs": "^10.2.70",
    "source-map-support": "^0.5.21"
  },
  "volta": {
    "extends": "../../package.json"
  }
}
```

`packages/infrastructure/package.json` after moon runs

```json
{
  "name": "@backstage/infrastructure",
  "version": "0.1.0",
  "bin": "bin/infrastructure.sh",
  "devDependencies": {
    "@aws-sdk/client-ec2": "^3.425.0",
    "@tsconfig/node18": "^18.2.0",
    "@types/jest": "^29.5.3",
    "@types/node": "^18.17.4",
    "aws-cdk": "^2.99.0",
    "enhanced-resolve": "^5.15.0",
    "jest": "^29.6.2",
    "jest-junit": "^16.0.0",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "@aws-cdk/aws-apigatewayv2-alpha": "^2.99.0-alpha.0",
    "@aws-cdk/aws-apigatewayv2-authorizers-alpha": "^2.99.0-alpha.0",
    "@aws-cdk/aws-apigatewayv2-integrations-alpha": "^2.99.0-alpha.0",
    "@backstage-services/analytics": "workspace:1.0.0",
    "@backstage-services/asset-management": "workspace:1.0.0",
    "@backstage-services/cpix": "workspace:1.0.0",
    "@backstage-services/domain-management": "workspace:1.0.0",
    "@backstage-services/email": "workspace:1.0.0",
    "@backstage-services/live-site-view": "workspace:1.0.0",
    "@backstage-services/livekit": "workspace:1.0.0",
    "@backstage-services/show-publish": "workspace:1.0.0",
    "@backstage-services/site-publish": "workspace:1.0.0",
    "@backstage/api-types": "workspace:1.0.0",
    "@backstage/constructs": "workspace:1.0.0",
    "aws-cdk-lib": "^2.99.0",
    "constructs": "^10.2.70",
    "source-map-support": "^0.5.21"
  },
  "volta": {
    "extends": "../../package.json"
  },
  "peerDependencies": {
    "@backstage-services/analytics": "^1.0.0",
    "@backstage-services/email": "^1.0.0",
    "@backstage-services/live-site-view": "^1.0.0",
    "@backstage-services/site-publish": "^1.0.0",
    "@backstage/bitmovin-resource-handler": "^1.0.0",
    "@backstage/chromecast-receiver": "^0.0.0",
    "@backstage/messaging-api": "^1.0.0",
    "@backstage/site-builder": "^1.0.0",
    "@backstage/ui": "^0.0.0"
  }
}
```
