### ISSUE TITLE
[Question] Passing deps outputs to task command

### ISSUE THREAD

**Issue by b4nst** [moonrepo/moon#1121]
Hey!

I'm trying out moon (really promising so far!) and I'm facing an issue where I have the feeling I'm doing something wrong.
I have a task `build` defined like so:

```yaml
  build:
    platform: system
    command:
      - '$workspaceRoot/tool/buildsystem/build-module.sh'
      - '$project'
      - '@files(tests)'
    deps:
      - '~:vendor'
    inputs:
      - 'globs(tests)'
      - /tool/buildsystem/build-module.sh
    outputs:
      - build/
```

I'm trying to write another task `mytask` which should have the artifacts generated by `build` as argument.
I've tried this:

```yaml
  mytask:
    platform: system
    command: 
      - mycmd
      - '@files(modbuild)'
    deps:
      - '~:build'
    inputs:
      - '@files(modbuild)'
```

whith

```yaml
  modbuild:
    - 'build/*.yaml'
```

However it doesn't work. The first time `mytask` is called, it fails because no arguments are passed to `mycmd`. If I rerun it it works (because `build` has been run during the previous call). The cache also seems to not be properly computed.

Is there a better way to achieve what I'm trying to do?

**Comment by milesj** [comment]
@b4nst Does this work? Curious what the args list is for exactly?

```yaml
  mytask:
    platform: system
    command: 
      - mycmd
    deps:
      - '~:build'
    inputs:
      - '@group(modbuild)'
```

**Comment by b4nst** [comment]
So let me give you the full context, maybe it will be easier:

`build` command generate one or multiple k8s manifests into `./build` directory. This `./build` dir is git ignored.
Here's the actual task I'm trying to run after that (what I simplified `mytask` in the issue):

```yaml
  score:
    platform: system
    command: 
      - kube-score
      - score
      - --ignore-container-cpu-limit
      - --ignore-container-memory-limit
      - --ignore-test
      - container-image-pull-policy
      - --ignore-test
      - pod-networkpolicy
      - --enable-optional-test
      - container-ports-check
      - '@files(modbuild)'
    deps:
      - '~:build'
    inputs:
      - '@files(modbuild)'
```

If I understood the doc correctly, `@group` is replaced with the file group items as-is. So in my case that would translate to something like

```yaml
  score:
    platform: system
    command: 
      - kube-score
      - score
      - --ignore-container-cpu-limit
      - --ignore-container-memory-limit
      - --ignore-test
      - container-image-pull-policy
      - --ignore-test
      - pod-networkpolicy
      - --enable-optional-test
      - container-ports-check
      - build/*.yaml'
    deps:
      - '~:build'
    inputs:
      - build/*.yaml'
```

I see 2 issues here:
1. As documented [here](https://moonrepo.dev/docs/config/project#inputs), files that match the glob, but are ignored via .gitignore will not be considered an input. Hence why I used the `@files` token instead.
1. Although documented as working [here](https://github.com/zegl/kube-score#example-with-static-yamls) the glob passed to `kube-score` command does not work:

    ```shell
    ▪▪▪▪ aria2:score
    Failed to score files: open ./build/*.yaml: no such file or directory
    ```
    I suspect it has something to do with shell expansion.

**Comment by milesj** [comment]
Yeah ok, I think the problem is that tokens (`@files`) get expanded when the project graph is being created, which happens before tasks run.

That's why you get an empty file list on the first run, but not the second. Let me think if there's a better way to implement this internally, because I agree, it's a bit confusing.

For now is it possible to hardcode the build files needed? Or are they non-deterministic?

```
   score:
    platform: system
    command: 
      - kube-score
      - score
      - --ignore-container-cpu-limit
      - --ignore-container-memory-limit
      - --ignore-test
      - container-image-pull-policy
      - --ignore-test
      - pod-networkpolicy
      - --enable-optional-test
      - container-ports-check
      - 'build/a.yml'
      - 'build/b.yml'
    deps:
      - '~:build'
    inputs:
      - 'build/a.yml'
      - 'build/b.yml'
```
