### ISSUE TITLE
[bug] Fails to query touched files when there is only a single commit

### ISSUE THREAD

**Issue by mrobinsn** [moonrepo/moon#1149]
Steps to reproduce:

1) Initialize a fresh repo:
  ```bash
  git init
  moon init --yes
  ```
2) Configure a root moon project and set up a simple moon task:

  `.moon/workspace.yml`:
  ```yaml
  $schema: 'https://moonrepo.dev/schemas/workspace.json'

  projects:
    - '.'
  vcs:
    manager: git
    defaultBranch: main
  ```
  `moon.yml`:
  ```yaml
  $schema: https://moonrepo.dev/schemas/project.json
  language: go
  tasks:
    test:
      command: echo "test"
  ```
3) Make the 1st commit
  ```bash
  git add .moon moon.yml
  git commit -a -m "init"
  ```
4) `moon ci` fails:
  ```bash
  ❯ moon ci
  ▪▪▪▪ Gathering touched files
  Error: process::failed

    × Process git failed with a 128 exit code.
    │
    │ fatal: ambiguous argument 'HEAD~1': unknown revision or path not in the
    │ working tree.
    │ Use '--' to separate paths from revisions, like this:
    │ 'git <command> [<revision>...] -- [<file>...]'
  ```
