### ISSUE TITLE
Fix for "Unable to find an executable binary for yarn"

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#1178]
If you're receiving the error "Unable to find an executable binary for yarn", then continue reading.

## Problem

Yarn >= v1.22.20 (released 11/14/23) changed the way the package was built, and our code for unpacking these versions is now incorrect, resulting in a broken build.

### moon < 1.13

You have a few options here:

- Remove the `yarn.version` setting in `toolchain.yml` (unsure if this will work).
- Drop down to Yarn v1 (instead of v2+).
- Upgrade moon to at minimum v1.13.

### moon >= 1.13 && < 1.16

- Delete Yarn plugins from `~/.proto/plugins`. The fix will automatically be downloaded on next run.

### moon >= 1.16

- Add the following `yarn.plugin` setting in `toolchain.yml`.

```yaml
node:
  yarn:
    plugin: 'source:https://github.com/moonrepo/node-plugin/releases/download/v0.5.1/node_depman_plugin.wasm'
```
