### ISSUE TITLE
[bug] Unable to remove a phantom dependency

### ISSUE THREAD

**Issue by mctrafik** [moonrepo/moon#1183]
**Describe the bug**

Running into this issue now that I think might be a dealbreaker for us to continue to use moon. What happens is that I had added a binary to one of the internal packages (compile tool). In the global `tasks.yml` I have added a dependency to run a shell script within that file (required for the binary). 

I.e I have:

```yaml
tasks:
  compile-package:
    deps:
      - package-tools:build
    command: "compile-package"
```

where the `package-tools:build` populates the script for `compile-package`. 

HOWEVER, now all `tsconfig.json` and `package.json` list a dependency on `package-tools`. This package isn't a dependency! My published packages cannot install now. 

No matter what I've tried to do with settings I'm unable to get this dependency to go away. 

**Steps to reproduce**

See above.

**Expected behavior**

I have `moon.yml` files in other packages where I specify projects they depend on. This extra package shouldn't added!

**Screenshots**

N/A

**Environment**

```
user@H2WGM0PVPJJ9 web-platform % moon --version
moon 1.16.2
user@H2WGM0PVPJJ9 web-platform % node --version
v20.9.0
user@H2WGM0PVPJJ9 web-platform % npm --version
10.1.0
```

**Additional context**

**Comment by milesj** [comment]
@mctrafik If you have a lot of packages, it's probably best to turn this setting off: https://moonrepo.dev/docs/config/toolchain#syncprojectworkspacedependencies

When a task depends on a task from another project, that project becomes an implicit dependency, even if not explicitly configured. It's to ensure the dependency graph resolves all relationships correctly. Unfortunately for `package.json` syncing, it's considered a dependency now.

You can turn it off by marking the dependency as "build", but if there's a lot of packages, then it becomes a bit tedious.

```yaml
dependsOn:
  - id: package-tools
    scope: build
```

We may change this to "build" instead of "peer" in the future based on feedback.

**Comment by mctrafik** [comment]
Yeah, I feel like there should be maybe a scope argument for `deps`. I.e.

```
task:
  foo:
   deps:
     - id: other-project:build
     - scope: build
```

One thing I tried that I don't understand why it didn't help: I changed the type of `apps/package-tools/moon.yml` from `typescript` to `unknown` and it still linked to it which feels like a bug.
