### ISSUE TITLE
[bug] cargo-bin install.exe already exists in destination

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#1195]
Cannot proceed on windows due to cargo bin existing. This is default that comes from GitHub actions and I have not installed it manually.

<img width="934" alt="image" src="https://github.com/moonrepo/moon/assets/287744/5d4ba728-5c49-4661-bb15-fab6fb2b5a45">

**Comment by milesj** [comment]
Let me look into. In the mean time, can comment out the bins stuff.

**Comment by prabirshrestha** [comment]
Unfortunately I cannot because it is required to download [typescript-cli](https://github.com/1Password/typeshare) which I use to convert rust files to typescript types as part of the build.

**Comment by milesj** [comment]
No worries, got a fix in. ~1 hour to get the patch out.

**Comment by prabirshrestha** [comment]
cargo-bin install seems to have been fixed but it can't find the typeshare-cli.exe now.

```
 INFO resolve: Resolving package: 'typeshare-cli@=1.7.0'
 WARN The package typeshare-cli v1.7.0 (x86_64-pc-windows-msvc) has been downloaded from github.com
 INFO This will install the following binaries:
 INFO   - typeshare.exe (typeshare.exe -> C:\Users\runneradmin\.cargo\bin\typeshare.exe)
 INFO Installing binaries...
 INFO Done in 1.1235177s
```

```
▪▪▪▪ client:lint
  client:lint | 
  client:lint | > @objstor/client@0.0.0 lint D:\a\objstor\objstor\apps\client
  client:lint | > eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0
  client:lint | 
▪▪▪▪ client:lint (4s 310ms, 7ea19392)
Error:   × Unable to find a Cargo binary for typeshare. Have you installed the
  │ corresponding dependency?

Error: Process completed with exit code 1.
```


toolchain.yml

```
rust:
  version: '1.74.0' # renovate: datasource=github-releases depName=rust-lang/rust
  # List of Cargo binaries to install globally and make available to tasks.
  bins:
    - bin: 'systemfd@0.4.1'
      local: true
    - bin: 'watchexec-cli@1.23.0'
      local: true
    - 'typeshare-cli@1.7.0'
    - 'cargo-zigbuild@0.17.3'
  components:
    - 'clippy'
    - 'rust-analyzer'
  # Sync the configured version above as a channel to the root `rust-toolchain.toml` config.
  syncToolchainConfig: true
```

moon.yml
```yml
  typeshare-typescript:
    command: typeshare crates/server --lang=typescript --output-file=apps/client/src/models/models.generated.ts
    inputs:
      - crates/server/src/models/*.rs
    outputs:
      - apps/client/src/models/models.generated.ts
```

probably missing `.exe` again?
