### ISSUE TITLE
[feature] Add capability to download and extract files

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#1202]
I'm working on photomaps and would like to be able to download files and extract it to a location.

Github repo: https://github.com/protomaps/basemaps-assets/

Here is the file I would like to download: https://github.com/protomaps/basemaps-assets/archive/refs/heads/main.zip

```yaml
  download_basemaps_assets:
    url: 'https://github.com/protomaps/basemaps-assets/archive/refs/heads/main.zip'
    outputs: 'dest_dir/basemaps-assets.zip'

  extract_basemaps_assets:
    deps:
      - download_basemaps_assets
    zip: 'dest_dir/basemaps-assets.zip'
    outputs: 'public/basemaps-assets'
```

It is possible to have a native task in moon to download and extract zip and tar.gz files as OS might not have curl/wget or unzip/tar installed by default.
