### ISSUE TITLE
[bug] invalid type: map, expected a string on .prototools

### ISSUE THREAD

**Issue by b4nst** [moonrepo/moon#1219]
**Describe the bug**

When using moon with a `.prototools` file to pin version, I get

```shell
Error:   × TOML parse error at line 1, column 1
  │   |
  │ 1 | moon = "~1.17"
  │   | ^^^^^^^^^^^^^^
  │ invalid type: map, expected a string
  │
```

**Steps to reproduce**
Here's my proto file

```toml
moon = "~1.17"
terraform = "~1.5"
sops = "~3.8"

[plugins]
moon="source:https://raw.githubusercontent.com/moonrepo/moon/master/proto-plugin.toml"
sops="source:https://raw.githubusercontent.com/stk0vrfl0w/proto-toml-plugins/main/plugins/sops.toml"
terraform="source:https://raw.githubusercontent.com/theomessin/proto-toml-plugins/master/terraform.toml"

[settings]
auto-install = true
```

**Expected behavior**

moon working

**Screenshots**

**Environment**

```
moon 1.17.4
proto 0.24.0
```

**Additional context**
