### ISSUE TITLE
[bug] Using `@files` token in tasks outputs breaks archiving & hydration

### ISSUE THREAD

**Issue by frankswarm** [moonrepo/moon#1230]
**Describe the bug**

Using `@files` token in tasks outputs breaks archiving & hydration

**Steps to reproduce**
I created a very simple reproduction example:

`.moon/workspace.yml`

```yml
$schema: 'https://moonrepo.dev/schemas/workspace.json'
projects:
  test-project: 'test-project'
``` 

`test-project/moon.yml`

```yml
fileGroups:
  test-output:
   - '/dist/test-project'

tasks:
  build: 
    command: 'pnpm tsc'
    inputs: 
      - '*.{ts,json}'
    outputs:
      - '@files(test-output)'
``` 

This will not have the expected contents in the .moon/outputs compressed file.

Changing `test-project/moon.yml` to this will work as expected:

```yml
tasks:
  build: 
    command: 'pnpm tsc'
    inputs: 
      - '*.{ts,json}'
    outputs:
      - '/dist/test-project'
``` 

**Expected behavior**

The compressed file in .moon/outputs to contains the results of the build.

**Environment**

```
System:
    OS: macOS 14.2
    CPU: (12) arm64 Apple M2 Max
    Memory: 3.00 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.11.0 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
  Managers:
    Homebrew: 4.1.24 - /opt/homebrew/bin/brew
    pip3: 23.2.1 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Bazel: 7.0.0 - /opt/homebrew/bin/bazel
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  IDEs:
    VSCode: 1.85.0 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: javac 21 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.11.6 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 17.2
```
