### ISSUE TITLE
[bug] `moon ci` incorrectly calculating action graph when providing a target that resolves to a task that is a dep of another task

### ISSUE THREAD

**Issue by frankswarm** [moonrepo/moon#1239]
**Describe the bug**

`moon ci` command incorrectly calculates what to execute when a target is passed and points to a task that is a dep of another task. It will execute the task and the one depending on it, even when the target does not include the latter.

**Steps to reproduce**

Make sure you have more than one commit in "main" branch

`workspace.yml`

```yml
$schema: 'https://moonrepo.dev/schemas/workspace.json'

projects:
  test-project: 'test-project'

vcs:
  manager: 'git'
  defaultBranch: 'main'

```

`test-project/moon.yml`

```yml
tasks:
  build-a: 
    command: 'pnpm tsc'
    inputs: 
      - '*.{ts,json}'
  build-b:
    command: 'pnpm tsc'
    inputs: 
      - '*.{ts,json}'
    deps:
     - '~:build-a'
```
Execute:
`moon ci :build-a`

Both `test-project:build-a` and  `test-project:build-b` are executed.

**Expected behavior**

Only `test-project:build-a` is executed

**Environment**

```
  System:
    OS: macOS 14.2
    CPU: (12) arm64 Apple M2 Max
    Memory: 19.49 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.11.0 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
  Managers:
    Homebrew: 4.1.24 - /opt/homebrew/bin/brew
    pip3: 23.2.1 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Bazel: 7.0.0 - /opt/homebrew/bin/bazel
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
  Servers:
    Apache: 2.4.56 - /usr/sbin/apachectl
  Virtualization:
    Docker: 24.0.7 - /usr/local/bin/docker
  IDEs:
    VSCode: 1.85.1 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: javac 21 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.11.6 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.2
```
