### ISSUE TITLE
[bug] command substitution is not working

### ISSUE THREAD

**Issue by delamainer** [moonrepo/moon#1280]
I have `moon.yml` file with the following configuration inside:
```yaml
type: 'application'
tasks:
  build-docker:
    command: 'docker build -t something:$(git rev-parse --short HEAD) .'
    inputs:
      - '**/*'
```

When I run `moon :build-docker` the execution fails with the following error:
```
unknown flag: --short
See 'docker buildx build --help'.
▪▪▪▪ something:build-docker (285ms, 1231eab3)
Error: task_runner::run_failed

  × Task something:build-docker failed to run. View hash details with moon query hash 1231eab3.
  ╰─▶ Process docker failed with a 125 exit code.
```
```
Hash: 1231eab3bfa9315f0eaf14a687118004b909a64925d728917ffe5104bd5ce628

[
  {
    "command": "docker",
    "args": [
      "build",
      "-t",
      "something:$(git",
      "rev-parse",
      "--short",
      "HEAD)",
      "."
    ],
    "deps": {},
    "envVars": {},
    "inputs": {
      ".moon/tasks.yml": "c467e0f150abd2be743b8c55c975e7c11a76ff10",
      ".moon/workspace.yml": "75ccf90708c3b8f35f1367aba3edf65e6ebb45f2",
      "something/Dockerfile": "839ecd87d5d9854f6d70f8325de3ac4835a14f51",
      "something/go.mod": "ec5fc29ab6347f4512ced63aa27526e26798e20b",
      "something/go.sum": "425a8a538f94eae723b788bbc0174ad24ea976b6",
      "something/main.go": "c7ab486c3a323e706213f63f9dd5135f11ad095d",
      "something/main_test.go": "6578bb4cdae1339713489fd25a12a716d37e6cc1"
    },
    "outputs": [],
    "projectDeps": [],
    "target": "something:build-docker",
    "version": "1"
  },
  {
    "arch": "aarch64",
    "os": "macos"
  }
]
```

Moon should support command substitution, or am I doing something wrong?

**Comment by milesj** [comment]
@delamainer We use this to parse args: https://crates.io/crates/shell-words and it doesn't support it.

You can just use an array instead.

```yaml
type: 'application'
tasks:
  build-docker:
    command: 
      - 'docker'
      - 'build'
      - '-t'
      - 'something:$(git rev-parse --short HEAD)'
      - '.'
    inputs:
      - '**/*'
```
