### ISSUE TITLE
[bug] commit-msg hook fails on Windows 11

### ISSUE THREAD

**Issue by amerfarooq** [moonrepo/moon#1338]
**Describe the bug**

I get the following error: 

```
Processing -File '.\.moon\hooks\commit-msg.ps1 .git/COMMIT_EDITMSG  ' failed because the file does not have a '.ps1' extension. Specify a valid Windows PowerShell script file name, and then try again.
```

with the following VCS configuration:

```yml
vcs:
  manager: 'git'
  defaultBranch: 'development'
  syncHooks: true
  hooks:
    pre-commit:
      - moon run :lint --affected --status added --status modified
      - moon run :format --affected --status added --status modified
    commit-msg:
      - npx --yes commitlint --edit

```

**Steps to reproduce**

1. Add the above VCS to your workspace configuration.
1. Perform a commit on Windows.

**Expected behavior**

There should be no error. It seems to be a quoting issue when running the command.

**Screenshots**

**Environment**

```
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 7.92 GB / 31.91 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - ~\AppData\Roaming\npm\npm.CMD
  Managers:
    Cargo: 1.75.0 - ~\.cargo\bin\cargo.EXE
    pip3: 23.3.2 - ~\AppData\Local\Programs\Python\Python310\Scripts\pip3.EXE
  Utilities:
    Git: 2.35.0. - C:\Program Files\Git\cmd\git.EXE
    Curl: 8.4.0 - C:\Windows\system32\curl.EXE
  Virtualization:
    Docker: 24.0.7 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.86.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 5.0.17 - C:\Windows\system32\bash.EXE
    Java: 17.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
    Python: 3.10.2 - C:\Users\Amerf\AppData\Local\Programs\Python\Python310\python.EXE
    Rust: 1.75.0 - C:\Users\Amerf\.cargo\bin\rustc.EXE
  Browsers:
    Edge: Chromium (121.0.2277.112)
    Internet Explorer: 11.0.22621.1
  ```

**Additional context**
