### ISSUE TITLE
[feature] ability to inherit or merge fileGroup(s)

### ISSUE THREAD

**Issue by andrewthauer** [moonrepo/moon#1360]
**Is your feature request related to a problem? Please describe.**

I have a repo where I am trying to keep the moon configuration as DRY as possible by leveraging workspace tasks as much as possible. All projects are very consistent and this works well aside from the root directory / workspace which contains some other random directories that help with the overall toolchain.

My `~/.moon/workspace` has this:

```yaml
projects:
  sources:
    root: '.'
  globs:
    - 'workloads/**'
```

There are some overlapping tasks for `root` and the`workloads/*` projects. However, the main difference is usually that I don't want the root project to glob into the workloads directories. I have this working, but seems like this could be cleaned up as the only difference is the `fileGroups` exclusion glob in `root`.

```yaml
# .moon/tasks.yml (workspace)
fileGroups:
  prettierInputs:
    - '**/*.{md,yml,yaml,js,ts}'

tasks:
  fmt-check-prettier:
    command: prettier --check @files(prettierInputs)

# moon.yml (root)
fileGroups:
  prettierInputs:
    - '**/*.{md,yml,yaml,js,ts}'
    - '!workloads/**'

tasks:
  fmt-check-prettier:
    command: prettier --check @files(prettierInputs)
```

**Describe the solution you'd like**

I think being able to do something like this might help here:

```yaml
# moon.yml (root)
fileGroups:
  prettierInputs:
    - '**/*.{md,yml,yaml,js,ts}'
    - '!workloads/**'

tasks:
  # do not need to redefine the tasks that use @files(prettierInputs)
```

**Describe alternatives you've considered**

If the behaviour of this might be unexpected then perhaps a setting in `workspace.inheritedTasks` that allows this to be overridden.

Another option would be to redefine the task in the project, but have an `options.mergeFileGroups` or something where you can `append`, `replace`, etc.

```yaml
# moon.yml (root)
fileGroups:
  prettierInputs:
    - '**/*.{md,yml,yaml,js,ts}'
    - '!workloads/*'

tasks:
    fmt-check-prettier:
      options:
        mergeFileGroups: 'replace'  # or omit if append is the default
```

**Additional context**

**Comment by andrewthauer** [comment]
For that matter, I don't think this works as I expected either:

```yaml
fileGroups:
  prettierInputs:
    - '**/*.{md,yml,yaml,js,ts}'
    - '!workloads/*'
```
