### ISSUE TITLE
[bug] Persistent Tasks and Dependencies

### ISSUE THREAD

**Issue by rawkode** [moonrepo/moon#1365]
**Describe the bug**

It's my understanding from the docs that persistent tasks are always run last, and kept running.

I'm curious how we should handle cases where we need to apply migrations to a database that needs to be running?

I've included my setup below, which runs `turso dev` to get us a libsql database running. Once it's running, I want to apply the migrations and run `grafbase`; also a persistent task.

**Steps to reproduce**

```yaml
# yaml-language-server: $schema=https://moonrepo.dev/schemas/project.json

# We should add a global flake
# to set MOON_TOOLCHAIN_FORCE_GLOBALS=true
type: application
platform: "system"

project:
  name: shows-service
  description: Microservice for Show Management

tasks:
  install-dependencies:
    command: bun install
    inputs:
      - ./bun.lockb
      - ./package.json
    outputs:
      - ./node_modules

  dev-grafbase:
    deps:
      - install-dependencies
    command: bun x grafbase dev
    options:
      persistent: true

  dev-turso:
    command: turso
    args:
      - dev
      - --port
      - "4021"
    options:
      persistent: true

  dev-turso-generate-migrations:
    deps:
      - install-dependencies
    inputs:
      - ./drizzle/schema
    command: cd drizzle && bunx drizzle-kit generate:sqlite

  dev-turso-apply-migrations:
    deps:
      - dev-turso-generate-migrations
    inputs:
      - ./drizzle/migrations
      - ./drizzle/migrate.ts
    command: cd drizzle && bun migrate.ts

  dev-turso-seed:
    deps:
      - dev-turso-apply-migrations
    inputs:
      - ./drizzle/seed.ts
    command: cd drizzle && bun seed.ts

  dev:
    local: true
    deps:
      - install-dependencies
      - dev-turso
      - dev-grafbase
      - dev-turso-seed
```
