### ISSUE TITLE
[feature] Internal Tasks

### ISSUE THREAD

**Issue by rawkode** [moonrepo/moon#1367]
**Is your feature request related to a problem? Please describe.**

As tasks can only execute a single command, without &&; I've found myself adding lots of tasks to each service; but I only really want a subset of them to be callable from the CLI.

**Describe the solution you'd like**

Use an `internal: true` option that removes the task from the `moon run` list / options.

```yaml
some-intermediate-task:
  command: echo hello
  options:
    internal: true
```
