### ISSUE TITLE
[feature] - generator could base their name on a template.yml variable instead of folder name

### ISSUE THREAD

**Issue by sybernatus** [moonrepo/moon#1373]
**Is your feature request related to a problem? Please describe.**
It's a kind of a problem. Managing an heavy monorepo, you can have many templates in many different templates folders.
So we have to ensure the unicity of templates in their folder name (most of the time we use the path to the template as unique name)

For example: 
```yaml
# repository tree
apps:
  technologies:
    rust:
      templates:
         apps-technologies-rust-templates-my-template
libs:
  workspace:
    technologies:
      bash:
        templates:
          libs-workspace-technologies-bash-templates-my-template
            ...
```

Problem is that is decrease the readability of the repository.

**Describe the solution you'd like**

What I suggest is to use a new `template.yml` property, `name` for example to manage the template name. So the repository could be more readable.
