### ISSUE TITLE
[feature] being able to set a "mutex" option for tasks

### ISSUE THREAD

**Issue by castarco** [moonrepo/moon#1415]
## Is your feature request related to a problem? Please describe:

I have some "local" tasks that are defined at a global level and are executed for all the sub-projects.

Some of these tasks require having exclusive access over certain filesystem resources while they are running (for example, they might need exclusive access over `./.git/index.lock`, but that's not the only case).

I tried to specify the "exclusive resource" path in the `inputs` and `outputs` sections, believing that parallelisation would be reduced if both tasks tried to read/write the same resources... but Moon doesn't seem to use that information to infer that these tasks can run at the same time.

It could be as well that because my "exclusive resource" was in `./.git/`, Moon didn't even try to factor it into its graph computations (I guess it is an ignored file). 

### Solution 1 (not my preferred, just to be more exhaustive)

I think it would be reasonable that Moon takes into consideration the fact that some tasks share the same inputs and outputs to avoid running them at the same time.

I suppose that, under "simple" cases (inputs and output are different from each other), Moon can use this information to refine its dependencies graph beyond what can be obtained from explicit dependencies and dependencies extracted from `package.json` or similar files...

But I suspect that some cases are more complicated, like having multiple tasks with the same `outputs` and different inputs, which gives us no clue as to "who" should have precedence over that file... Although it certainly tells us that, independently of their order, they shouldn't run at the same time because they are generating side effects over the same resource.

Alternatively, if using `outputs` to infer incompatibilities implies having to change too much in Moon's codebase, we could introduce some new field, something like `exclusiveResources`:
```yaml
tasks:
  my.special.task:
    command: 'do something'
    exclusiveResources: # Refers to filesystem resources
      - 'exclusive_resource.lock'
```

The problem with this solution is that it wouldn't be able to consider "resources" outside the immediate scope of Moon (for example, I suspect that "ignored files" wouldn't be factored into the graph computations, as mentioned in the previous section).

### Solution 2 (my preferred)

It would help a great deal being able to add an attribute to some tasks to indicate if they can be run in parallel with their "twins" running in other projects, or, more generally, to indicate if they are "incompatible" with a list of other task references (incompatible to be executed at the same time as the others).

What I think is ideal, with a "virtual mutex", it would make it "incompatible" for parallel execution with any other task sharing the same `mutex` value.
```yaml
tasks:
  my.special.task:
    command: 'do something'
    options:
      # this is an "abstract mutex", not tied to the filesystem, so we
      # don't risk problems related to ignored files, and also allows us
      # to "protect" remote resources that can't be modelled by Moon.
      mutex: 'resource_1'
```
