### ISSUE TITLE
[feature] ignore cache but still validate changes in inputs?

### ISSUE THREAD

**Issue by alexisde** [moonrepo/moon#1500]
When running a task using `moon ci` Is there a way to have a task ignore the cache but still validate and run based on if the inputs where changed?

**Describe the solution you'd like**

My use case is for building docker images, i want to be able to build them only when some files where changed, so i have defined the task like this: 

```
  docker-build:
    command: docker build <project params>
    inputs: 
      - '*.ts'
      - 'src/**/*'
      - '*.json'
      - '/libs/**/*'
```

I call the above using `moon ci :docker-build`, I don't commit my cache to the repository so the docker build always runs in my CI server with ephemeral workers, is there a way to only run the task only based on if the inputs where changed?

I guess i could gate the `moon :docker-build` command by calling `moon query touched-files` and see if those match the inputs? i would expect there to be a native way of doing that?

Thank you!

**Comment by milesj** [comment]
@alexisde CI will only run tasks that are affected by touched files, so only if they match the inputs. This _should_ be doing what you expect. If you inspect the logs, it will tell you what file trigger the affected state.

**Comment by alexisde** [comment]
> @alexisde CI will only run tasks that are affected by touched files, so only if they match the inputs. This _should_ be doing what you expect. If you inspect the logs, it will tell you what file trigger the affected state.

Even if the task hash is not cached? 

i have the task definition on `.moon/tasks/typescript-application.yaml` so it's inherited by a bunch of projects, here's the information from the latest build:

task definition:
```
  containerize:
    command: containerize build --project $project
    options:
      cache: false
      outputStyle: stream
      runFromWorkspaceRoot: true
    inputs: 
      - '*.ts'
      - 'src/**/*'
      - '*.json'
      - '/libs/**/*'
    outputs:
      - 'image_id' 
```

latest run on the CICD server:

```
13:13:48  + moon ci :containerize
13:13:48  ▪▪▪▪ Gathering touched files
13:13:48  pnpm-lock.yaml
13:13:48  .moon/tasks/typescript-application.yml
13:13:48  moon.yml
13:13:48  tools/containerize/moon.yml
13:13:48  tools/containerize/src/build.ts
13:13:48  Jenkinsfile
13:13:48  infra/deployment/helmfile.yaml
13:13:48  .npmrc
13:13:48  ▪▪▪▪ Gathering potential targets
13:13:48    :containerize
13:13:48  ▪▪▪▪ Generating action graph
13:13:48  Target count: 1
13:13:48  Action count: 31
13:13:48  ▪▪▪▪ Running targets
13:13:48  ▪▪▪▪ <app-1>:containerize
13:13:48  ▪▪▪▪ <app-2>:containerize
```


The touched files don't seem to match any of the ones in the task definition, touched files don't contain things on `apps/<app-1>/` or `apps/<app-2>/` or the main `/libs/`tree
