### ISSUE TITLE
`dependencyVersionFormat: 'file'` has no affect [bug] 

### ISSUE THREAD

**Issue by snspinn** [moonrepo/moon#1506]
**Describe the bug**

`dependencyVersionFormat: 'file'` recently stopped having an affect, with npm. I was previously able to copy files into my `node_modules` from a node "library" but it recently started symlinking the files, even with this option set.

Noticed this because I'm relying on being able to copy the entirety of `node_modules` into a docker container and run the project.

**Steps to reproduce**

_Can publish/link a full example project, if needed_

My `toolchain.yml`:
```yaml
node:
  version: '18.20'
  syncProjectWorkspaceDependencies: true
  dependencyVersionFormat: 'file'
```

My pseudo `moon.yml`:
```yaml
type: 'application'
language: 'javascript'
platform: 'node'
stack: 'backend'

tasks:
  install:
    command: 'npm install'
    deps: 
      - 'imported-package:install'
    outputs:
      - 'node_modules/'
```

If I do `ll node_modules`:
```sh
...
lrwxrwxrwx 1 me me  24 Jun 13 16:17 imported-package -> ../../../../libraries/package
...
```

**Expected behavior**

`ll node_modules` to give something like:
```sh
...
drwxrwxr-x 2 me me 4.0K Jun 13 16:17 package
...
```

**Environment**

```
# proto --version
proto 0.36.2

# moon --version
moon 1.25.5

# npx envinfo

  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 20.89 GB / 31.20 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.proto/shims/node
    Yarn: 4.1.1 - ~/.proto/shims/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.15.6 - ~/.proto/shims/pnpm
  Managers:
    Apt: 2.4.12 - /usr/bin/apt
    Cargo: 1.75.0 - ~/.cargo/bin/cargo
    pip3: 22.0.2 - /usr/bin/pip3
  Utilities:
    CMake: 3.22.1 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 11.4.0 - /usr/bin/gcc
    Git: 2.34.1 - /usr/bin/git
    Clang: 14.0.0 - /usr/bin/clang
    Ninja: 1.10.1 - /usr/bin/ninja
    Curl: 7.81.0 - /usr/bin/curl
    OpenSSL: 3.0.2 - /usr/bin/openssl
  Servers:
    Apache: 2.4.52 - /usr/sbin/apachectl
  Virtualization:
    Docker: 26.1.4 - /usr/local/bin/docker
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    VSCode: 1.90.0 - /usr/bin/code
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Go: 1.18.1 - /usr/bin/go
    Perl: 5.34.0 - /usr/bin/perl
    Python: 3.12.3 - /home/me/.proto/shims/python
    Python3: 3.12.3 - /home/me/.proto/shims/python3
    Rust: 1.75.0 - /home/me/.cargo/bin/rustc
  Browsers:
    Brave Browser: 125.1.66.118
    Chrome: 125.0.6422.141
```

**Additional context**

Same issue with proto 0.35.0 and moon 1.24.4
