### ISSUE TITLE
[feature] Add an ability to specify command per OS

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1538]
**Is your feature request related to a problem? Please describe.**

I need to support build for at least two systems (MacOS and Linux) for now which are project specific. The commands can vary quite substantially.  

**Describe the solution you'd like**

I pretty like [just's approach](https://github.com/casey/just?tab=readme-ov-file#enabling-and-disabling-recipes180), where you just writing command with the same name and assigning os attributes to them, so just figures correct version of the command to run itself. 

In moon's case, I think tasks section will need to be reformatted to have tasks defined not as a map, but as an array with id/name of a task, and discriminator by os and potentially more fields.

Like this:
```yaml
tasks:
  - name: build
     os: macos
     ...
  - name: build
     os: unix
     ...
  - name: build
     os: win
     ...
```

Alternative might be some strings patterning, the [same way you doing it with lang/stack/platform specification](https://moonrepo.dev/docs/concepts/task-inheritance#scope-by-project-metadata).
```yaml
tasks:
  build-macos:
     ...
  build-unix:
     ...
  build-win:
     ...
```
But this one would be less preferable as this limits user's freedom on tasks names quite significantly.

**Describe alternatives you've considered**

Alternative perhaps trying to determine the os the same way as it has been done in .sh scripts so far manually.

**Additional context**

No.
