### ISSUE TITLE
[bug] Command output (stdout and stderr) is not printed on system task error

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1539]
**Describe the bug**

I'm trying moonrepo and need to run a lot of custom commands (polyglot repo). For now I'm not using node toolchain and running a lot of commands manually.

This is project definition:

```yaml
# yaml-language-server: $schema=https://moonrepo.dev/schemas/project.json

language: "yaml"
stack: "backend"
type: "configuration"

fileGroups:
  sources:
    - src/**

tasks:
  build:
    platform: system
    command: npx redocly join src/root.yaml $(ls src/*.yaml | grep -v src/root.yaml) -o ./dist/schema.yaml --without-x-tag-groups --lint-config off
    inputs:
      - "@group(sources)"
    outputs:
      - dist
```

Moon reports only npx failed: exit code 1:
```bash
> moon run -i :build
zsh:1: parse error near `$(ls src/*.yaml | gr...'
▪▪▪▪ app-openapi-schema:build (5a26e545)
▪▪▪▪ app-openapi-schema:build (2ms)
Error: task_runner::run_failed

  × Task app-openapi-schema:build failed to run.
  ╰─▶ Process npx failed: exit code 1

```

Running with ```--log=debug``` gives nothing more, it just prints that moon running this command and there is no mention of an error in this logs as well.

**Steps to reproduce**

I'm not sure how, but basically my expectation is that any failed command will print back all the captured stdout and stderr to me, so I have a chance to fix it. Idk if it's like this for every platform and command running through moon.

**Expected behavior**

Expected to print this:
```bash
> npx redocly join src/root.yaml $(ls src/*.yaml | grep -v src/root.yaml) -o ./dist/schema.yaml --without-x-tag-groups --lint-config off
zsh: no matches found: src/*.yaml

    ╔═══════════════════════════════════════════════════════╗
    ║                                                       ║
    ║  A new version of Redocly CLI (1.16.0) is available.  ║
    ║  Update now: `npm i -g @redocly/cli@latest`.          ║
    ║  Changelog: https://redocly.com/docs/cli/changelog/   ║
    ║                                                       ║
    ╚═══════════════════════════════════════════════════════╝

At least 2 apis should be provided. 
```

**Screenshots**

No.

**Environment**

```
 System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 3.55 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.6 - /opt/homebrew/bin/pnpm
  Managers:
    Homebrew: 4.3.7 - /opt/homebrew/bin/brew
    pip3: 24.0 - ~/Projects/backend/.venv/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
    OpenSSL: 3.3.0 - /opt/homebrew/bin/openssl
  Servers:
    Apache: 2.4.58 - /usr/sbin/apachectl
  Virtualization:
    Docker: 25.0.4 - /opt/homebrew/bin/docker
    Docker Compose: 2.24.6 - /usr/local/bin/docker-compose
  IDEs:
    VSCode: 1.90.2 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.34.1 - /usr/bin/perl
    Python: 3.10.14 - /Users/user/Projects/backend/.venv/bin/python
    Python3: 3.10.14 - /Users/user/Projects/backend/.venv/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    PostgreSQL: 14.11 - /opt/homebrew/bin/postgres
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.4.1
```

**Additional context**

No.
