### ISSUE TITLE
[bug] Bun `installArgs` are not being used by Node when bun is the `packageManager`

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1550]
**Describe the bug**

If I use in my toolchain file: 

```yaml
bun:
  installArgs:
    - "--frozen-lockfile"
node:
  packageManager: bun
```

The install arguments are not propagated to the `bun install` for Node tasks. Then I need to repeat it again as in:

```yaml
bun:
  installArgs:
    - "--frozen-lockfile"
node:
  packageManager: bun
  bun:
    installArgs:
      - "--frozen-lockfile"
```

Then it works properly.
