### ISSUE TITLE
[bug] Typescript Project References are created for unnecessary implicit dependencies

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1561]
**Describe the bug**

I have the following structure:

```
/packages
  |-> /tool-cd
  |-> /library-b
```

In `tool-cd` (a commander CLI) that's the `moon.yml`:

```yaml
project:
  name: CD Tools
  description: Tools for continuous delivery
platform: bun
language: typescript
type: tool
stack: infrastructure
tasks:
  cli:
    platform: bun
    command: bun index.ts
    type: run
    local: true
    options:
      persistent: false
      runInCI: false
      cache: false
```

In `library-b` that's the `moon.yml`:

```yaml
language: typescript
platform: bun
type: library
tasks:
  test:
    deps:
      - target: tool-cd:cli
        args: azure login
      - target: tool-cd:cli
        args: keyvault allow
    options:
      runDepsInParallel: false
      mergeDeps: replace
```

In `/.moon/tasks/typescript.yml`:

```yaml
fileGroups:
  sources:
    - package.json
    - src/**/*
    - "**/*.json"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.css"
tasks:
  ... clipped ...
  test:
    platform: bun
    command: bun test
    inputs:
      - "@group(sources)"
    type: test
    deps:
      - "^:test"
    options:
      runInCI: true
      persistent: false
```

My toolchain file:

```yaml
bun:
  syncProjectWorkspaceDependencies: true
  version: latest
  installArgs:
    - "--frozen-lockfile"
node: # Node.js is for running storybooks. They still don't support bun. https://github.com/storybookjs/storybook/issues/23279
  syncProjectWorkspaceDependencies: true
  version: v21.7.3
  packageManager: bun
typescript:
  createMissingConfig: true
  syncProjectReferences: true
  syncProjectReferencesToPaths: true
  routeOutDirToCache: true
```

Because of those dependencies, the library-b gets an implicit dependency of scope `build` on tool-cd and the `syncProjectReferences` config add references in `tsconfig.json`. But this is actually not needed since I don't need the CLI to build the library with `tsc`, which increases time spent in running `moon ci`. This also generates issues with circular dependencies if tool-cd depends on the library to run and the library needs to run a command in order to initialize unit tests.

The only way to solve this is by splitting the tasks in moon.yml for library-b:

```yaml
language: typescript
platform: bun
type: library
tasks:
  azure-login:
    local: true
    type: run
    platform: bun
    command: bun ../tool-cd/index.ts azure login
    options:
      persistent: false
  keyvault-allow:
    local: true
    type: run
    platform: bun
    command: bun ../tool-cd/index.ts keyvault allow
    options:
      persistent: false
  test:
    deps:
      - azure-login
      - keyvault-allow
    options:
      runDepsInParallel: false
      mergeDeps: replace
```
