### ISSUE TITLE
[feature] Possibility to give names to dependent tasks

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1562]
**Is your feature request related to a problem? Please describe.**

Getting a hook on #1561, If `library-b` has this moon.yml:

```yaml
language: typescript
platform: bun
type: library
tasks:
  test:
    deps:
      - target: tool-cd:cli
        args: azure login
      - target: tool-cd:cli
        args: keyvault allow
    options:
      runDepsInParallel: false
      mergeDeps: replace
```

When I run `moon ci`, I will see lots of `tool-cd:cli` but performing different operations.

A very much beneficial improvement would be to give a name parameter to it, so in the logs you could see the real name of it instead of a repeated task name:

```yaml
language: typescript
platform: bun
type: library
tasks:
  test:
    deps:
      - target: tool-cd:cli
        args: azure login
        name: Azure Login
      - target: tool-cd:cli
        args: keyvault allow
        name: Allow Key Vault Firewall
    options:
      runDepsInParallel: false
      mergeDeps: replace
```
