### ISSUE TITLE
[bug] File groups get resolved differently in different contexts

### ISSUE THREAD

**Issue by kikones34** [moonrepo/moon#1563]
**Describe the bug**

File groups get resolved differently in different contexts.
E.g. `/test/path/file.txt` sometimes gets resolved to `../../test/path/file.txt` and other times to `test/path/file.txt`.

**Steps to reproduce**

1. Create a project structure similar to the following:

- monorepo/
  - .moon/
     - tasks.yml
  - services/
     - service1/
        - moon.yml
  - test/
     - path/
        - file.txt

2. Define a file group in `tasks.yml` that references `file.txt` from the monorepo root:

```yml
fileGroups:
  test-file:
    - /test/path/file.txt
```

3. Use this file group in `moon.yml` inside `service1` under different contexts.

    a. In a command:
    ```yml
    test:
      command: 'echo @group(test-file)'
    ```
    Result:
    ```
    ../../test/path/file.txt
    ```

    b. In a script:
    ```yml
    test:
      script: 'echo @group(test-file)'
    ```
    Result:
    ```
    test/path/file.txt
    ```

    c. In an env var:
    ```yml
    test:
      env:
        TEST: '@group(test-file)'
      command: 'echo $TEST'
    ```
    Result:
    ```
    test/path/file.txt
    ```

Note that the behavior is the same when using `@files` rather than `@group`.

**Expected behavior**

In all three cases, the result should be `../../test/path/file.txt`. This is the correct path to `file.txt` relative to `service1`.

Moon version: 1.27.1
