### ISSUE TITLE
[bug] moon query task in case of an error shall report which task causing the error and allow @in to be used in command and scripts with another token defined inputs and outputs

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1566]
**Describe the bug**

Having illegal task definition like this one:

```yaml
# yaml-language-server: $schema=https://moonrepo.dev/schemas/project.json

language: "yaml"
stack: "backend"
type: "configuration"

fileGroups:
  rest: [src/!(root.yaml)]
  root: [src/root.yaml]
  all: [src/*.yaml]
  srcConfig: [redocly.src.yaml]
  genConfig: [redocly.gen.yaml]
  outSchema: [dist/schema.yaml]

platform: system
tasks:
  lint:
    script: npx redocly lint --config @in(0) @in(1)
    inputs:
      - "@files(srcConfig)"
      - "@files(sources)"
  build:
    script: >
      npx redocly join @in(0) @in(1) -o @out(0) --without-x-tag-groups --lint-config off &&
      echo \"security:\n  - bearerAuth: []\" >> @out(0)
    inputs:
      - "@files(root)"
      - "@files(rest)"
    outputs:
      - dist
    deps:
      - "~:lint"

```

And then running moon query tasks, I have an error message saying 

```bash
app % moon query tasks
Error: token_expander::invalid_index_reference

  × Token @in(0) is referencing another token or an invalid value. Only file paths or globs can be referenced by index.
```

**Steps to reproduce**

1. Use the ```moon.yaml``` definition above and run ```moon query tasks```

**Expected behavior**

1. When error is reported it shows which line/command/yaml path caused the error.
E.g.
```bash
app % moon query tasks
Error: token_expander::invalid_index_reference

  × app - tasks.lint.script: Token @in(0) is referencing another token or an invalid value. Only file paths or globs can be referenced by index.
```

2. @in, @out tokens can be used in command/script definitions, when inputs or outputs themselves defined via token.

I don't think that 2 is really hard to achieve, in the end it's a recursive resolution, and taking that files group can't have recursive tokens definition, then we have here maximum 2 levels recursion resolving the actual substitution value. 

**Environment**

```
  System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 79.88 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.6 - /opt/homebrew/bin/pnpm
  Managers:
    Homebrew: 4.3.9 - /opt/homebrew/bin/brew
    pip3: 24.0 - ~/Projects/backend/.venv/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Bazel: 7.1.2 - /opt/homebrew/bin/bazel
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.4.0 - /usr/bin/curl
    OpenSSL: 3.3.1 - /opt/homebrew/bin/openssl
  Servers:
    Apache: 2.4.58 - /usr/sbin/apachectl
  Virtualization:
    Docker: 25.0.4 - /opt/homebrew/bin/docker
    Docker Compose: 2.24.6 - /usr/local/bin/docker-compose
  IDEs:
    VSCode: 1.91.1 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.34.1 - /usr/bin/perl
    Python: 3.10.14 - /Users/artsiommiksiuk/Projects/backend/.venv/bin/python
    Python3: 3.10.14 - /Users/artsiommiksiuk/Projects/backend/.venv/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    PostgreSQL: 14.11 - /opt/homebrew/bin/postgres
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 126.0.6478.128
    Safari: 17.4.1
```

moon 1.27.2
