### ISSUE TITLE
[feature] tokens inside command/scripts shall be considered implicit inputs to command by default

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1567]
**Is your feature request related to a problem? Please describe.**

I have the following task definition:

```yml
tasks:
  lint-src:
    script: npx redocly lint --config @files(srcConfig) @files(all)
    inputs:
      - "@files(srcConfig)"
      - "@files(all)"
    options:
      internal: true
```

As it can be seen, i need to type twice tokens and files groups. Instead, I think it should be a fair assumption, that if some token is mentioned in script or command this token brings it's dependency to the task (as inputs). 

**Describe the solution you'd like**

So, instead of typeing tokens inside command and then repeating it in inputs, I'd like to do it only once in command, and use inputs to specify any implicit dependency which is not directly passed into command.

Like this:
```yml
tasks:
  lint-src:
    script: npx redocly lint --config @files(srcConfig) @files(all)
    options:
      internal: true
```
inputs now has @files(srcConfig) and @files(all) implicitly

**Describe alternatives you've considered**

If not make this behaviour default one - to have an option to infer tokens from command line and add them to input.
Like:

```yaml
options:
   inferInputs: true
```
