### ISSUE TITLE
[bug] Bad variable substitution in scripts

### ISSUE THREAD

**Issue by kikones34** [moonrepo/moon#1590]
**Describe the bug**

Sometimes, moon variables are not properly substituted within scripts. For example, `$projectRoot` may be resolved to `$project` concatenated with the string `Root`.

**Steps to reproduce**

This seems to happen whenever `$project` is used _before_ `$projectRoot`.

E.g.

```yml
tasks:
  test:
    script: echo $project && echo $projectRoot
```

Results in:

```
monorepo
monorepoRoot
```

However, when swapped:

```yml
tasks:
  test:
    script: echo $projectRoot && echo $project
```

The result is:

```
/home/k34/repos/internal/trio-cloud-search
monorepo
```

Note that `command` behaves correctly in both cases.

**Expected behavior**

`$projectRoot` should always be substituted by the project root.
