### ISSUE TITLE
[bug] Sometimes, dependants are not executed when dependencies change in `moon ci`

### ISSUE THREAD

**Issue by kikones34** [moonrepo/moon#1604]
**Describe the bug**

When running `moon ci`, if a touched file affects a dependency of a task that is set to run in CI, but does not affect the task directly, the task is not executed when it contains an `inputs` field.

**Steps to reproduce**

Make tasks not run in CI by default. Add this to the root `tasks.yml`:
```yml
taskOptions:
  runInCI: false
```

Define two tasks as follows inside a project's `moon.yml`:
```yml
  dependency:
    command: echo "I'm the dependency"
    inputs:
      - dependency-input.txt

  dependant:
    deps:
      - dependency
    command: echo "I'm the dependant"
    inputs:
      - dependant-input.txt
    options:
      runInCI: true
```

Commit everything to the default git branch. Now `moon ci` shouldn't execute anything:
```
▪▪▪▪ Gathering touched files
▪▪▪▪ Gathering potential targets
  ...
  trio-cloud-search:dependant
  trio-cloud-search:dependency
  ...
▪▪▪▪ Generating action graph
Target count: 302
Action count: 0
No targets to run based on touched files
```

Modify the file `dependency-input.txt`. Now execute `moon ci`. The `dependant` task is still not executed:
```
▪▪▪▪ Gathering touched files
services/trio-cloud-search/dependency-input.txt
▪▪▪▪ Gathering potential targets
  ...
  trio-cloud-search:dependant
  trio-cloud-search:dependency
  ...
▪▪▪▪ Generating action graph
Target count: 302
Action count: 0
No targets to run based on touched files
```

However, if you do __not__ specify any inputs on the dependant, then it does get executed. Remove the inputs from the `dependant` task, commit the changes. Modify the  `dependency-input.txt`. Run `moon ci`. Now the output is as follows:

```
▪▪▪▪ Gathering touched files
services/trio-cloud-search/dependency-input.txt
▪▪▪▪ Gathering potential targets
  ...
  trio-cloud-search:dependant
  trio-cloud-search:dependency
  ...
▪▪▪▪ Generating action graph
Target count: 302
Action count: 12
▪▪▪▪ Running targets
▪▪▪▪ trio-cloud-search:dependency (7ec34b28)
                        trio-cloud-search:dependency | I'm the dependency
▪▪▪▪ trio-cloud-search:dependency (7ec34b28)
▪▪▪▪ trio-cloud-search:dependant (bfc1e3e2)
                         trio-cloud-search:dependant | I'm the dependant
▪▪▪▪ trio-cloud-search:dependant (1ms, bfc1e3e2)
...
```

**Expected behavior**

Both tasks should be executed always if either `dependency-input.txt` or `dependant-input.txt` are touched.
