### ISSUE TITLE
[bug] Dependency chains are not respected in `moon ci`

### ISSUE THREAD

**Issue by kikones34** [moonrepo/moon#1624]
**Describe the bug**

If you have a dependency chain task1 -> task2 -> task3, when task1 is touched, `moon ci` will only execute task2 and it will not propagate to task3.

**Steps to reproduce**

Configure three tasks as follows:
```yaml
  dependency:
    command: echo "I'm the dependency"
    inputs:
      - dependency-input.txt
    options:
      runInCI: true

  dependency-checker:
    deps:
      - dependency
    command: echo "I'm the dependency checker"
    inputs:
      - dependency-checker-input.txt
    options:
      runInCI: true

  dependent:
    deps:
      - dependency-checker
    command: echo "I'm the dependent"
    inputs:
      - dependent-input.txt
    options:
      runInCI: true
```

Commit everything to the default git branch. `moon ci` shouldn't execute anything.
Now, modify the file `dependency-input.txt` and execute `moon ci`. The `dependency-checker` task is run, but the `dependent` is not:
```text
▪▪▪▪ Gathering touched files
  services/trio-cloud-search/dependency-input.txt
▪▪▪▪ Gathering potential targets
  ...
  trio-cloud-search:dependency
  trio-cloud-search:dependency-checker
  trio-cloud-search:dependent
  ...
▪▪▪▪ Generating action graph
Target count: 335
Action count: 12
▪▪▪▪ Running targets
▪▪▪▪ trio-cloud-search:dependency (faf9f199)
        trio-cloud-search:dependency | I'm the dependency
▪▪▪▪ trio-cloud-search:dependency (faf9f199)
▪▪▪▪ trio-cloud-search:dependency-checker (7f147af2)
trio-cloud-search:dependency-checker | I'm the dependency checker
▪▪▪▪ trio-cloud-search:dependency-checker (7f147af2)
```

**Expected behavior**

The task `dependent` should also be executed since it depends on `dependency-checker`.

**Additional context**

Note that these dependency chains behave correctly regarding the cache logic (so if `dependency` is dirty, it will propagate the dirty state up to `dependent`). The issue only occurs in `moon ci`.

**Comment by milesj** [comment]
@kikones34 This is by design at the moment. The "run dependents" logic only applies to _direct dependents of affected tasks_, and not the entire tree. It was built this way as a simple regression testing mechanism and ensuring a change in a project didn't affect it's immediate consumers.

However, we can probably add an option to control the depth.

**Comment by kikones34** [comment]
@milesj Oh, I see. The problem is that this breaks the way we're managing inter-project dependencies. In the real-world use case, what we actually have is:
- A `check-source-changed` task on each project which gets dirty when the source code of the project changes.
- `check-deps-source-changed` on each project, which has dependencies such as `proj1:check-source-changed`, `proj2:check-source-changed`, etc. It gets dirty whenever one of those project's source is changed.
- Tasks that depend on `check-deps-source-changed`. For example, `test` only gets dirty if the project source or the source of the dependencies has changed.
This has worked perfectly as far as caching goes, but I'm finding it impossible to replicate with the CI feature.

**Comment by milesj** [comment]
@kikones34 Yah that makes sense. Are you able to use `moon run` in CI now to replicate what you want?

**Comment by kikones34** [comment]
Yeah for now we're using `moon run`, but managing the cache is tricky due to the pipelines being run by Bamboo agents, different PRs open on different branches at the same time, etc.
For now it's mostly working, although we are limiting the cache to be per-branch, otherwise many issues arise. That's why we were looking into leveraging the `moon ci` capabilities so that we can always run just the minimum necessary tasks given by the touched files, without having to worry so much about the cache state.

**Comment by milesj** [comment]
I'll look into supporting deep dependents in the next release.

**Comment by milesj** [comment]
I've made some changes in v1.29, can you give that a shot?

**Comment by kikones34** [comment]
I've been checking out the new tracker logs and CLI options `upstream` and `downstream`, but I think there's still no way to pass these to `moon ci`, right? It only seems available for `moon query projects`. I also cannot really test if it would behave as expected for this issue's example, because the options can't be passed to `moon query tasks` either, and I get no information regarding affected tasks using the projects query.
In any case, the introduction of these parameters looks promising, and the tracker logs definitely will help debug stuff moving forwards!

**Comment by milesj** [comment]
Yeah `moon ci` is hard-coded to how it works and probably won't change. I'd rather add this functionality to `moon run`.

**Comment by dudicoco** [comment]
@milesj can you please elaborate on why this is the intended behavior of moon ci?
I believe most use cases require downstream dependents to run when a task changes, otherwise you have to rely solely on task inputs in order to make them affected such a change.

We could put the outputs of a dependency as an inputs for the task like so:
```yaml
# app1
tasks
  build:
    command: build
    inputs:
    - 'src/**/*`
	outputs:
	- bin/main
```

```yaml
# app2
tasks
  build:
    deps:
    - app1:build
    command: build
    inputs:
    - 'src/**/*`
	- /app1/bin/main
```

```yaml
# app3
tasks
  build:
    deps:
    - app2:build
    command: build
    inputs:
    - 'src/**/*`
	- /app2/bin/main
```

However, moon generates the graph before the outputs are generated so this doesn't work.

So it seems that at the current state `moon ci` is actually not suitable to run in CI since a lot of dependant tasks will not be triggered.

**Comment by milesj** [comment]
@dudicoco Why are the outputs of dep task used as inputs for the owning task? This shouldn't be necessary, since the dep task itself is considered an "input".

**Comment by milesj** [comment]
@kikones34 v1.30 now properly supports tasks in the affected tracker, so `moon query tasks` should work better.

**Comment by dudicoco** [comment]
@milesj if my dep task produces an artifact which the next task needs to use as input for its build then this is neccessary.

If you look at how bazel works this happens everywhere basically, for example:
```
go_library(
    name = "lib",
    srcs = ["lib.go"],
)

go_binary(
    name = "bin",
    srcs = ["bin.go"],
    deps = [":lib"],
)
```

**Comment by dudicoco** [comment]
@milesj i'll try to illustrate what I believe is the problem:
```
# app1
tasks:
  build:
    command: echo output1>>file.txt
    inputs:
    - file.txt
    outputs:
    - out/file.txt
```

```
# app2
tasks:
  build:
    deps:
    - app1:build
    command: echo output2>>file.txt
    inputs:
    - /app1/out/file.txt
    outputs:
    - out/file.txt
```

```
# app3
tasks:
  build:
    deps:
    - app2:build
    command: echo output3>>file.txt
    inputs:
    - /app2/out/file.txt
    outputs:
    - file.txt
```

As you can see in this example, app3 needs the input of app2 in order to produce output.
And if a change to app1 doesn't trigger a change to the transitive dependents (app3) then app3 won't be rebuilt.
