### ISSUE TITLE
[feature] Add a `$gitHash` token

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1639]
**Is your feature request related to a problem? Please describe.**

Many times we need to use commit sha's to fill up some info in the applications developed. For example, we use the commit SHA as the version in the deployed frontends and backends.

Today we need to reuse the COMMIT_SHA env variable from the CI run:

```yaml
tasks:
  build-frontend:
    platform: bun
    command: bun --bun run vite build
    inputs:
      - "@group(sources)"
    outputs:
      - dist
    type: build
    deps:
      - build
      - lint
      - format-check
      - test
    env:
      NODE_ENV: production
      VITE_SENTRY_RELEASE: ${COMMIT_SHA}
```

In Github actions for the PR we pass it as an env:

```yaml
- name: Build and Deploy
  run: moon ci
  env:
    COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
```

Or in the main branch:

```yaml

- name: Deploy
  run: moon run :deploy
  env:
    COMMIT_SHA: ${{ github.sha }}
```

But locally if I'm running `moon ci` it would be way more beneficial to have this as a token (`$gitHash` and `$gitHashShort`) so moon could infer this to me by running:

```sh
git rev-parse HEAD
```

Then I wouldn't need to setup this in CI and locally. Moon would be smart enough to fill this up for me so I could use.

**Describe the solution you'd like**

Adding 2 tokens `$gitHash` and `$gitHashShort` so I could use them in the tasks.yaml file like this:

```yaml
tasks:
  build-frontend:
    platform: bun
    command: bun --bun run vite build
    inputs:
      - "@group(sources)"
    outputs:
      - dist
    type: build
    deps:
      - build
      - lint
      - format-check
      - test
    env:
      NODE_ENV: production
      VITE_SENTRY_RELEASE: $gitHash
```

**Describe alternatives you've considered**

Today I inject myself during CI.
