### ISSUE TITLE
[bug] Pass empty values to not expanded environment variables

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1640]
**Describe the bug**

When you don't set an environment variable the value expansion gives the literal value right away which masks potential failures that would happen due to a missing env.

**Steps to reproduce**

Given the current task:

```yaml
tasks:
  build-frontend:
    platform: bun
    command: bun --bun run vite build
    inputs:
      - "@group(sources)"
    outputs:
      - dist
    type: build
    deps:
      - build
      - lint
      - format-check
      - test
    env:
      NODE_ENV: production
      VITE_SENTRY_RELEASE: ${COMMIT_SHA}
```

If I run `moon run project:build-frontend --log=debug` without the COMMIT_SHA env, I get the following:

```
Task value `${COMMIT_SHA}` contains the environment variable $COMMIT_SHA, but this variable is not set. Not substituting and keeping as-is.
```

So in my code when I do:

```js
const sha = process.env.VITE_SENTRY_RELEASE ?? "development"

if (sha === "development") {
  console.log("Yay! You are in development mode")
} else {
  console.log("You are on release mode")
}
```

`sha` will be "${COMMIT_SHA}" when it should be empty. So I cannot take some action in code to assert the environment variable is empty or not set. It would be beneficial to have it empty so we could do proper error handling. Gracefully leaving as is, in my opinion, leads to many bugs hard to debug because of those literal values.

**Expected behavior**

I would expect to either:
- Fail the command if the env is not set, as I set the env expansion myself in the task file. This would be the safest.
- Set an empty value to the env, so we can handle the failure inside the code.
