### ISSUE TITLE
[bug] tasks.build.outputs[1]: token and environment variables are not supported

### ISSUE THREAD

**Issue by owanio1992** [moonrepo/moon#1647]
**Describe the bug**

I read doc [token](https://moonrepo.dev/docs/concepts/token#workspace)

"Tokens are variables and functions that can be used by outputs "
but output only support token function, don't support token variable

**Steps to reproduce**
moon.yml
```
fileGroups:
  storybook:
    - '.storybook/**/*'
    - 'src/**/*'
    - '**/*.stories.*'

tasks:
  build:
    inputs:
      - '@group(storybook)'     # this support 
      - '$workspaceRoot'          # this support 
    outputs:
      - '@group(storybook)'  # this support 
      - '$workspaceRoot'       # this not support
```

moon error msg
```
Error: config::parse::failed

  × Failed to parse projects/nebula-config-service/moon.yml.
  ╰─▶   × tasks.build.outputs[1]: token and environment variables are not supported
```

**Expected behavior**

outputs can use token variable

**Screenshots**

![image](https://github.com/user-attachments/assets/34858366-e685-4ded-96d5-1e0441339c5f)

**Environment**

```
moon 1.28.1
```
