### ISSUE TITLE
[feature] Replace task field only if defined

### ISSUE THREAD

**Issue by kikones34** [moonrepo/moon#1685]
**Is your feature request related to a problem? Please describe.**

We would like to inherit tasks without having to micromanage the merge strategies all the time. By default, we almost always want to *replace* fields rather than *appending* to them, but this causes issues when the fields are not defined. For example, setting the default of all merge strategies to "replace" leads to situations like the following.

In `tasks.yml`:
```yml
do-cool-thing:
   deps:
      - dep1
      - dep2
   command: do-cool-thing arg1 arg2
   inputs:
      - input1
   outputs:
      - output1
```

Then, in some project's local `moon.yml`:
```yml
do-cool-thing:
   command: do-cool-thing-with-another-command different-args
```

When the default strategy is "append", you only need to specify that you want to replace the args. But if it is "replace", then the deps, inputs and outputs of the original task get replaced with nothing, because they are not defined in the local task, so you need to manually specify the "append" strategy for each field other than the args.

**Describe the solution you'd like**

A merge strategy that acts like inheritance in OOP. That is to say, if you inherit from a task, defining a field by default overrides it, and not defining it keeps the original.

This could be accomplished by either modifying the behavior of the current "replace" strategy, or making a new strategy "replace-if-present" or similar. In my opinion, it would make sense that the current "replace" strategy behaved this way, since it is unexpected that not defining a field would remove it rather than inheriting it. If you really want to remove a field from the inherited task, you can always explicitly set it to empty in the local task.

**Describe alternatives you've considered**

Option 1. Setting all merge strategies to "replace" by default and micromanaging the merge strategy of fields that we do *not* want to get modified.

For example, the task in the previous example would end up like this:
```yml
do-cool-thing:
  command: do-cool-thing-with-minor-modification arg-X
options:
  mergeDeps: append
  mergeInputs: append
  mergeOutputs: append
  mergeEnv: append  # for forwards compatibility...
```

Option 2. Setting all merge strategies to "append" by default and micromanaging the merge strategy of fields that we want to replace.

In this case the previous task would get simplified, but other tasks where almost all fields get overridden become really cumbersome, since we would have to specify `mergeXXX: replace` for each field.

With the proposed solution, both types of tasks can coexist without so much hassle: if we want to replace a field, we define it, if we don't, we don't define it. If we want to append to a field, we still need to explicitly set the option, but these cases are rare for our task setup, and I'm compelled to think there must be other people too with setups similar to ours.
