### ISSUE TITLE
[feature] Retrying tasks that failed due to timeout

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1689]
Looks like a bug but I'm adding as feature.

**Is your feature request related to a problem? Please describe.**

Sometimes a task can hang for many different reasons. The `timeout` option covers this case and it's a good option. But if a task finishes in a timeout, it doesn't retry if you configure the `retryCount` option. It stops with the error message:

```
Error:   × Unknown error!
```

**Describe the solution you'd like**

I wanted moon to respect `retryCount` if the `timeout` option is set. So if I have something like:

```yaml
fail:
  platform: system
  command: sleep 10
  type: run
  options:
    persistent: false
    retryCount: 2
    timeout: 5
    cache: false
```

it would run 3 times before failing completely.

**Describe alternatives you've considered**

Today only retrying the whole process (and good caching) solves my problem.

**Additional context**

This is tested on moon 1.29.0
