### ISSUE TITLE
[feature] Allow task platform configuration to be used when a task is extended

### ISSUE THREAD

**Issue by sharpepd** [moonrepo/moon#1693]
**Is your feature request related to a problem? Please describe.**

I am trying to define a task that is used as the base for other tasks. It is important that all the tasks that extend from it have the same "platform" configuration, as it is not the same as the project "language".

But I have found when I tried this that the platform parameter is not being used when extending and I have to specify it on each task separately.

e.g.

```
tasks:
  base_task: "echo"
    args:
      - "Hello"
    platform: system

  ext_task:
    extends: bask_task
    args:
      - "World"
```

**Describe the solution you'd like**

The extended task to have the platform paremeter of the base task, unless overriden.

**Describe alternatives you've considered**

It may be acceptable to define the platform in the tasks.yml similar to taskOptions, so it applies to all tasks in that configuration file.

**Additional context**

None
