### ISSUE TITLE
[feature] Support a `deploy` task type

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1698]
**Is your feature request related to a problem? Please describe.**

`moon check` runs all `test` and `build` type tasks. Very useful for local development and CI. But in CD, after we merge to main, I need to add one naming convention in tasks to be called `deploy` with the following config:

```yaml
# .moon/tasks/backend.yml
tasks:
  deploy:
    command: docker build && docker push
    platform: bun
    type: run
    local: true
    deps:
      - infra-login
      - build-backend
    options:
      persistent: false
      cache: false
```

Then in the CD pipeline I run `moon run :deploy` in order to deploy the whole monorepo.

**Describe the solution you'd like**

It would be good to have one new task type called `deploy` which assume some defaults. This would simplify a lot for the ones configuring the monorepo. Also a command `moon deploy` like `moon check` would be very useful and would make the mental model of using moon very homogeneous, once you could also use the `moon deploy` command to run a deploy to a development environment locally in addition to CD.

So the same task would be:

```yaml
# .moon/tasks/backend.yml
tasks:
  deploy:
    command: docker build && docker push
    platform: bun
    type: deploy
    deps:
      - infra-login
      - build-backend
```

And I could run all deploy tasks with `moon deploy`

**Describe alternatives you've considered**

Today only alternative is to run `moon run :deploy` or using filters or relying on naming conventions.
