### ISSUE TITLE
[bug] error with `yarn-deduplicate` on minimal build

### ISSUE THREAD

**Issue by CluEleSsUK** [moonrepo/moon#1699]
**Describe the bug**

Running a simple `moon project:build` throws an error about `yarn-deduplicate` not existing from inside `yarn-deduplicate`'s code itself.

**Steps to reproduce**

my toolchain.yml is as follows:
```
node:
  version: 22.3.0
  packageManager: 'yarn'
  yarn:
    version: 1.22.22
```

my moon.yml for the project is as follows:
```
language: 'typescript'

tasks:
  build:
    command: 'yarn build'
    inputs:
      - 'lib/**/*'
      - 'src/**/*'
      - 'tsconfig.json'
      - 'package.json'
      - 'foundry.toml'
    outputs:
      - 'output'
      - 'artifacts'
      - 'typechain-types'
      - 'cache'
      - 'cache-hardhat'
```

The following is the build output:
```
me ~/r/myrepo (master) [1]> which yarn-deduplicate
/Users/me/.nvm/versions/node/v22.3.0/bin/yarn-deduplicate

me ~/r/myrepo (master)> moon myproject:build
▪▪▪▪ yarn install
yarn install (in ./myproject)
yarn install v1.22.22
warning ../../../package.json: No license field
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ husky && forge install
.git can't be foundUpdating dependencies in /Users/me/repos/myrepo/myproject/lib
✨  Done in 0.72s.
▪▪▪▪ yarn dedupe
Error: ENOENT: no such file or directory, open 'yarn-deduplicate'
    at Object.readFileSync (node:fs:448:20)
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v22.3.0/lib/node_modules/yarn-deduplicate/dist/cli.js:34:35)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'yarn-deduplicate'
}
Error: process::failed

  × Process /opt/homebrew/bin/fish failed: exit code 1

```

**Expected behavior**

my `yarn build` to run successfully (as it does when run on its own)

**Environment**

```
  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 67.66 MB / 32.00 GB
    Shell: 3.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 22.3.0 - ~/.nvm/versions/node/v22.3.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.3.0/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v22.3.0/bin/npm
```

**Additional context**

I have tried both fish and bash, and `language: 'javascript'`
