### ISSUE TITLE
[feature] Ability to set installArgs on project-level

### ISSUE THREAD

**Issue by mwkcoding** [moonrepo/moon#1712]
**Is your feature request related to a problem? Please describe.**

We have a project that requires us to run `npm install --ignore-scripts` and since I'm currently setting up CI/CD for our monorep, it's frustrating to manually install dependencies in the workflow as the only thing.

**Describe the solution you'd like**

I'd like to be able to define `installArgs` on project-level like I can in `.moon/toolchain.yml`:
```yaml
# in project's moon.yml
toolchain:
  node:
    npm:
      installArgs: '--ignore-scripts'
...
```

**Describe alternatives you've considered**

Adding it globally might work, but also might cause issues in other projects.

**Additional context**

It seems generally weird that the Node `version` is the only property you can define on project-level.
