### ISSUE TITLE
[feature] Allow bin to run on host and docker compose with different CPU architecture

### ISSUE THREAD

**Issue by mortyccp** [moonrepo/moon#1716]
**Is your feature request related to a problem? Please describe.**

In a setup with installing moon with `pnpm` and developing locally with docker compose with mounting the host root directory into container for simplicity, right now moon will have error on the binary version.

This is because moon use postintall to copy the correct binary at install time, so when the moon binary was installed in host machine then later executed in docker compose container, the binary version is not corret.

**Describe the solution you'd like**

It is possible that instead of copying the binary with postinstall, selecting the correct binary at runtime will solve the problem.

**Describe alternatives you've considered**

I have consider to write a Dockerfile that install moon and use that as the base image for the docker compose container, but I think using the pnpm install with pinned version of moon is better.

**Comment by milesj** [comment]
@mortyccp 

> It is possible that instead of copying the binary with postinstall, selecting the correct binary at runtime will solve the problem.

What do you mean selecting at runtime exactly?

Outside of that, I'm not sure how to fix this. The way the packages + postinstall is setup is how they should be structured for npm/pnpm/yarn. The other arch packages (not the host one) probably don't exist in node_modules, because the package managers only install the matching arch package.

**Comment by mortyccp** [comment]
@milesj 

> What do you mean selecting at runtime exactly?
Is it possible to have the entry point be a javascript that wrap the select and execution of the correct binary? Similar to how the postinstall select the correct binary but just change to execute the binary instead.

> The other arch packages (not the host one) probably don't exist in node_modules, because the package managers only install the matching arch package.

Most package managers have config to install other arch packages
- https://docs.npmjs.com/cli/v10/configuring-npm/package-json#os
- https://pnpm.io/package_json#pnpmsupportedarchitectures
- https://yarnpkg.com/configuration/yarnrc#supportedArchitectures

**Comment by mortyccp** [comment]
@milesj 
I found a workaround now, instead of directly mounting the node_modules or build a base image, I workaround with separating the node_modules and install inside of the container

```
services:
  pnpm:
    image: registry.scmp.tech/docker-hub/product/web/node:20
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
      - pnpm_store:/workspace/.pnpm-store
    env_file:
      - ./services/vault/.env
    command: pnpm install
    tty: true

  app:
    container_name: rosetta-app
    image: registry.scmp.tech/docker-hub/product/web/node:20
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
      - pnpm_store:/workspace/.pnpm-store
    depends_on:
      pnpm:
        condition: service_completed_successfully
    ports:
      - '8301:8080'
    env_file:
      - ./services/vault/.env
    command: pnpm moon

volumes:
  node_modules:
  pnpm_store:
```
