### ISSUE TITLE
[bug] AffectedPassInputs does not work when inputs are missing

### ISSUE THREAD

**Issue by dudicoco** [moonrepo/moon#1732]
**Describe the bug**

When configuring a task with `affectedPassInputs: true`, if the inputs are missing the dir will be passed as an arg to the command.

**Steps to reproduce**

Define the following task:
```yaml
  format:
    command: echo
    inputs:
    - '*.sh'
    options:
      affectedFiles: true
      affectedPassInputs: true
```

If no `sh` files exist the task will echo `.`.

**Expected behavior**

If we pass an empty string the formatter/linter might fail.
Perhaps the task command should be skipped in this case?
