### ISSUE TITLE
[feature] Ability to use globs when specifying tasks for `moon run` and task `deps`

### ISSUE THREAD

**Issue by chadrik** [moonrepo/moon#1762]
**Is your feature request related to a problem? Please describe.**

I have tasks that match a naming convention, like this:

```
$ moon query tasks 'task~test-*'
core
        test-3.11 | python | test | system | Run tests
        test-3.10 | python | test | system | Run tests
        test-3.9 | python | test | system | Run tests
houdini
        test-20.5 | python | test | system | Run tests
observability
        test-3.10 | python | test | system | Run tests
        test-3.7 | python | test | system | Run tests
```

The numbered suffixes correspond to a version of the underlying component that can be tested individually. 

As a developer, if I want to run all of the tests for a given project, it's annoying to have to specify all of them:

```
moon run core:test-3.11 core:test-3.10 core:test.3.9
```

Using a query to reduce the repetitiveness is not any better:
```
moon run :test-3.11 :test-3.10 :test.3.9 --query project=core
```

**Describe the solution you'd like**

Ideally, I could use a glob to specify tasks, so that running all of the tests would be as simple as this:

```
moon run 'core:test-*'
```

Special glob characters `*`, `?`, and `[]` are disallowed in task names, so it would be clear when a target is intended to be a glob.

**Describe alternatives you've considered**

The obvious alternative here is to create a task in each project that gathers together all of the versions of the tasks:

`core/moon.yml`
```yml
tasks:
  # override the global test task to add variants
  test-3.11:
    extends: _test
    options:
      internal: false  # override the base task
    args: ['--extra-package=python-3.11']

  test-3.10:
    extends: _test
    options:
      internal: false  # override the base task
    args: ['--extra-package=python-3.10']

  test-3.9:
    extends: _test
    options:
      internal: false  # override the base task
    args: ['--extra-package=python-3.9']

  tests:
    deps:
      - ~:test-3.9
      - ~:test-3.10
      - ~:test-3.11
    options:
      runDepsInParallel: false
```

The problem is that this boilerplate `tests` task needs to be copied into the `moon.yml` of each project, and the version list needs to be kept up-to-date.   This works against moon's great inheritance capabilities, which helps keep config DRY. 

If globs were valid targets not only for `moon run`, but also for task deps, then I could create a global task that would be inherited by all projects, like this:

`.moon/tasks.yml`
```yml
tasks:
  tests:
    deps:
      - '~:test-*'
    options:
      runDepsInParallel: false
```

With this, I would have the best of both worlds.   I could run all tests using my handy inherited shortcut task, like this:

```
moon run core:tests
```

Or I could specify ad hoc task globs on the CLI, for example to run all tests targeting version  >=3.10:

```
moon run 'core:test-3.1?' 
```

(reminder: `?` is a glob that is a wild card for any single character.  Alternatively, one could use a character range to limit the glob to numbers: `'core:test-3.1[0-9]'`).
