### ISSUE TITLE
[bug]  Task output not prefixed consistently

### ISSUE THREAD

**Issue by chadrik** [moonrepo/moon#1775]
**Describe the bug**

**Steps to reproduce**

`.moon/tasks.yml`:

```yaml
tasks:

  foo:
    command: 'echo "foo running"'

  bug:
    command: 'echo "bug running"'
    options:
      cache: false

  lint:
    deps: [bug, foo]
    command: "echo 'lint running'"
```

```
$ moon run ocio:lint -u
bug running
▪▪▪▪ ocio:bug
▪▪▪▪ ocio:bug (2ms)
▪▪▪▪ ocio:foo (abe36ae1)
 ocio:foo | foo running
▪▪▪▪ ocio:foo (1ms, abe36ae1)
▪▪▪▪ ocio:lint (ef8141cc)
lint running
▪▪▪▪ ocio:lint (1ms, ef8141cc)

Tasks: 3 completed
 Time: 33ms
```

Note that `bug running` is not prefixed with `ocio:bug |`.  Same for `lint running`.

If I set `bug.cache: true` the output changes:

```
$ moon run ocio:lint -u
▪▪▪▪ ocio:bug (ff047264)
 ocio:bug | bug running
▪▪▪▪ ocio:bug (2ms, ff047264)
▪▪▪▪ ocio:foo (e5b1bf7f)
 ocio:foo | foo running
▪▪▪▪ ocio:foo (1ms, e5b1bf7f)
▪▪▪▪ ocio:lint (976a6baf)
lint running
▪▪▪▪ ocio:lint (1ms, 976a6baf)

Tasks: 3 completed
 Time: 36ms
```

It now correctly prints ` ocio:bug | ocio running` but `lint` is still not prefixed.

**Expected behavior**

My expectation is that if there is more than one task being run, all output should be prefixed with the full task name, and that output formatting should not be affected by the `cache` setting. 

**Screenshots**

**Environment**

```
$ moon --version
moon 1.30.6
```

**Additional context**
