### ISSUE TITLE
[bug] ctrl-c does not stop another process if one is interactive

### ISSUE THREAD

**Issue by hackwaly** [moonrepo/moon#1781]
**Describe the bug**

**Steps to reproduce**

package.json
```
{
  "private": true,
  "scripts": {
    "dev": "moon run dev",
    "devTest": "moon run devTest"
  },
  "devDependencies": {
    "@moonrepo/cli": "^1.30.6",
    "rescript": "12.0.0-alpha.7",
    "vitest": "^2.1.8"
  }
}
```

moon.yml
```
tasks:
  dev:
    command: rewatch watch
    local: true

  devTest:
    command: vitest
    local: true
    deps:
      - dev
```

1. run `pnpm devTest` in terminal
2. press ctrl-c
3. run `pnpm devTest` in terminal
4. you'll see `rewatch watch` failed because previous `rewatch` process doesn't exit as expected.

**Expected behavior**

**Screenshots**

**Environment**

```

```

**Additional context**
