### ISSUE TITLE
[bug] moon.yml dependsOn does not work as expected

### ISSUE THREAD

**Issue by sharpepd** [moonrepo/moon#1785]
In the docs https://moonrepo.dev/docs/config/project#dependson it says "The most common use case for this is building those projects before building this one". I am unsure what that really means and the behaviour I am seeing does not fit with what I would expect.

If I have two projects app1 & app2 and app1 is dependent on app2, then I am expecting ALL tasks of app2 to be completed before app1 tasks are attempted.

But this is not what I am observing.

**Steps to reproduce**

I setup a simple moon set-up:

workspace.yml
```
projects:
  - 'apps/*'
```

apps/app1/moon.yml
```
dependsOn:
  - app2
tasks:
  build:
    script: 'echo "Building app1"'
  deploy:
    script: 'echo "Deploying app1"'
    deps: 
    - build
```

apps/app2/moon.yml
```
tasks:
  build:
    script: 'echo "Building app2"'
  deploy:
    script: 'echo "Deploying app2"'
    deps: 
    - build
```

When I run `moon run :deploy --summary`

I get the running order (summary only shown)
```
pass SyncWorkspace (1ms)
skip SetupToolchain(system) (skipped, 2ms)
pass SyncProject(system, app2) (1ms)
pass SyncProject(system, app1) (2ms)
pass RunTask(app2:build) (837ms)
pass RunTask(app1:build) (834ms)
pass RunTask(app1:deploy) (814ms)
pass RunTask(app2:deploy) (839ms)
```

**Expected behavior**

For the above example I am expecting:
```
[... skip to RunTasks]
pass RunTask(app2:build) (846ms)
pass RunTask(app2:deploy) (869ms)
pass RunTask(app1:build) (832ms)
pass RunTask(app1:deploy) (878ms)
```

**Screenshots**

N/A

**Environment**

Issue observed in Moon 1.31.0  (also earlier versions)
I am operating on windows 10

**Additional context**

It can be I am just misunderstanding what it means, in which case the documentation could be improved to clarify, or there is an issue here!

**Comment by milesj** [comment]
It doesn't happen automatically, you need to use the `^:` target in task dependencies. Running everything by default is a bad idea.

https://moonrepo.dev/docs/concepts/target#dependencies-

**Comment by sybernatus** [comment]
If I understant the usecase, I think @sharpepd is right, he has 2 projects with 2 targets `build` & `deploy` and in both projects `deploy` target have the `build` target dependency within the project itself.
Which mean that:
- `moon run app1:deploy` will trigger `app1:build`
- `moon run app2:deploy` will trigger `app2:build`

Then he declared a dependsOn: ["app2"] in the app1 project.

Which mean that:
- running `moon run app1:build` will trigger `app2:build` too
- running `moon run app1:deploy` *should* run:
  - `app2:deploy` which runs `app2:build` before because it has it as a dependency
  - then `app1:build` 
  - then `app1:deploy`

So the full graph should be the following:

```mermaid
flowchart TD
app2-build --> app2-deploy
app2-deploy --> app1-build
app1-build --> app1-deploy
```

**Comment by milesj** [comment]
@sybernatus That's not how it works baed on his configuration. His tasks would need to be this:

```
dependsOn:
  - app2
tasks:
  build:
    script: 'echo "Building app1"'
    deps:
    - ^:build # this references dependsOn
  deploy:
    script: 'echo "Deploying app1"'
    deps: 
    - build
```
