### ISSUE TITLE
[bug] `moon ci` results in different actions plan on GHA and local

### ISSUE THREAD

**Issue by artsiommiksiuk** [moonrepo/moon#1791]
**Describe the bug**

On CI, with GHA, I'm using this setup:

```yml
  docker-build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - uses: extractions/setup-just@v2
      - uses: moonrepo/setup-toolchain@v0
      - uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
      - uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"

      - run: moon ci --color :docker-push-ci --cache=read

      - uses: appthrust/moon-ci-retrospect@v1
        if: success() || failure()
```

Which results moon assembling this info:

![image](https://github.com/user-attachments/assets/31865c99-13be-44a2-b2f4-9f53393815d8)

![image](https://github.com/user-attachments/assets/b3b57feb-b387-42a9-a223-cf1fa5f823e7)

All qrmap:* tasks never should've been picked up (nothing was changed from it's dependencies). 

Meanwhile on local machine I can't reproduce it even if I specifically setting up MOON_BASE and MOON_HEAD to simulate what CI suppose to see.

![image](https://github.com/user-attachments/assets/b49a0ff1-e038-469c-8c83-8639dbe9ee5a)

It does not picks qrmap as something needing change. Which is correct.

**Steps to reproduce**

I really don't know how to make good reproducible example, and I'm not excluding that I don't understand something.

**Expected behavior**

CI moon ci run behaves the same as local.

Or, if it is some configuration error from my side, I want to know how to make `moon ci :some-command` still honor only affected targets and run only specific command, like run :some-command only for targets been affected by current commit.

**Screenshots**

-

**Environment**

```

  System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 117.92 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.14.2 - ~/Library/pnpm/pnpm
  Managers:
    Homebrew: 4.4.15 - /opt/homebrew/bin/brew
    pip3: 24.2 - ~/Projects/backend/.venv-apps-qrmap/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Bazel: 7.4.0 - /opt/homebrew/bin/bazel
    Make: 3.81 - /usr/bin/make
    GCC: 15.0.0 - /usr/bin/gcc
    Git: 2.39.3 - /usr/bin/git
    Clang: 15.0.0 - /usr/bin/clang
    Curl: 8.6.0 - /usr/bin/curl
    OpenSSL: 3.4.0 - /opt/homebrew/bin/openssl
  Servers:
    Apache: 2.4.58 - /usr/sbin/apachectl
  Virtualization:
    Docker: 27.4.0 - /usr/local/bin/docker
    Docker Compose: 2.31.0 - /usr/local/bin/docker-compose
  IDEs:
    VSCode: 1.96.0 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.23.4 - /opt/homebrew/bin/go
    Perl: 5.34.1 - /usr/bin/perl
    Protoc: 28.3 - /opt/homebrew/bin/protoc
    Python: 3.10.15 - /Users/artsiommiksiuk/Projects/backend/.venv-apps-qrmap/bin/python
    Python3: 3.10.15 - /Users/artsiommiksiuk/Projects/backend/.venv-apps-qrmap/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    PostgreSQL: 14.13 - /opt/homebrew/bin/postgres
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 131.0.6778.265
    Safari: 17.5
```

**Additional context**
