### ISSUE TITLE
[feature] cleanup task / dependency after / finally

### ISSUE THREAD

**Issue by mi4uu** [moonrepo/moon#1815]
I'm really missing option to define cleanup task option, what I mean is in same way I'm doing deps I sometime want to run command/script after previous command, and yes I can create wrapper command that run the first one as dep, but what if it fails? 
i would like to have a way to make a deps that's runs after my task no matter if this task was success or fail, or even better, it might pass the output and return code to this cleanup task.

**Describe the solution you'd like**

simple example (nextjs modify tsconfig ) :

```
tasks:
  backup-config:
    script: 'cat tsconfig.json > .tsconfig.back.json'
 build:
    command: 'next build'
    deps:
        -  '~:backup-config'
    after:
       - '~:restore-config'
restore-config:
    script: 'mv .tsconfig.back.json tsconfig.json'
    
```

**Describe alternatives you've considered**

 any current solution to this problem (above example is trival, but solution to this feels kind of clunky) need right now extra steps, and things like custom wrappers
