### ISSUE TITLE
[bug] `moon project-graph` stays alive after ctrl-c, and resists attempts to SIGTERM it!

### ISSUE THREAD

**Issue by johnpyp** [moonrepo/moon#1844]
**Describe the bug**

I ran `moon project-graph` in a new project that had just initialized with bare minimum configuration, and ctrl-c'd it. Later trying to bind to port 8000, I realized it was still alive!

I then tried to kill it via `pkill -f 'project-graph'` and htop separately. For whatever reason, it resisted attempts to kill it, and spawned multiple other processes.

Only via `pkill -f 'project-graph -9` was I actually able to kill it.

**Steps to reproduce**

1. Run `moon project-graph`
2. ctrl-c
3. Verify there's still a `project-graph` process running.
4. Attempt to SIGTERM that process
5. Verify there's still `project-graph` process(es) running

**Expected behavior**

It should just work with ctrlc, and of course not evade SIGTERMs.

**Screenshots**

N/A

**Environment**

```
System:
    OS: Linux 6.11 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 42.41 GB / 61.96 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.local/share/mise/installs/node/20.14.0/bin/node
    pnpm: 9.15.5 - ~/.local/share/mise/installs/npm-pnpm/9.15.5/bin/pnpm

Moon version: 1.32.6
# (other fields omitted for brevity)

```

**Additional context**

My configuration:
```yml
# https://moonrepo.dev/docs/config/workspace
$schema: 'https://moonrepo.dev/schemas/workspace.json'

# Require a specific version of moon while running commands, otherwise fail.
# versionConstraint: '>=1.0.0'

# Extend and inherit an external configuration file. Must be a valid HTTPS URL or file system path.
# extends: './shared/workspace.yml'

# REQUIRED: A map of all projects found within the workspace, or a list or file system globs.
# When using a map, each entry requires a unique project ID as the map key, and a file system
# path to the project folder as the map value. File paths are relative from the workspace root,
# and cannot reference projects located outside the workspace boundary.
projects:
  - 'packages/*'
  - 'scripts'
  - 'vendor/*'

# Configures the version control system to utilize within the workspace. A VCS
# is required for determining touched (added, modified, etc) files, calculating file hashes,
# computing affected files, and much more.
vcs:
  # The client to use when managing the repository.
  # Accepts "git". Defaults to "git".
  manager: 'git'

  # The default branch (master/main/trunk) in the repository for comparing the
  # local branch against. For git, this is is typically "master" or "main",
  # and must include the remote prefix (before /).
  defaultBranch: 'main'
```
and `toolchain.yml`
```yml
node:
  packageManager: 'pnpm'
```
