### ISSUE TITLE
[feature] Repeated installation of trusted-signing-cli causes Cargo error

### ISSUE THREAD

**Issue by TadasMil** [moonrepo/moon#1850]
**Is your feature request related to a problem? Please describe.**

In our CI/CD pipeline, every time we run moon ci, MoonRepo re-installs all configured binaries. In the case of trusted-signing-cli, this results in Cargo throwing an error because the binary already exists:

```
▪▪▪▪ cargo binstall
 INFO resolve: Resolving package: 'trusted-signing-cli'
 WARN The package trusted-signing-cli v0.5.0 will be installed from source (with cargo)
    Updating crates.io index
error: binary `trusted-signing-cli` already exists in destination
Add --force to overwrite
ERROR Cargo errored! ExitStatus(unix_wait_status(25856))
```

**Describe the solution you'd like**

It would be great if MoonRepo could either:

- Automatically detect that the binary already exists and either skip the installation step, or
- Provide an option to automatically pass the --force flag for certain binaries in the configuration (for example, via an additional property for each bin).

Ideally, this behavior should be configurable per binary, allowing users to decide whether to force reinstall or simply skip if the binary is already present.

**Describe alternatives you've considered**

```
 - bin: 'trusted-signing-cli'
      installArgs: ['--force']
```

**Additional context**

.toolchain.yml:
```
rust:
  version: '1.85.0'
  syncToolchainConfig: true
  targets: ['x86_64-pc-windows-msvc']
  bins: ['cargo-watch', 'tauri-cli@2.3.1', 'cargo-xwin', 'trusted-signing-cli']
  components: ['rustfmt', 'rust-analyzer']
```
