### ISSUE TITLE
[bug] moon always "installs" older version of proto

### ISSUE THREAD

**Issue by castarco** [moonrepo/moon#1862]
**Describe the bug**

Although `proto` is already installed, available and pinned, `moon` keeps:
- "installing" `proto` every time I run it
- using an older version that does not match the pinned one (0.45.2 instead of 0.46.1)
- and consequently adding ~1.5s to the execution time of all my `moon` commands.

**Steps to reproduce**

0. Configure `.bashrc` and/or similar init scripts to automatically set the correct set of tools every time I enter into a directory with the `.prototools` file.
   ```bash
   eval "$(proto activate bash)";
   ```
1. Have a `.prototools` file like the following one in the project directory:
   ```toml
   deno = "2.2.3"
   moon = "1.32.8"
   proto = "0.46.1" # NOTICE the pinned version here
   tofu = "1.9.0"

   [plugins]
   jnv = "https://raw.githubusercontent.com/appthrust/proto-toml-plugins/main/jnv/plugin.toml"
   tofu = "https://raw.githubusercontent.com/appthrust/proto-toml-plugins/main/tofu/plugin.toml"

   [settings]
   auto-clean = true
   auto-install = true
   detect-strategy = "prefer-prototools"
   pin-latest = "local"
   ```
2. Define a task file like the next one:
   ```yaml
   $schema: 'https://moonrepo.dev/schemas/tasks.json'

   tasks:
     init:
       command: 'tofu init'
       inputs:
         - '.terraform/providers/**/*'
         - '.terraform.lock.hcl'
         - 'providers.tf'
       outputs:
         - '.terraform/providers/**/*'
         - '.terraform.lock.hcl'

     validate:
       command: 'tofu validate .'
       deps:
         - '~:init'
       inputs:
         - '.terraform/providers/**/*'
         - '.terraform.lock.hcl'
         - 'main.tf'
         - 'outputs.tf'
         - 'providers.tf'
         - 'variables.tf'
   ```
3. Run a `moon` command, such as `moon tf:validate`
4. See the result:
   - It always starts with `▪▪▪▪ installing proto 0.45.2`
   - It is always around 1.5s slower than it should (`moon` itself only takes less than 200ms to run the "real work").

**Expected behavior**

- `moon` shouldn't waste time trying to install an older version of `proto` that doesn't even match the pinned and available one.

**Screenshots**

<img width="720" alt="Image" src="https://github.com/user-attachments/assets/58530eca-7db2-416d-aa59-2b623a9c09f2" />

**Environment**

`proto --version`
```
proto 0.46.1
```

`proto status`
```
╭────────────────────────────────────────────────────────────────────────────────────────────────────╮
│Tool        Configured    Resolved      Installed                    Config                         │
│────────────────────────────────────────────────────────────────────────────────────────────────────│
│deno        2.2.3        2.2.3         /Users/user/.proto/tools/     /Users/user/code/.prototools   │
│                                       deno/2.2.3                                                   │
│jnv         0.5.0        0.5.0         /Users/user/.proto/tools/     /Users/user/code/.prototools   │
│                                       jnv/0.5.0                                                    │
│moon        1.32.8       1.32.8        /Users/user/.proto/tools/     /Users/user/code/.prototools   │
│                                       moon/1.32.8                                                  │
│tofu        1.9.0        1.9.0         /Users/user/.proto/tools/     /Users/user/code/.prototools   │
│                                       tofu/1.9.0                                                   │
╰────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

`moon --version`
```
moon 1.32.8
```

`pnpm dlx envinfo`
```
  System:
    OS: macOS 15.3.1
    CPU: (24) arm64 Apple M2 Ultra
    Memory: 811.77 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.14.0 - ~/.proto/shims/node
    Yarn: 3.6.1 - ~/.local/state/fnm_multishells/85792_1741521834668/bin/yarn
    npm: 10.9.2 - ~/.proto/shims/npm
    pnpm: 10.4.1 - ~/.proto/shims/pnpm
    bun: 1.2.2 - ~/.proto/shims/bun
  Managers:
    Cargo: 1.83.0 - ~/.cargo/bin/cargo
    CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    Composer: 2.8.6 - /opt/homebrew/bin/composer
    Homebrew: 4.4.23 - /opt/homebrew/bin/brew
    Maven: 3.9.9 - /opt/homebrew/bin/mvn
    pip3: 25.0 - /opt/homebrew/bin/pip3
    RubyGems: 3.6.3 - /opt/homebrew/opt/ruby/bin/gem
  Utilities:
    CMake: 3.31.6 - /opt/homebrew/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 16.0.0 - /usr/bin/gcc
    Git: 2.48.1 - /opt/homebrew/bin/git
    Clang: 19.1.7 - /opt/homebrew/opt/llvm/bin/clang
    Curl: 8.7.1 - /usr/bin/curl
    OpenSSL: 3.4.1 - /opt/homebrew/bin/openssl
  Virtualization:
    Docker: 27.5.1 - /Users/user/.local/bin/docker
    Docker Compose: 2.32.4 - /Users/user/.local/bin/docker-compose
    VirtualBox: 7.1.4 - /usr/local/bin/vboxmanage
  Languages:
    Bash: 5.2.37 - /opt/homebrew/bin/bash
    Go: 1.24.1 - /opt/homebrew/bin/go
    Java: 23.0.2 - /usr/bin/javac
    Perl: 5.34.1 - /usr/bin/perl
    PHP: 8.4.4 - /opt/homebrew/bin/php
    Protoc: 29.3 - /opt/homebrew/bin/protoc
    Python: 3.13.2 - /Users/user/.proto/shims/python
    Python3: 3.13.2 - /opt/homebrew/bin/python3
    Ruby: 3.4.2 - /opt/homebrew/opt/ruby/bin/ruby
    Rust: 1.83.0 - /Users/user/.cargo/bin/rustc
```
