### ISSUE TITLE
[feature] affected or status (staged) files token

### ISSUE THREAD

**Issue by muuvmuuv** [moonrepo/moon#1865]
**Is your feature request related to a problem? Please describe.**

I do know my dev-workflow is kind of wild here but maybe some can relate. 

While I have set up hooks I noticed that affected and status=staged have no possibility to just lint these affected files. In other words I cannot develop 4 features simultaneously when some files create errors that I have not staged yet but came across and error that I was able to fix on-the-fly in the same application.

**Describe the solution you'd like**

A token or something like `@affected` with a fallback option like `@affected(@in(0))`. That will just append all affected files or fall back to what is described.

**Describe alternatives you've considered**

```yml
vcs:
  hooks:
    pre-commit:
      - 'moon run :lint --affected --status=staged'
      - 'gitleaks git --pre-commit --redact --staged --verbose'
# ....
  run-eslint:
    command:
      - 'eslint'
      - '--cache'
      - if:
          - '@status(staged)'
        else:
          - '.'
    inputs:
      - '@group(app)'
      - '@group(sources)'
      - '@group(tests)'
      - '**/eslint.config.mjs'
```

**Additional context**

**Comment by milesj** [comment]
Not sure if this will solve this problem exactly, but have you tried this task option? https://moonrepo.dev/docs/config/project#affectedfiles

**Comment by muuvmuuv** [comment]
How should that actually work, when I enable this option it will also pass other files to e.g. ESLint which will prints a lot of warnings for JSON files, but these are relevant for the group "app" which I wanted to re-use for eslint. I might have to be more explicit with my groups then.

**Comment by muuvmuuv** [comment]
Hm, no this is not what I was looking for, but maybe I just need some help settings this up.

So this is for example for stylelint task:
```yml
  run-stylelint:
    command:
      - 'stylelint'
      - '--ignore-path'
      - '@in(0)'
      - '--ignore-path'
      - '@in(1)'
      - '--allow-empty-input'
      - '--cache'
    options:
      affectedFiles: true
    inputs:
      - '/.gitignore'
      - '/.stylelintignore'
      - '**/.stylelintrc.json'
      - '@group(styles)'
```

Stylelint will exit with 1 if it cannot parse a file. So running `moon :run-stylelint` will fail due to some affected file are HTML or JSON files.

I thought inputs would also "filter" affected files, or did I missunderstood that?

**Comment by muuvmuuv** [comment]
Oh, ok, got it now I guess. Stylelint is special. I had to explicitly ignore these kind of files because implicit inputs were passed to it when using it from the cli not the hook. Now it works as far as I can see.

```yml
  run-eslint:
    command:
      - 'eslint'
      - '--cache'
    options:
      affectedFiles: true
    inputs:
      - '**/eslint.config.mjs'
      - '@group(sources)'


  run-stylelint:
    command:
      - 'stylelint'
      - '--cache'
      - '--ignore-path'
      - '@in(0)'
      - '--ignore-path'
      - '@in(1)'
      - '--allow-empty-input'
    options:
      affectedFiles: true
      affectedPassInputs: true
    inputs:
      - '/.gitignore'
      - '/.stylelintignore'
      - '**/.stylelintrc.json'
      - '@group(styles)'
```

*** Insert "What a Week, Huh?" for "Web programming" ***
