### ISSUE TITLE
[bug] link separator replaced in fileGroups

### ISSUE THREAD

**Issue by MihaiPopescu1985** [moonrepo/moon#1868]
**Describe the bug**

When declaring an entry in a fileGroups with the value that represents a url, the '/' characters are replaced with '\\'.
For example:
```
fileGroups:
  link:
    - https://example.com/example
```
the `@groups(link)` will expand into `https:\example.com\example` which is not a valid url.

**Steps to reproduce**

Declare the group inside a moon.yml file and use it in a command.
Example content:

```
$schema: 'https://moonrepo.dev/schemas/tasks.json'

project:
  name: echo
  description: 'echo'

fileGroups:
  link:
    - https://example.com/example

tasks:
  echo:
    command: echo
    args:
      - '@group(link)'
```

Then run the moon task `moon run echo:echo`

The output is:
```
[ WARN 2025-03-12 15:31:27.786] moon_task_hasher::task_hasher  Attempted to hash input https:/example.com/example but it does not exist, skipping
▪▪▪▪ echo:echo (c38eaf4d)
https:\example.com\example
▪▪▪▪ echo:echo (6s 358ms, c38eaf4d)
```

**Expected behavior**

The url should stay the same and the '/' character should not be changed.

**Screenshots**

**Environment**

```
moon --version
moon 1.32.9
```

**Additional context**
