### ISSUE TITLE
[bug] "Property typescript is not allowed." error when adding the typescript settings in .moon/toolchain.yml

### ISSUE THREAD

**Issue by Rick-Phoenix** [moonrepo/moon#1893]
As indicated here: https://moonrepo.dev/docs/config/toolchain#javascript, the toolchan.yml file should accept a top-level property for typescript, but that property doesn't seem to be included in the toolchain.json schema, so VSCode shows "Property typescript is not allowed." when trying to add it to the toolchain.yml file (even after the schema has been correctly set up using the VSCode extension). 

An example of what I am trying to set up is:
```
bun:
  inferTasksFromScripts: true
  syncProjectWorkspaceDependencies: true
  version: latest
  installArgs:
    - "--frozen-lockfile"

typescript:
  syncProjectReferences: true
  syncProjectReferencesToPaths: true
```

Am I doing something wrong or something in the documentation or schema is outdated?
