### ISSUE TITLE
[feature] Generator command execution

### ISSUE THREAD

**Issue by SlyCedix** [moonrepo/moon#1902]
I am currently attempting to setup a .NET monorepo with templates for generating new projects, but to actually completely instantiate the project, I would need to both create the project files and add the project to the `.sln` file at the top level of the repository.

The best way to handle this would be to actually forgo the templating entirely, and instead prompt the user for inputs such as project name, root namespace, dotnet template, etc. and compose a `dotnet new` command from those inputs. Similar to what [nx-dotnet](https://www.nx-dotnet.com/) does for `nx`.

My ideal generator would look something like this:

template.yml:
```yml
title: "Class Library"
description: "Scaffolds a class library project, including source and test projects"
destination: "/"
variables: 
    project_name:
        type: string
        required: true
        prompt: "Enter a name for the project:"
    project_template:
        type: string
        required: true
        prompt: "Enter the project template:"
    test_project_template:
        type: string
        required: true
        prompt: "Enter the test project template:"

command: >
    "dotnet new {{project_template}} -o 'lib/src/{{project_name | lower_case}}' -n '{{project_name | pascal_case}}' &&"
    "dotnet new {{test_project_template}} -o 'lib/test/{{project_name | lower_case}}.test' -n '{{project_name | pascal_case}}' &&"
    "dotnet solution add 'lib/src/{{project_name | lower_case}}/{{project_name | pascal_case}}.csproj' &&"
    "dotnet solution add 'lib/test/{{project_name | lower_case}}.test/{{project_name | pascal_case}}.Test.csproj'"
```

Used as follows:
```
$ moon g library
library ──────────────────────────────────────────────────────────────────────────────                                                                                                                                 
                                                                                                                                                                                                                       
  Class Library
  Scaffolds a class library project, including source and test projects

✔ Enter a name for the project: SomeLibrary                                                                                                                                                                            
✔ Enter the project template: classlib                                                                                                                                                                                 
✔ Enter the test project template: nunit       

Executing command: dotnet new classlib -o 'lib/src/somelibrary' -n SomeLibrary && dotnet new nunit -o 'lib/test/somelibrary.test' -n 'SomeLibrary.Test' && dotnet solution add 'lib/src/somelibrary/SomeLibrary.csproj' && dotnet solution add 'lib/test/somelibrary.test/SomeLibrary.Test.csproj'
```

Another option would be to implement this as a task, but tasks do not have a builtin mechanism for prompting the user, so they would have to be implemented with shell commands and `interactive: true`, but that may introduce portability issues.

**Comment by bilelomrani1** [comment]
+1 on this feature. Scaffolding often involves running commands, potentially at different stage of the scaffolding process. I can think of several use cases:
1. Some template variables need to be populated by running commands. For instance, automatically inserting Git username and email into a project manifest, or querying system information to set defaults.
2. The new project needs to be registered in various top-level configuration files (OP's use case with `.sln` files, but this is also valid in other languages). Even within Moon itself, we could automatically register the new project in `.moon/workspace.yml` after scaffolding.
3. Running package manager commands (`npm install`, `dotnet restore`, `cargo fetch`, etc.) to set up the project immediately after generation.
4. Running commands to set correct permissions on scripts or other generated files that need specific access controls.

For reference, tools like [cookiecutter](https://cookiecutter.readthedocs.io/) support this pattern via `pre_gen_project` and `post_gen_project` hooks (Python scripts or shell scripts that run before/after template rendering). [Yeoman](https://yeoman.io/) has a similar lifecycle with `install()` and other hook methods.

A potential API could look something like:

```yaml
title: "Class Library"
description: "Scaffolds a class library project"
destination: "/"
variables:
  project_name:
    type: string
    required: true
    prompt: "Enter a name for the project:"

hooks:
  pre_generate:
    - command: "echo 'Starting generation...'"
  post_generate:
    - command: "dotnet new classlib -o 'lib/src/{{project_name | lower_case}}' -n '{{project_name | pascal_case}}'"
    - command: "dotnet sln add 'lib/src/{{project_name | lower_case}}/{{project_name | pascal_case}}.csproj'"
```
