### ISSUE TITLE
[bug] Negated globs are not being respected by the hasher

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1911]
**Describe the bug**

I have one task:

```yaml
  build-storybook:
    toolchain: node
    description: Build a Storybook for publishing on Chromatic
    command: storybook build --stats-json --test
    inputs:
      - "@group(sources)"
      - "!**/*.snap.png"
      - .storybook/*
      - /packages/library-storybook-utils/**/*
    outputs:
      - storybook-static/**/*
    type: build
    options:
      runInCI: false
      persistent: false
      cache: true
      outputStyle: buffer-only-failure
      timeout: 360
```

If I run `moon query hash` I will see the .snap.png files as inputs.

**Expected behavior**

I expected that the hasher would ignore the inputs that I mark as negated.

**Environment**

moon v1.34.1

**Workaround**

The workaround is to add a global ignore in `workspace.yml`:

```yaml
hasher:
  ignorePatterns:
    - "**/*.snap.png"
```
