### ISSUE TITLE
[feature] Support templates from http tarballs

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#1936]
**Is your feature request related to a problem? Please describe.**

moon code generation templates support having local files, git repos or npm packages.

Would be good also to be able to support http addresses providing tarballs, this would avoid having to publish a git repo or a npm package and would improve a lot of the DX for providing templates without the hassle of having to manage versioning over git or npm.

**Describe the solution you'd like**

To be able to do the following in `.moon/workspace.yml`

```yaml
generator:
  templates:
    - 'https://address.to/moon-templates.tar.gz'
```

**Describe alternatives you've considered**

Only alternatives now is to use npm or git.
