### ISSUE TITLE
[feature] Workspace.yml config for tailored dockerfile output

### ISSUE THREAD

**Issue by jesse-matsec** [moonrepo/moon#1988]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to set inputs for `moon docker file` to allow for more customizable Dockerfile generation

**Describe the solution you'd like**

We use a custom base image that has pnpm, moon and proto preconfigured and the full toolchain already warmed as a builder. 

It would be great if we could set configuration in `workspace.yml` to allow for more tailored Dockerfile generation:

```yaml
$schema: "https://moonrepo.dev/schemas/workspace.json"

projects:
  sources:
      app: "path/to/app"
      service: "path/to/service"
vcs:
  manager: "git"
  defaultBranch: "main"

docker:
  build_image:
    path: custom/docker/image/moon_base:latest
    build_toolchain: false
  prune: false
  entry_point: moon run [name]:start | node app.js | something else
  destination: default (project root) | custom (wherever/in/the/repo)
```

This would make the generated Dockerfile more flexible. For example, rather than always generating this:

```
#### BASE STAGE
#### Installs moon.

FROM node:latest AS base
WORKDIR /app

# Install moon binary
RUN curl -fsSL https://moonrepo.dev/install/moon.sh | bash
ENV PATH="/root/.moon/bin:$PATH"

#### SKELETON STAGE
#### Scaffolds repository skeleton structures.

FROM base AS skeleton

# Copy entire repository and scaffold
COPY . .
RUN moon docker scaffold <appname>

#### BUILD STAGE
#### Builds the project.

FROM base AS build

# Copy toolchain
COPY --from=skeleton /root/.proto /root/.proto

# Copy workspace configs
COPY --from=skeleton /app/.moon/docker/workspace .

# Install dependencies
RUN moon docker setup

# Copy project sources
COPY --from=skeleton /app/.moon/docker/sources .

# Build the project
RUN moon run <appname>:build

# Prune extraneous dependencies
RUN moon docker prune

#### START STAGE
#### Runs the project.

FROM base AS start

# Copy built sources
COPY --from=build /root/.proto /root/.proto
COPY --from=build /app /app

CMD moon run <appname>:start
```

I could configure it to generate something more like:

```
{% if workspace.docker.build_image is defined %}
  {% if workspace.docker.build_image.build_toolchain %}
    # Custom Base Image with Build step
    #### BASE STAGE
    #### Installs moon.

    FROM workspace.docker.build_image.path AS base
    WORKDIR /app

    # Install moon binary
    RUN curl -fsSL https://moonrepo.dev/install/moon.sh | bash
    ENV PATH="/root/.moon/bin:$PATH"

  {% else %}
    FROM workspace.docker.build_image.path AS base
{% else %}

WORKDIR /app

#### SKELETON STAGE
#### Scaffolds repository skeleton structures.

FROM base AS skeleton

# Copy entire repository and scaffold
COPY . .
RUN moon docker scaffold <appname>

#### BUILD STAGE
#### Builds the project.

FROM base AS build
{% endif %}


# Copy toolchain
COPY --from=skeleton /root/.proto /root/.proto

# Copy workspace configs
COPY --from=skeleton /app/.moon/docker/workspace .

# Install dependencies
RUN moon docker setup

# Copy project sources
COPY --from=skeleton /app/.moon/docker/sources .

etc..


```

Right now, since it's just me, I craft the Dockerfile for each new service. The other option is in my other feature request that allows for a Dockerfile.tera template to be stored in the central location for our Dockerfiles

**Additional context**

Edit for clarity: I honestly am not experienced enough to know if these are super niche requests. Sorry!
