### ISSUE TITLE
[feature] Simpler way to define internal tasks

### ISSUE THREAD

**Issue by sharpepd** [moonrepo/moon#1993]
**Is your feature request related to a problem? Please describe.**

I am finding that I like to use extends a lot to base other tasks on. The "base" tasks need to be internal (no one should run them on their own), which means I need to set the internal option true. But then the task that I expend from this is also marked internal and I need to set the option internal to true again.

**Describe the solution you'd like**

I would like a way to define such internal tasks in such a way that I do not have to keep setting the internal option off and on.

One idea I have is based on the name of the task. We could use a dot prefix "." to indicate that the task is "hidden" (i.e. internal) at least as a default. It can be overridden by the internal option as normal.

Example:
```yaml
tasks
    .hiddenTask:
        script: echo "I am hidden"
        env:
            FOO: BAR

   visibleTask:
       extends: .hiddenTask
       script: echo "Hello $FOO"
```

A `moon query tasks` would result in visibleTask being listed but not .hiddenTask.

I guess for backwards-compatibility reasons this would have to be an opt-in feature.

**Describe alternatives you've considered**

**Additional context**
