### ISSUE TITLE
[Question] outputStyle docs maybe wrong

### ISSUE THREAD

**Issue by b2whats** [moonrepo/moon#2004]
For 'outputStyle' written:

> Controls how stdout/stderr is displayed when the task is ran as a **transitive** target.

But it don't work.
```yml
  test: 
    command: 'echo 1'
    options:
      outputStyle: 'none'
```
and run task `moon run test`, i will not see output, although the task is not transitive, but is performed directly

can moon hide the output only for tasks described as dependencies ?
