### ISSUE TITLE
[bug] Git revision is not working for templates

### ISSUE THREAD

**Issue by codrin-iftimie** [moonrepo/moon#2006]
**Describe the bug**
I'm just taking a [random commit](https://github.com/facebook/react/tree/12adaffef7105e2714f82651ea51936c563fe15c) from a public registry. While I know there are no templates in this example, I'm just providing it as an example
```yaml
$schema: 'https://moonrepo.dev/schemas/workspace.json'

projects:
  - 'apps/*'
  - 'packages/*'

generator:
  templates:
    - 'git://github.com/facebook/react#12adaffef7105e2714f82651ea51936c563fe15c'
```

**Steps to reproduce**
1. `moon generate test` returns this error: `No template with the name test could be found at any of the configured template locations.`

2. When I do `ls -l ~/.moon/templates/git/github.com/facebook/react` I see the files from the main branch, not from the specific commit. 

I tried tags https://github.com/facebook/react/releases/tag/v17.0.2 (points to the same commit) as well
The file structure for these would not have the `ReactVersions.js` file present in the `~/.moon/templates/git/github.com/facebook/react` directory, for example

**Expected behavior**

The git templates should honor the revision.

**Environment**

moon@1.37.1
