### ISSUE TITLE
[feature] Task setup and cleanup hooks

### ISSUE THREAD

**Issue by rhuanbarreto** [moonrepo/moon#2009]
**Is your feature request related to a problem? Please describe.**

You normally need to do some preparations before a task, like logging into the infra or fetching secrets. You also normally need to do some cleanup after the task is run, like logging off the infra or formatting files after linting fixes.

Today you can solve this in moon by using `deps`. But `deps` doesn't guarantee the task happens right before and right after the current task in the task graph in the case you are running big task graphs like `moon ci` or `moon check` or `moon run :lint`. So you need to do a workaround:

```yaml
# tasks.yml
tasks:
  setup:
    command: do some setup
    options:
      internal: true
  actual-task:
    commmand: do the actual task
    options:
      internal: true
  cleanup:
    commmand: do the cleanup task
    options:
      internal: true
  task-name:
    commmand: noop
    deps:
      - setup
      - actual-task
      - cleanup
    options:
      runDepsInParallel: false
```

**Describe the solution you'd like**

I would like to have some configuration on a task that I could hook setup and cleanup tasks around a task.

**Describe alternatives you've considered**

Today the alternative is to do the workaround I showed, which brings lots of boilerplate.

**Additional context**

The main reason I do this is due to Azure login tokens expiring for a very long CI process (>10 mins) once those tokens are valid for around 5 minutes. So sometimes, CI fails because the azure token generation happened too early in the graph and the task execution runs with an expired token.

**Comment by milesj** [comment]
I'd say the correct way to do this is:

```yaml
tasks:
  setup:
    command: do some setup
    options:
      internal: true
  actual-task:
    commmand: do the actual task
    deps: [setup]
    options:
      internal: true
  cleanup:
    commmand: do the cleanup task
    deps: [actual-task]
    options:
      internal: true
```

I'd personally just rename the tasks to make it more apparent to the user.


But regardless, there are plans for "cleanup" dependencies, but our pipeline needs to be reworked to support them. It's a big overhaul and not high priority right now.
