### ISSUE TITLE
RFC: Task inheritance via inline configuration

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#2023]
# Problem

Task inheritance is one of moon's most powerful features, allowing you to define tasks at the top-level and have them automatically inherited by projects that match certain conditions. This is particularly useful for defining common tasks across multiple projects, such as linting, testing, or building.

In it's current form, task inheritance is based on the file name of the configuration file. For example, if you have a file named `node-application.yml`, it will inherit tasks for Node.js applications. This approach has several limitations:

- **Restrictive naming**: The file name must follow a specific pattern, which can be limiting and unintuitive.
- **Limited flexibility**: The inheritance is based solely on the file name, which means you cannot easily define more complex inheritance structures or conditions.

# Proposal

Instead of basing inheritance on the file name, which is rather restrictive, instead inheritance will be configured within the file  using a new `inheritedBy` setting. This setting will accept a MQL (moon query language) string, or an object of conditions.

With this change, the file name is irrelevant and can be named freely, and the configuration itself can support more complex inheritance structures, conditions, operators, and new features.

To demonstate this, here's a list of existing file name patterns and their equivalent `inheritedBy` configurations:

```yaml 
# node-application.yml 
inheritedBy:
  toolchains: 'node'
  layers: 'application'

inheritedBy: 'projectToolchain=node && projectLayer=application'
```

```yaml 
# ruby-backend-library.yml 
inheritedBy:
  toolchains: 'ruby'
  stacks: 'backend'
  layers: 'application'

inheritedBy: 'projectToolchain=ruby && projectStack=backend && projectLayer=application'
```

```yaml 
# tag-docker.yml 
inheritedBy:
  tags: 'docker'

inheritedBy: 'tag=docker'
```

## Better inheritance matching

To ensure this new approach is flexible and powerful, each condition in `inheritedBy` will support:

### One or many values 

You may have noticed in the examples that each field name is pluralized. This is because you can target one or many values for each condition. By default, a list of values is an `OR` clause.

```yaml
inheritedBy:
  # Only node 
  toolchains: 'node'
  # Bun or node 
  toolchains: ['bun', 'node']

inheritedBy: 'projectToolchain=[bun, node]'
```

This isn't possible with file name matching, as a file name can only match one value at a time.

### AND, OR, XOR, and NOT clauses

By default condition values are combined with an `OR` clause, meaning that if any of the condition values match, the inheritance will apply. However, you can also use an `AND` clause to require all condition values to match, or `NOT` clause to exclude all condition values that match, so on and so forth.

```yaml
inheritedBy:
  # Project is Node and Ruby
  toolchains: 
    and: ['node', 'ruby']
  # Project is not an app or library
  layers: 
    not: ['application', 'library']

inheritedBy: 'projectToolchain=[node, ruby] && projectLayer!=[application, library]'
```

With this approach, you can also mix and match clauses by defining the applicable `and`, `or`, `xor`, and `not` fields. When using multiple clauses, all of them must match for the inheritance to apply.

## Support existing conditions

The following conditions, which are currently supported in the file name matching, and their equivalent `inheritedBy` configurations.

- Project language/platform - Uses `toolchains` condition. 
  - The way toolchains and languages work are rather complex and confusing, so we hope to streamline this in the future.
- Project stack - Uses `stacks` condition.
- Project type - Uses `layers` condition.
- Project tag - Uses `tags` condition.

## Add new conditions

Because the `inheritedBy` setting is more flexible than file name matching, it can support new conditions that were not possible before.

### Files within a project 

You can now target files within a project using the new `files` condition. This allows you to match files based on their names, extensions, or even glob patterns.

For example, say you want to inherit ESLint tasks when a project contains an `.eslintrc` file, you can do something like this:

```yaml
inheritedBy:
  files: ['.eslintrc', '.eslintrc.*', 'eslint.config.*']

# Not supported by MQL
```

### Other?

If you have other ideas for inheritance enhancements, be sure to leave some feedback!
