### ISSUE TITLE
[feature] Support in-order (serial) execution for task deps

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#207]
**Is your feature request related to a problem? Please describe.**

Nope

**Describe the solution you'd like**

Tasks can define dependencies (https://moonrepo.dev/docs/config/project#deps), which are other tasks that must be ran before this task can be run. While this currently works, these dependencies run in parallel, where as sometimes you may want them to run in serial. For example, given the following task:

```yaml
tasks:
  release:
    command: '...'
    deps:
      - '~:clean'
      - '~:build'
      - '~:check'
```

On the surface it seems viable, but in actuality, the `clean` step must be finished _before_ the `build` step, which also must be finished before the `check` step. What we want is:

```
clean -> build -> check -> release
```

Instead of:

```
clean | 
build | -> release
check |
```

This problem _can_ be solved with the `deps` field and creating a manual chain, but this can be rather cumbersome, and makes it quite hard to reuse these tasks in other dependency chains.

```yaml
tasks:
  clean:
    command: '...'
  build:
    command: '...'
    deps: ['~:clean']
  check:
    command: '...'
    deps: ['~:build']
  release:
    command: '...'
    deps: ['~:check']
```

Instead, we can simply toggle between parallel and serial via an option on the task, like so:

```yaml
tasks:
  release:
    command: '...'
    deps:
      - '~:clean'
      - '~:build'
      - '~:check'
    options:
      serialDeps: true
      # or
      runDepsInSerial: true
```

**Describe alternatives you've considered**

N/A

**Additional context**
