### ISSUE TITLE
[bug/feature] should be able to execute any shell commands

### ISSUE THREAD

**Issue by alexn-s** [moonrepo/moon#223]
i would like to be able to use execute any shell command in a selectable shell.
most users have several cli utilities install that are only available in a certain shell with a profile)

shell: powershell
os: win 11
moon: 0.8.0

.moon/project.yml
```yml
tasks:
  clean:
    command: 'rimraf'
    type: 'system'
    args:
    - ' dist'
```

current error message

```sh
  $ moon run types:clean
▪▪▪▪ types:clean

 ERROR  Process failure for rimraf: program not found
```

rimraf is installed globally with npm

also why cant the command value be a 'sentence' (string with whitespaces), to write the full command of something?
if you need any further information please let me know.

**Comment by milesj** [comment]
@alexn-s This is an interesting one. When `type` is "system", nothing special happens, the command is simply executed as a child process. I'm assuming the npm global install location isn't within `$PATH`, so the environment can't find it.

I'm also not sure this is something we should support, as it assumes that all developers and machines (CI) also have `rimraf` installed globally, otherwise it would break. As an alternative you can do:

```
tasks:
  clean:
    command: 'rm'
    type: 'system'
    args: '-rf dist'
```

> also why cant the command value be a 'sentence' (string with whitespaces), to write the full command of something?

This is being discussed currently.
