### ISSUE TITLE
[bug] new envFile feature breaks when no CI file, even if not defined on running task

### ISSUE THREAD

**Issue by tanepiper** [moonrepo/moon#266]
In one project `moon.yml` the `dev` task has the `envFile` property set to true, also `local: true`

When running the `build` task in our CI, it fails to try to load a `.env` file even though this is not set on the task

**Steps to reproduce**

run `yarn moon run api-server:build` in the CI pipeline

output:

`Failed to parse env file ~/work/repo/services/api-server/.env: No such file or directory (os error 2)`

```
$schema: 'https://moonrepo.dev/schemas/global-project.json'

type: 'application'
language: 'typescript'

tasks:
  dev:
    local: true
    options:
      envFile: true
    command: 'yarn'
    args: 'run start'
    deps:
      - 'api-server:prestart'
    inputs:
      - 'src/**/*'
      - 'tsconfig.json'
      - 'package.json'
  prestart:
    options:
      cache: false
    command: 'yarn'
    args: 'run prestart'
    inputs:
      - 'src/**/*'
      - 'tsconfig.json'
      - 'package.json'
    outputs:
      - 'dist'
  build:
    command: 'yarn'
    args: 'run build'
    inputs:
      - 'src/**/*'
      - 'tsconfig.json'
      - 'package.json'
    outputs:
      - 'dist'
 ```

**Expected behavior**

Build should run without `.env` file present

**Environment**

GitHub Actions
