### ISSUE TITLE
[bug] Project 'tsconfig.json' is out of date because output 'dist/index.js' is older than input 'tsconfig.json

### ISSUE THREAD

**Issue by kaname-png** [moonrepo/moon#362]
**Describe the bug**

I don't know if I'm doing something wrong, or I have something misconfigured but when I run the task to build my typescript project I get this message in the console.

![image](https://user-images.githubusercontent.com/56084970/195177613-2a65fe33-062d-4162-9c97-33a39ab0dcf6.png)

**Steps to reproduce**

> project.yml

```yaml
# https://moonrepo.dev/docs/config/global-project
$schema: "https://moonrepo.dev/schemas/global-project.json"

fileGroups:
  configs:
    - "*.{js,json}"
  sources:
    - "src/**/*"
    - "types/**/*"
  tests:
    - "tests/**/*"

tasks:
  lint:
    command:
      - eslint

    args:
      - --no-error-on-unmatched-pattern
      - "."

    deps: []

    env:
      NODE_ENV: "production"

    inputs:
      - "@globs(sources)"

    type: "node"

  prettier:
    command:
      - prettier

    args:
      - --check
      - "."

    deps:
      - ^:lint

    env:
      NODE_ENV: "production"

    inputs:
      - "@globs(sources)"

    type: "node"

  build:
    command:
      - tsc

    args:
      - --build
      - --verbose

    deps:
      - ^:lint
      - ^:prettier

    env:
      NODE_ENV: "production"

    inputs:
      - "@globs(sources)"

    outputs:
      - dist

    type: "node"

```

> workspace.yml

```yaml
# https://moonrepo.dev/docs/config/workspace
$schema: "https://moonrepo.dev/schemas/workspace.json"

projects:
  core: "packages/core"

node:
  version: "18.10.0"

  packageManager: "pnpm"

  pnpm:
    version: "7.12.1"

  addEnginesConstraint: true

  dedupeOnLockfileChange: true

  dependencyVersionFormat: "workspace"

  syncProjectWorkspaceDependencies: true

  inferTasksFromScripts: false

  # Use the `package.json` name as an alias for the respective moon project.
  # aliasPackageNames: 'name-and-scope'

  # Sync `node.version` to a 3rd-party version manager's config file.
  # Accepts "nodenv" (.node-version), "nvm" (.nvmrc), or none.
  # syncVersionManagerConfig: 'nvm'

typescript:
  createMissingConfig: true

  projectConfigFileName: "tsconfig.json"

  rootConfigFileName: "tsconfig.base.json"

  rootOptionsConfigFileName: "tsconfig.base.json"

  # Update the project's `tsconfig.json` to route the `outDir` to moon's cache.
  # routeOutDirToCache: true

  syncProjectReferences: true

  syncProjectReferencesToPaths: true

vcs:
  manager: "git"
  defaultBranch: "main"

generator:
  template:
    - "./templates"

```

> tsconfig `packages/core`

```json
{
  "extends": "../../tsconfig.base.json",
  "include": [
    "**/*"
  ],
  "references": [],
  "compilerOptions": {
    "outDir": "dist"
  }
}

```

**Expected behavior**

When executing the task, this message is not displayed in the console.

**Screenshots**

See description.

**Environment**

```
  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) arm64 Neoverse-N1
    Memory: 19.57 GB / 23.43 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
  Managers:
    Apt: 2.2.4 - /usr/bin/apt
  Utilities:
    Git: 2.30.2 - /usr/bin/git
  IDEs:
    Nano: 5.4 - /bin/nano
  Languages:
    Bash: 5.1.4 - /bin/bash
    Perl: 5.32.1 - /usr/bin/perl
    Python3: 3.9.2 - /usr/bin/python3
```

**Additional context**

Nope.
