### ISSUE TITLE
[feature] Templates extend

### ISSUE THREAD

**Issue by itsezc** [moonrepo/moon#434]
**Is your feature request related to a problem? Please describe.**

Allow for templates to extend each other, where common files could be shared examples include: 

- LICENSE
- tsconfig
- gitignore

and similar files one might share between templates.

**Describe the solution you'd like**

```yml
title: 'npm package'
extends: parent-template
description: |
  Scaffolds the initial structure for an npm package,
  including source and test folders, a package.json, and more.
variables:
  name:
    type: 'string'
    default: ''
    required: true
    prompt: 'Package name?'
```

If both the parent and the child template have the same file i.e LICENSE, the child gets priority

**Describe alternatives you've considered**

Duplicating files, which isn't ideal, or using a third party generator.

**Additional context**

N/A
