### ISSUE TITLE
[bug] "dev" tasks only run lowest level dependencies concurrently.

### ISSUE THREAD

**Issue by xenobytezero** [moonrepo/moon#560]
If we assume a dependency tree that looks like 

```
app
├── components-1
│   └── library-1
└── components-2
    └── library-2
```
and a task description that looks like the following

```yaml
  dev:
    command: "tsc --watch --preserveWatchOutput"
    inputs: 
      - 'src/**'
      - 'types/**'
    outputs: 
      - 'dist/'
    deps:
      - '^:dev'
```
When the task is run, the two deepest leaves of the graph (library-1, library-2) will start their watch tasks, but obviously never finish, and so the next level up will never be started, and so the app will never be watched.

I understand inherently why this is the behaviour, but it feels like I'm missing a feature or something? Surely a dev task like watch should essentially collapse the dependecy tree in this case? Am I missing a configuration option?

**Comment by milesj** [comment]
@xenobytezero You are correct. The best way around this currently is with another "noop" task in the top level task, like so:

```yml
tasks:
  tsc-watch:
    command: "tsc --watch --preserveWatchOutput"
    inputs: 
      - 'src/**'
      - 'types/**'
    outputs: 
      - 'dist/'

  dev:  
    command: noop
    deps:
      - 'tsc-watch'
      - '^:dev'
```

**Comment by xenobytezero** [comment]
Looks like I'm still getting the same issue with the noop command.

```yaml
tasks:

  dev: 
    command: noop
    deps:
      - 'dev-watch'
      - '^:dev'

  dev-watch:
    command: "tsc --watch"
    inputs: 
      - 'src/**'
      - 'types/**'
    outputs: 
      - 'dist/'

```

```
>yarn moon project @ges/plugin-youtube-attach     

 PLUGIN-YOUTUBE-ATTACH 

ID: plugin-youtube-attach
Alias: @ges/plugin-youtube-attach
Source: packages/cms/plugin-youtube-attach
Root: <PATH>\packages\cms\plugin-youtube-attach
Language: TypeScript
Type: Unknown

 DEPENDS ON 

 - strapi-react-components (implicit, production)

 TASKS 

build: tsc 
dev: noop 
dev-watch: tsc --watch
```

```
>yarn moon run @ges/plugin-youtube-attach:dev 

▪▪▪▪ strapi-react-components:dev-watch
```

at which point it just stays here and never moves off the dependency project.

Moon v0.22.0

**Comment by milesj** [comment]
Can you paste the `--log trace` output and any terminal output?

**Comment by xenobytezero** [comment]
Attached it logfile (with my system path replaced with `<PROJECT PATH>`. Running the same command as above.

Also probably not related, but the log file also shows that my `Finding projects with globs: packages/*/*` step takes upwards of 5-6 minutes on a fresh PC boot.

[log.txt](https://github.com/moonrepo/moon/files/10484848/log.txt)

**Comment by milesj** [comment]
A few things to check:

- If you inspect the `.moon\cache\states\strapi-react-components\runfile.json`, are all the "deps" there?
- When you run `moon dep-graph @ges/plugin-youtube-attach:dev`, are all of the "deps" at the same level? If they are not, that's the problem.

**Comment by xenobytezero** [comment]
> If you inspect the .moon\cache\states\strapi-react-components\runfile.json, are all the "deps" there?

Everything looks correct? Looked at the `runfile.json` for both projects.

* plugin-youtube-attach:dev
    * plugin-youtube-attach:dev-watch
    * strapi-react-components:dev
* plugin-youtube-attach:dev-watch
    * NO DEPS
* strapi-react-components:dev
    * strapi-react-components:dev-watch
* strapi-react-components:dev-watch
    * NO DEPS

> When you run moon dep-graph @ges/plugin-youtube-attach:dev, are all of the "deps" at the same level? If they are not, that's the problem.

Again, I think it looks right?

![Graph](https://user-images.githubusercontent.com/5059527/215364545-a11f44b0-d75c-4542-bc3b-9b73016eb738.png)

**Comment by milesj** [comment]
@xenobytezero I think it's because `^:dev` ultimately resolves to `:dev` but what you really want is `^:dev-watch`. 

What I think is happening is that `plugin-youtube-attach:dev` starts the `strapi-react-components:dev` task, which then "takes over" because it's higher in the chain. This results in the other tasks not running.

Try this:
```
tasks:
  dev: 
    command: noop
    deps:
      - 'dev-watch'
      - '^:dev-watch'
```
