### ISSUE TITLE
[feature] Github Action for installing moon

### ISSUE THREAD

**Issue by cobraz** [moonrepo/moon#584]
I'm mainly running Github Actions, and I'm wondering if it might be helpful to have a `setup-moon` action.

We should use GitHub Actions' caching capabilities to store the global binary (Rust code), which might provide us with a more optimized workflow?

Let me know if I can help, or if I have missed anything?

**Comment by milesj** [comment]
This isn't a bad idea, I like it.

I've also thought about caching the toolchain at `~/.moon`. Maybe the tool can do that also.

**Comment by bryanjswift** [comment]
> This isn't a bad idea, I like it.
> 
> I've also thought about caching the toolchain at `~/.moon`. Maybe the tool can do that also.

For what it is worth, I _had_ to do this or I would get errors indicating node wasn't available. It is possible this had to do with my project's setup. It is difficult to tell since debugging actions is kind of a pain.

```yml
    - name: Cache Moon tools
      uses: actions/cache@v3
      with:
        path: ~/.moon/tools
        key: ${{ runner.os }}-moon-tools-v1-${{ hashFiles('.moon/toolchain.yml') }}
```
