### ISSUE TITLE
[feature] Don't write `tsconfig.json` when it hasn't changed

### ISSUE THREAD

**Issue by bryanjswift** [moonrepo/moon#607]
**Is your feature request related to a problem? Please describe.**

When developing a web application locally watching for changes with a tool like [`ts-node-dev`](https://www.npmjs.com/package/ts-node-dev) the server restarts every time `tsconfig.json` is modified. This is desirable when the contents of the file have been modified but the watching tools are listing for filesystem events to see if files were written and not reading the contents to compare if they have changed.

**Describe the solution you'd like**

Don't flush a write of an unmodified `tsconfig.json` file if what is on disk is the same as what would be written.

**Describe alternatives you've considered**

It is possible to change the `ts-node-dev` configuration to ignore changes to the `tsconfig.json`, which will work but it will mean that devs need to be aware that changes to TypeScript configuration require restarting the server by hand. Which includes anything that would change the TypeScript configuration as a result of "upstream" modifications (like adding a workspace dependency).

**Additional context**

The writing of `tsconfig.json` wouldn't trigger as many restarts if it didn't happen, seemingly, each time the package/project is processed. Meaning, even if the task is cached and restored from cache (or there's nothing to restore) the `tsconfig.json` file is still written and still triggers a reload.

**Comment by milesj** [comment]
@bryanjswift Do you happen to know which field is changing?

We do attempt to avoid writing if nothing has changed: https://github.com/moonrepo/moon/blob/master/crates/typescript/lang/src/tsconfig.rs#L130 But maybe we're missing a field.

**Comment by bryanjswift** [comment]
> @bryanjswift Do you happen to know which field is changing?
> 
> We do attempt to avoid writing if nothing has changed: https://github.com/moonrepo/moon/blob/master/crates/typescript/lang/src/tsconfig.rs#L130 But maybe we're missing a field.

Based on `git status` and `git diff` nothing in the file on disk has changed. I have not done any digging into this one because it is a fairly minor inconvenience. I'll note that I have the following typescript toolchain settings (on v0.22.0)

```yml
# Configures how moon integrates with TypeScript.
typescript:
  # When `syncProjectReferences` is enabled and a dependent project reference
  # *does not* have a `tsconfig.json`, automatically create one.
  createMissingConfig: true

  # Name of `tsconfig.json` file in each project root.
  # projectConfigFileName: 'tsconfig.json'

  # Name of `tsconfig.json` file in the workspace root.
  # rootConfigFileName: 'tsconfig.json'

  # Name of the config file in the workspace root that defines shared compiler
  # options for all project reference based config files.
  # rootOptionsConfigFileName: 'tsconfig.options.json'

  # Update a project's `tsconfig.json` to route the `outDir` compiler option
  # to moon's `.moon/cache` directory.
  routeOutDirToCache: false

  # Sync a project's `dependsOn` as project references within the
  # project's `tsconfig.json` and the workspace root `tsconfig.json`.
  syncProjectReferences: false

  # Sync a project's project references as import aliases to the `paths`
  # compiler option in each applicable project.
  syncProjectReferencesToPaths: false
```
