### ISSUE TITLE
[feature] Improve caching when tasks do not want to consider outputs

### ISSUE THREAD

**Issue by aidanhs** [moonrepo/moon#638]
**Is your feature request related to a problem? Please describe.**

Given the following `abc/moon.yml`:
```
tasks:
  test1:
    #command: "bash -c 'mkdir -p out && echo hi > out/a'"
    #command: "bash -c 'mkdir -p out && echo hii > out/a'"
    #command: "bash -c 'mkdir -p out && echo hi > out/a'"
    platform: 'system'
    outputs: [out]
```

If I run this task three times *uncommenting each `command` in turn) I get no cache hits.

This is expected behaviour - as documented on https://moonrepo.dev/docs/concepts/cache, apparently `output` targets are hashed before considering caches. But for build processes that always overwrite output/replace the output directory, this is overly pessimistic and means I will almost never get cache hits while iterating on some code or switching back and forward between different versions of something.

**Describe the solution you'd like**

I'd like a way to indicate to moon that the outputs should not be considered for caching purposes - perhaps this means moon considers them empty (and then clears them before running the task), or something else.

**Describe alternatives you've considered**

**Additional context**
