### ISSUE TITLE
[bug] Caching can cache too much if output directories are already populated

### ISSUE THREAD

**Issue by aidanhs** [moonrepo/moon#640]
**Describe the bug**

If multiple tasks use the same output directory, moon can incorrectly task output.

**Steps to reproduce**

Given the following abc/moon.yml (with x being an empty file):
```
tasks:
  test1:
    command: "bash -c 'mkdir -p out && echo hi > out/a'"
    platform: 'system'
    inputs: [/x]
    outputs: [out]
  test2:
    command: "bash -c 'mkdir -p out && echo hi > out/b'"
    platform: 'system'
    inputs: [/x]
    outputs: [out]
```

You can observe the following terminal session:
```
$ ./moon run abc:test1
▪▪▪▪ abc:test1
▪▪▪▪ abc:test1 (2ms, 3fa2ab50)

Tasks: 1 completed
 Time: 9ms

/tmp/tmp.7IyhNnxqSb $ ./moon run abc:test2
▪▪▪▪ abc:test2
▪▪▪▪ abc:test2 (3ms, ba02b2a5)

Tasks: 1 completed
 Time: 12ms

/tmp/tmp.7IyhNnxqSb $ rm -r abc/out/
/tmp/tmp.7IyhNnxqSb $ ./moon run abc:test2
▪▪▪▪ abc:test2 (cached, ba02b2a5)

Tasks: 1 completed (1 cached)
 Time: 5ms ❯❯❯❯ to the moon

/tmp/tmp.7IyhNnxqSb $ ls abc/out
a  b
```

**Expected behavior**

moon should not have cached both a and b for the `test2` task.

**Screenshots**

**Environment**

```
$ ./moon --version
moon 0.24.2
```

**Additional context**

This is a followup on #638 after a hint that I need to provide inputs to avoid hashing the 'out' directory.

I suspect the most pessimistic way for moon to operate by default is to treat output locations as empty, and clear them by default - i.e. applying the same logic that globs are documented to follow https://moonrepo.dev/docs/config/project#outputs
