### ISSUE TITLE
Semver-compliant Node Version Fails Validation

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#690]
**Describe the bug**

Moon complains when a semver-compliant string `18` is used. This is technically a compliant value: https://jubianchi.github.io/semver-check/#/*/18

If moon is going to assert semver complaint numbers, then a constraint should be published to show what moon is expecting. 

`18` is something that `nvm` handles, as well as the various node version managers.

**Steps to reproduce**

toolchain.yml

```yml
node:
  # The version to use. Must be a semantic version that includes major, minor, and patch.
  # We suggest using the latest active LTS version: https://nodejs.org/en/about/releases
  version: '18'
```

**Expected behavior**

No error, things work as per usual.

**Actual Behavior**

```
 ERROR 

Failed to validate .moon/toolchain.yml configuration file.

  ▪ Must be a valid semantic version for key "toolchain.node.version" in ../../.moon/toolchain.yml YAML Extended file
```

**Screenshots**

**Environment**

I ran `npx envinfo` as well as `pnpm dlx envinfo` and both hung upon execution, so I'm guessing that the package isn't Apple Silicon compatible 

**Additional context**

Additionally, we don't mandate a particular version of the `18` major, just that 18 is used. This isn't something we're particularly interested in tracking as it's an additional DX burden, so this requirement is not exactly friendly.

Our toolchain.yml file got this value from importing the value from `.npmrc` for what it's worth.
