### ISSUE TITLE
docs: global task `env` versus task context `env`

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#697]
I think this is more of a documentation issue than a bug or feature. I think there's some nuance missing from the docs around `env` in `tasks.yml`. Please consider the following `.moon/tasks.yml` file:

```yml
# https://moonrepo.dev/docs/config/tasks
$schema: 'https://moonrepo.dev/schemas/tasks.json'

env:
  MAKEFILES: '../../Makefile'

tasks:
  build:
    platform: 'system'
    command: 'make hello'
    envFile: true
```

The target `Makefile` exists at the repo root, and the task is being run with the `moon run svc-api:build` command. `svc-api` exists at `services/svc-api` at the repo root.

When running the `build` command, this fails with a message that `make` cannot find the `hello` target. It was my expectation based on the docs that the `MAKEFILES` envar would be applied to all tasks. When we change `tasks.yml` to the following:

```yml
# https://moonrepo.dev/docs/config/tasks
$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  build:
    platform: 'system'
    command: 'make hello'
    env:
      MAKEFILES: '../../Makefile'
    envFile: true
```

Adding the envar to the task context itself, things work as per usual, `make` files `Makefile` and we get the expected output.

Is there nuance missing around how `env` vars are applied to tasks, or is there something else going on behind the scenes that isn't obvious?

**Comment by milesj** [comment]
Yeah that looks correct. I have a handful of test cases here: https://github.com/moonrepo/moon/blob/master/crates/core/project-graph/tests/projects_test.rs#L920

Let me add some more and see if there's an edge case.

**Comment by milesj** [comment]
One thing to note is that `envFile` should be under `options`, so:

```
tasks:
  build:
    platform: 'system'
    command: 'make hello'
    options:
      envFile: true
```
