### ISSUE TITLE
[feature] `$timestamp` token variable

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#705]
**Is your feature request related to a problem? Please describe.**

I have the need to define a task in `.moon/tasks.yml` which dynamically include the current system timestamp in a command argument. e.g.

```yml
  deploy:
    command: 'cdk'
    args:
      - 'deploy'
      - '--all'
      - '--require-approval=never'
      - '--app "deploy --target=$projectRoot"'
      - '--output $workspaceRoot/.cdk/$project/$(date +%s)'
    deps:
      - ~:build
```

The `$(date +%s)` portion is problematic as we're not in a `sh` or `bash` shell and there doesn't appear to be a way to get that kind of data.

**Describe the solution you'd like**

The quick and dirty fix for our needs would be to create a new token variable `$timestamp` that was set to the system timestamp/epoch. It doesn't have to be high resolution, but I certainly wouldn't complain if it was.

**Describe alternatives you've considered**

I'm not sure at the moment how to get around this. A nice alternative might be something like a `@shell` function that would allow executing shell commands and returning the stdout output. Something like `@shell($(date +%s))` would get the job done. 

**Additional context**
