### ISSUE TITLE
[bug] Root-level 'moon.yml' hashing

### ISSUE THREAD

**Issue by elmpp** [moonrepo/moon#714]
**Describe the bug**

Altering the inputs on tasks do not seem to bust the cache

**Steps to reproduce**

I have set up a root level project:

./moon/workspace.yml
```
projects:
  sources:
    root: '.' # moon root-level project - https://tinyurl.com/2od9bpc4
  globs:
    - 'apps/*'
    - 'packages/*'
```

Created a ./moon.yml
```
tasks:
  testFixtures:
    command: 'pnpm jest --passWithNoTests tests/pkg-tests-specs-fixtures'
    inputs:
      # - 'tests/pkg-tests-specs-fixtures'
      # - 'TOTALLY_MADEUP_NONEXISTENT_PATH'
    platform: 'node'
    runFromWorkspaceRoot: true
```

After an initial run, all subsequent runs are a cache hit. I can change the `tasks.testFixtures.inputs` to anything. This is verified by looking in `~/dev/org-repo-moonrepo/.moon/cache/hashes/2bc666ea7942f5eea6d1fdd93951b2369654a5b11e31713f3c26c0367ca2a5fa.json` and seeing:

```
...
  "configs":
    "./moon.yml": "038c74c951a6fd1eff2155368c1db992a019ddff", <!--- does not change 
...
```

**Expected behavior**

I expect 2 things:
 - task input definitions to bust the cache
 - I expect that changing the any file matching the input should bust the cache 

**Screenshots**

**Environment**

`pnpm dlx envinfo` / `npx envinfo` does not work ??

Mac / Node 18.14.2 / pnpm 7.18.2

**Notes**
 - There is a log trace of the task run here- https://pastebin.mozilla.org/49KEEnHP
