### ISSUE TITLE
[bug] moon task that returns an exit code doesn't result in exit with code

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#720]
**Describe the bug**

We're running a dependency audit task that returns with an exit code of `1`, but the call to `moon` is returning an exit code of `0`

**Steps to reproduce**

As a control, run:

```console
→ bash -c "exit 1"
→ echo $?
1
```

Define a moon task that exits with `1`

```yml
  boom:
    command: 'bash -c "exit 1"'
```

Run the task and check the exit code:

```console
→ moon run rally:boom
▪▪▪▪ rally:boom
▪▪▪▪ rally:boom (1ms, 3bf153be)

 ERROR  Process bash failed with a 1 exit code.

→ echo $?            
0
```

**Expected behavior**

An exit code of `1`

This directly affects using moon in github actions, as tasks which fail are seen as passing. e.g. linting, dependency audits, etc

**Screenshots**

**Environment**

Mac OS Ventura
moon v0.26.3

**Additional context**

**Comment by milesj** [comment]
We explicitly set the error code to 1 when we render that "ERROR" message, so this is odd. https://github.com/moonrepo/moon/blob/master/crates/core/terminal/src/terminal.rs#L105

Do you know if this happens for other non-bash tasks? Or only for this kind of command?

**Comment by shellscape** [comment]
I first noticed it when PNPM was throwing an error on an audit check, and the workflow continued to pass. then I verified locally with PNPM audit, then verified with bash and used that example in the issue

**Comment by milesj** [comment]
Added some tests for this and they seem to pass: https://github.com/moonrepo/moon/pull/721

This also seems to work correctly for me locally:

```
$ cargo run -- r runtime:lint
▪▪▪▪ types:build (cached from previous run, 896f1e8f)
▪▪▪▪ runtime:lint
  3:1   warning  Unexpected console statement  no-console
  3:13  error    No magic number: 123          no-magic-numbers

✖ 2 problems (1 error, 1 warning)

▪▪▪▪ runtime:lint (4s 833ms, 2d9a797b)

 ERROR  Process ~/.proto/tools/node/16.19.1/bin/node failed with a 1 exit code.

$ echo $?
1
```

Could pnpm or something else be swallowing it?

**Comment by shellscape** [comment]
Here's the output from the github workflow:

<img width="571" alt="Screenshot 2023-03-19 at 3 36 17 PM" src="https://user-images.githubusercontent.com/76371/226204597-6664f393-8214-4b44-9f3d-8f25e7fa7861.png">

You can see there that two tasks that are started with moon both error, yet the workflow proceeds, and overall reports success. (the `build` step intentionally fails atm) Here's the yml for the workflow:

```yml
name: Validate Monorepo

on:
  workflow_dispatch:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  push:
    branches:
      - '*'
      - '!main'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v1

      - name: Checkout Main
        run: git branch -f main origin/main

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack
        id: pnpm-setup
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm config set script-shell "/usr/bin/bash"
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup Moon
        uses: moonrepo/setup-moon-action@v1

      - name: pnpm Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-setup.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ESLint Cache
        uses: actions/cache@v3
        with:
          path: ./.eslintcache
          key: ${{ runner.os }}-eslintcache-${{ hashFiles('./eslintcache') }}
          restore-keys: |
            ${{ runner.os }}-eslintcache-

      - name: Sanity Check
        run: |
          echo git `git version`;
          echo branch `git branch --show-current`;
          echo node `node -v`;
          echo pnpm `pnpm -v`

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Moon CI Setup
        run: moon ci

      - name: Audit Dependencies
        run: moon run rally:audit

      - name: Build Services
        run: moon run :build

      - name: Lint Monorepo
        run: moon run rally:lint
```

There's nothing but moon in those steps. 

Task defs for each:

```yml
# root moon.yml
# https://moonrepo.dev/docs/config/tasks
$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  audit:
    command: 'pnpm audit --audit-level=high'
    options:
      cache: false
```

```yml
#.moon/tasks.yml
# https://moonrepo.dev/docs/config/tasks
$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  configs:
    - '*.{js,json}'
  sources:
    - 'src/**/*'
  tests:
    - 'tests/**/*.test.*'

tasks:
  build:
    command: 'esbuild'
    envFile: true
```

I'll ask the team if we can grant you repo access to investigate if that will help.
