### ISSUE TITLE
Root level project is added as reference [bug] 

### ISSUE THREAD

**Issue by elmpp** [moonrepo/moon#723]
**Describe the bug**

Root level project is added to tsconfig.json as a reference

**Steps to reproduce**

 - Add a root level workspace with `syncProjectReferences: true`
 - observe `/tsconfig.json#references[0] === {'.'}`
 - Causes the following error:
 
 ```
 // toolchains.yml
 projects:
  sources:
    root: '.' # moon root-level project - https://tinyurl.com/2od9bpc4
  globs:
    - 'apps/*'
    - 'packages/*'
 ```
 
 ```
// /tsconfig.json
  "references": [
    {
      "path": "." // <!--- be gone, demon
    },
    {
      "path": "packages/pkg-address"
    },
 ```
 
 ```
 ○ → p moon run root:build
▪▪▪▪ root:build
error TS6202: Project references may not form a circular graph. Cycle detected: /Users/matt/dev/org-repo-moonrepo/tsconfig.json
 ```

**Expected behavior**

No root project managed reference

**Screenshots**
