### ISSUE TITLE
[bug] `moon ci` cannot find a Node dependency

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#728]
**Describe the bug**

It appears that `moon ci` is having trouble finding `esbuild` in our `pnpm` monorepo in a workflow. This doesn't seem to be an issue running locally. 

[log.txt](https://github.com/moonrepo/moon/files/11028858/log.txt)

You'll notice that it also cannot find the `goose` binary that we installed in another step. Here's our workflow for reference:

```yml
name: Validate Monorepo

on:
  workflow_dispatch:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  push:
    branches:
      - '*'
      - '!main'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v1

      - name: Checkout Main
        run: git branch -f main origin/main

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack
        id: pnpm-setup
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm config set script-shell "/usr/bin/bash"
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup Moon
        uses: moonrepo/setup-moon-action@v1

      - name: pnpm Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-setup.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ESLint Cache
        uses: actions/cache@v3
        with:
          path: ./.eslintcache
          key: ${{ runner.os }}-eslintcache-${{ hashFiles('./eslintcache') }}
          restore-keys: |
            ${{ runner.os }}-eslintcache-

      - name: Sanity Check
        run: |
          echo git `git version`;
          echo branch `git branch --show-current`;
          echo node `node -v`;
          echo pnpm `pnpm -v`

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Moon CI Setup
        run: moon ci --verbose

      - name: Audit Dependencies
        run: moon run workspace:audit

      - name: Build Services
        run: moon run :build

      - name: Lint Monorepo
        run: moon run workspace:lint
```

I think it's apparent that we're not using `moon ci` correctly, as my initial interpretation of the docs was that it's a setup routine rather than an automatic runner of all the things. We're going to be changing that on our end and likely not using `moon ci` because it just does too much and we like to structure CI/CD workflows differently than the standard it's setting. However, I wanted to share the issue none the less.

**Steps to reproduce**

Use a similar workflow to the one provided, add a task to `.moon/tasks.yml` like:

```
tasks:
  build:
    command: 'esbuild'
    envFile: true
```

And install esbuild as a devDep using `pnpm add esbuild -D -w`

**Expected behavior**

No errors

**Screenshots**

**Environment**

MacOS Ventura on M2

**Additional context**

**Comment by milesj** [comment]
@shellscape A few questions:

- Where does `goose` come from in CI?
- In CI, if you `ls` node modules, do you see the `esbuild` folder?

**Comment by shellscape** [comment]
> Where does goose come from in CI?

gah, sorry, that got cut from the text when I was cleaning it up.

```yml
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
```

> In CI, if you ls node modules, do you see the esbuild folder?

yes
