### ISSUE TITLE
[bug] moon gives globally installed node binary precedence over local

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#730]
**Describe the bug**

It appears that moon is giving globally installed binaries precedence over locally installed binaries of the same name. This is counter-intuitive in the Node realm, as most tools behave in the opposite.

**Steps to reproduce**

In a PNPM repo:

1. `pnpm add aws-cdk@latest` # 2.69.0
2. `pnpm add aws-cdk@2.54.0 -g`

Add a task:

```yml
platform: 'node'

tasks:
  deploy:
    command: 'cdk --version'
    platform: 'node' # for good measure
```

Run `moon run [project]:deploy` and observe that the output is `2.54.0 (build 9f41881)`
Run `pnpm exec cdk --version` and observe that the output is `2.68.0 (build 25fda51)`

**Expected behavior**

I had expected moon to choose the locally installed `cdk` bin first and execute that.

**Screenshots**

n/a

**Environment**

MacOS Ventura M2

**Additional context**
