### ISSUE TITLE
[bug] command + args composition appears incorrect

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#731]
**Describe the bug**

_Related to #729, I'm unable to inspect how moon is composing the command to execute, so I can't provide further context_

We're running a command to initiate a deployment with a bin that takes quite a few arguments. In an effort to clean up the presentation in tasks.yml, I put all of the args into an array. 

**Steps to reproduce**

We used the args array as follows:

```yml
  deploy:
    command: 'cdk'
    args:
      - 'deploy'
      - '--all'
      - '--require-approval=never'
      - '--app "deploy --target=$projectRoot"'
      - '--output $workspaceRoot/.cdk/$project/$timestamp'
```

But running this command results in an error from cdk `--app is required either in command-line, in cdk.json or in ~/.cdk.json`. That arg is clearly defined, so something else must be awry. I figured that I would fall back to a single arg in a big string:

```yml
  deploy:
    command: 'cdk'
    args: 'deploy --all --require-approval=never --app "FORCE_COLOR=1 pnpm exec deploy --target=$projectRoot" --output $workspaceRoot/.cdk/$project/$timestamp'
```

And that worked. I then attempted to break that out as:

```yml
  deploy:
    command: 'cdk'
    args:
      - 'deploy --all --require-approval=never --app "FORCE_COLOR=1 pnpm exec deploy --target=$projectRoot" --output $workspaceRoot/.cdk/$project/$timestamp'
```

And a different error was thrown: `Unknown command: deploy --all --require-approval=never --app "FORCE_COLOR=1 pnpm exec deploy --target=/Users/user/code/rally/rally/infra/core" --output /Users/user/code/rally/rally/.cdk/core/$timestamp`

Given the different behaviors observed, I would suspect there is some composition logic that's not quite right.

**Expected behavior**

Args to be assembled and the command to be called successfully.

**Screenshots**

**Environment**

MacOS Ventura M2

**Additional context**
