### ISSUE TITLE
[bug] command variable interpolation issues

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#732]
**Describe the bug**

_I can break this out into separate issues if needed. Related to #729 if we could have the final command logged, after interpolation is applied, I could provide more context._ 

We have a project that is being deployed via a `moon run infra-core:deploy` command. There appear to be a few issues:

1. The `$project` variable is being written "incorrectly"
2. The `$timestamp` variable isn't being replaced

We're using @moonrepo/cli v0.26.4

**Steps to reproduce**

The package.json file for the project is:

```json
{
  "name": "infra-core",
  "version": "0.1.0",
  "description": "Core Infrastructure Dependencies",
  "license": "UNLICENSED",
  "author": "Rally"
}
```

And the task definition is:

```yml
  deploy:
    command: 'cdk'
    args: 'deploy --all --require-approval=never --app "FORCE_COLOR=1 pnpm exec deploy --target=$projectRoot" --output $workspaceRoot/.cdk/$project/$timestamp'
```
**Expected behavior**

1. `$project` should be `infra-core`, as that matches package.json _and_ the project name required to run the command
2. `$timestamp` should be replaced

I had thought that `$timestamp` landed in v0.26.4, but could be mistaken. 

**Screenshots**

We can see from the following screenshot that the `$project` variable was replaced with `"core"` and the `$timestamp` variable wasn't replaced. I recall you all mentioning that the project name defaulted to the directory name, but given the inconsistency between the project name when calling the command, and the default name, that probably warrants some resolution.

<img width="309" alt="Screenshot 2023-03-21 at 12 06 13 PM" src="https://user-images.githubusercontent.com/76371/226671148-70fa13ff-b2e1-4738-af07-5ede26849106.png">

**Environment**

MacOS Ventura M2

**Additional context**
