### ISSUE TITLE
[bug] Descendant task dependencies run before earlier top level task dependencies

### ISSUE THREAD

**Issue by atticoos** [moonrepo/moon#744]
**Describe the bug**

Serial-ordered task dependencies run descendant dependencies of later-ordered tasks first

**Steps to reproduce**

```yml
tasks:
  run:
    deps:
      - a
      - b
  options:
    runDepsInParallel: false

  a:
    command: echo "A"

  b:
    command: echo "B"
    deps:
      - b1
      - b2
    options:
      runDepsInParallel: false

  b1:
    command: echo "B1"
  b2:
    command: echo "B2"
```

**Expected behavior**

Expected order:
```
A, B1, B2, B
```

Actual order:
```
B1, B2, A, B
```

**Screenshots**

n/a

**Environment**

MacOS Venture M1

**Additional context**

Becomes problematic when early tasks create artifacts that later tasks need to operate on.

Shifts my main task from
```yml
tasks:
  all:
    - clean
    - build
    - process
    - upload
```
to
```yml
tasks:
  all:
    - clean
    - mkdir
    - build.X
    - build.Y
    - build.Z
    - process.X
    - process.Y
    - process.Z
    - upload.X
    - upload.Y
    - upload.Z
```
