### ISSUE TITLE
[bug] `envFile` errors: missing files, no interpolation

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#748]
**Describe the bug**

There are a few issues in this one, and I couldn't figure out how to break them up without a lot of duplication. The task in question started out as this:

```yml
  foo:
    command: echo bar
    platform: system
```

I decided to test environment variable capability and changed the task to this:

```yml
  foo:
    command: echo env: $DEPLOY_ENV
    platform: system
    options:
      envFile: true
```

And then ran `moon run root:foo`. When specifying that `envFile: true` in `.moon/tasks.yml`, missing `.env` files in individual project directories throw (issue #1):

```
 ERROR  Failed to parse env file ~/code/projects/packages/log/.env: No such file or directory (os error 2)
```

And moon exits. Running the same task again _does not_ throw the error, but moon appears to run the old command, before enabling `envFile` and outputs `bar` to terminal. There seems to be a caching issue around that (issue #2)

So, I figured that maybe moon was failing to search up parent directories for the `.env` file, and changed the command to:

```yml
  foo:
    command: echo env: $DEPLOY_ENV
    platform: system
    options:
      envFile: $workspaceRoot/.env
```

But moon doesn't interpolate `$workspaceRoot` here, and fails citing the env file it cannot find with the literal `$workspaceRoot` in the bad path, curiously again within that same packages directory:

```
 ERROR 

Failed to parse env file ~/code/projects/packages/log/$workspaceRoot/.env: No such file or directory (os error 2)
```

**Steps to reproduce**

Outlined above for continuity

**Expected behavior**

1. moon properly finds-up, looking for the .env file without throwing errors
2. moon doesn't fail to clear the command cache when a command has been physically changed, if there's a preceding error
3. moon interpolates $workspaceRoot and other variables in options that accept strings, especially paths

**Screenshots**

**Environment**

MacOS Ventura, Moon v1.0.0

**Additional context**

**Comment by shellscape** [comment]
Adding to this, I just tried a parent-relative path as a workaround:

```yml
  foo:
    command: echo $DEPLOY_ENV
    platform: system
    options:
      envFile: ../../.env
```

And got 

```
 ERROR 

Failed to validate services/svc-api/moon.yml configuration file.

  ▪ Parent relative paths are not supported
```

That's an unfortunate limitation, given that the run context for the command is supposed to be the project directory. I've had to fall back to the shell to make it behave how I was expecting:

```yml
  foo:
    command: |
      [[ -f ../../.env ]] && source ../../.env;
      echo $DEPLOY_ENV
    platform: system
```

And that outputs `dev` as expected.
