### ISSUE TITLE
[bug] `$workspaceRoot` does not expand when used as prefix of command

### ISSUE THREAD

**Issue by mrobinsn** [moonrepo/moon#752]
Not sure if this is a bug, or intended behavior (in which case consider this a potential feature request).

It seems that `$workspaceRoot` is being interpreted literally when used as part of a command, I would expect it to be replaced with the absolute path to the actual workspace root.

This is necessary when sub-projects need to execute a tool that was installed at the repo root.

Error I am seeing:
```
▪▪▪▪ my-project:install
$workspaceRoot/target/venv/bin/pip install '-r requirements-dev.txt' (in REDACTED)
my-project:install | zsh:1: no such file or directory: /target/venv/bin/pip
```

Example task definition:
```
$schema: 'https://moonrepo.dev/schemas/project.json'

language: python

tasks: 
 install: 
 command: '$workspaceRoot/target/venv/bin/pip'
 args: 
 - 'install'
 - '-r requirements-dev.txt'
 options: 
 outputStyle: stream
 inputs: 
 - requirements-dev.txt
 deps: 
 - root:create/python-venv
 platform: system
```

(The setup is basically that a root project at the workspace level creates and manages a Python venv which various sub-projects might use) 

`$workspaceRoot` is only expanded if it stands alone in the command/args array, but that means you can’t use it as part of the binary target.

One workaround is to mark this task with `options.runFromWorkspaceRoot`, but that’s less than desirable since the arguments then all need to then be prefixed with the project’s path.
