### ISSUE TITLE
[bug] `$projectAlias` not replaced correctly in system command

### ISSUE THREAD

**Issue by shellscape** [moonrepo/moon#792]
**Describe the bug**

Consider the following config:

```yml
  pnpm.build:
    command: pnpm --filter $projectAlias --prod deploy $projectRoot/pnpm.out
    inputs:
      - dist
      - package.json
    platform: system
```

When calling `moon run svc-batman:pnpm.build` we receive an error from pnpm that no projects match.

The `--log trace` output indicates that the command is being constructed as:

```
[trace 13:18:06] moon:utils:process Running command /bin/zsh -c pnpm --filter svc-batmanAlias --prod deploy /Users/user/code/services/svc-batman/pnpm.out (in ~/code/services/svc-batman)
```

It looks like `$projectAlias` is being replaced out of order as `svc-batmanAlias`.

**Steps to reproduce**

See above

**Expected behavior**

`$projectAlias` is interpolated as `svc-batman`

**Screenshots**

**Environment**

MacOS Ventura
moon 1.1.1

**Additional context**
