### ISSUE TITLE
[feature] rust.bin in .moon/toolchain.yml should add an option for runInCI: false

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#882]
**Is your feature request related to a problem? Please describe.**

In `.moon/toolchain.yml` I configure to download few tools. I don't want to install `systemfd` and `watchexec-cli` when running `moon ci`.

```yaml
rust:
  version: '1.69.0'
  # List of Cargo binaries to install globally and make available to tasks.
  bins:
    - 'systemfd'
    - 'watchexec-cli'
  # Sync the configured version above as a channel to the root `rust-toolchain.toml` config.
  syncToolchainConfig: true
```

**Describe the solution you'd like**

running `moon ci` downloads the tools. There should be an option `runInCI: false` so it doesn't download when using `moon ci`. This allows me to speed up the ci builds.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by milesj** [comment]
Nice callout. I can look into this for the next version.

Curious, do tasks in CI not rely on these bins?

**Comment by prabirshrestha** [comment]
These are only used for dev and not CI. 

For example, I need webpack in CI, but don't need webpack-dev-server.

Basically I use `watchexec` to watch for file changes in `server` folder and if anything changes run `cargo run` command similar to how `cargo-watch` works. I don't need this tool in CI and would like to improve the CI perf.

```sh
watchexec --restart -w server 'cargo run'
```

**Comment by milesj** [comment]
Been thinking about this a bit. We'll need a way to support both local and CI bins inparalle.

For example, with `bins` you can't mix local/ci bins without someway of denoting which is which. This is kind of ugly:

```yaml
bins:
  - 'systemfd'
  - bin: 'watchexec-cli'
    ci: false
```

But the only other alternative is 2 separate settings. I'm not sure which is better.

```yaml
bins:
  - 'systemfd'
localBins:
  - 'watchexec-cli'
```

**Comment by prabirshrestha** [comment]
What about this? You can probably support both though I'm ok being explicit about it. command and options are the same as what tasks support which means less apis to learn. In future one could easily extend to add other options such as alias or default args.

```yaml
bins:
   - 'systemfd'
   - 'watchexec-cli':
       command: 'watchexec-ci'
       options:
         runInCI: false
```

You could extend this in future to support `npx` too so `bins` in node works via [npx](https://docs.npmjs.com/cli/v9/commands/npx).
