### ISSUE TITLE
[feature] Allow running task & it's deps in same shell 

### ISSUE THREAD

**Issue by spljs** [moonrepo/moon#955]
**Is your feature request related to a problem? Please describe.**

When i'm writing two tasks that are exploiting local variables , the variables are lost when the second one is executed (i assume a new shell is spawned)

**Describe the solution you'd like**

Add an option on a task to keep the same shell for the downstream (deps)

**Describe alternatives you've considered**

Adding commands in the same task (merged two tasks into one) but it's not readable as using the `deps`

**Additional context**

tasks definition

```yaml
  first_shell:
    platform: 'system'
    command: export AB=5
    
  sec_shell:
    platform: 'system'
    command: echo "$AB"
    options:
      uniqueShell: true # Must be great to add
    deps:
      - first_shell
```

The `sec_shell` task outputs nothing because of the shell separation
