### ISSUE TITLE
[bug] Moon doesn't hydrate glob'd outputs

### ISSUE THREAD

**Issue by mrobinsn** [moonrepo/moon#983]
I've found that moon doesn't hydrate outputs correctly when you use a glob.

For example, with the following `moon.yml`:
```yaml
$schema: https://moonrepo.dev/schemas/project.json
language: go
tasks:
  gen:
    command: touch a.txt b.txt c.txt
    inputs:
    - input.in
    outputs:
    - 'a.txt'
    - 'b.txt'
    - 'c.txt'
```

If I run
```bash
moon run gen
rm b.txt
moon run gen
```
Then `b.txt` is restored from the cache

However, with the following `moon.yml`:
```yaml
$schema: https://moonrepo.dev/schemas/project.json
language: go
tasks:
  gen:
    command: touch a.txt b.txt c.txt
    inputs:
    - input.in
    outputs:
    - '*.txt'
```

```bash
moon run gen
rm b.txt
moon run gen
```

`b.txt` is not restored.

`b.txt` is present in the cache tar at `.moon/cache/outputs/<hash>.tar.gz` in both cases.
