### ISSUE TITLE
[feature] Allow env var substition to work with tokens

### ISSUE THREAD

**Issue by philippeauriach** [moonrepo/moon#985]
**Is your feature request related to a problem? Please describe.**

I want to derive env variable from the current project name. For example, in every project, I have a `SENTRY_PROJECT` env variable, derived from the moon project's name.

**Describe the solution you'd like**

I would like to be able to write:
```yaml
  build:
    platform: system
    command: echo $SENTRY_PROJECT # this prints `myproject-${project}` without interpreting
    env:
      SENTRY_PROJECT: "myproject-${project}"
```

**Describe alternatives you've considered**

For now I'm getting out of it using : 
```yaml
  build:
    platform: system
    command: export SENTRY_PROJECT=myproject-$project && mycommandtobuild
```

**Additional context**

Env doc talks about substition and tells us "only variables in the current process can be referenced" => I guess that "tokens" are not considered variables in the current process, or maybe am I missing something ?

**Comment by milesj** [comment]
Good news, this is already implemented and will be released in the next version.

**Comment by philippeauriach** [comment]
Excellent news, thanks !

**Comment by milesj** [comment]
Landed in v1.11 https://moonrepo.dev/blog/moon-v1.11#unlocked-features

**Comment by philippeauriach** [comment]
Hello @milesj, I just checked with 1.11 and it does not seem to work with variable replacements in `ENV` variables : 
```
  test-replacement:
    platform: system
    command: echo $TEST_REPLACEMENT
    env:
      TEST_REPLACEMENT: test-${project}
```

This will output `test-${project}`

Regarding the release notes "unlocked features", it seems to only mention variable substition in tasks commands, not in env variables.
