### ISSUE TITLE
[feature] Generated files

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/moon#991]
I use [typeshare](https://github.com/1Password/typeshare/) to generate typescript files from rust code. How do I make sure the generated file is accounted for in inputs?

**Comment by milesj** [comment]
@prabirshrestha Where are the files being generated to? In the project, or somewhere else?

**Comment by prabirshrestha** [comment]
It can be in project or outside of project. Here are two cases:.

I have a typescript project that generates html/js/css files. These needs to be embedded in rust binary for release mode, for dev mode I directly proxy via the client server.

For clients I need to depend on on the some .rs files which can generate .ts equivalent. Since I get the binaries from rust bininstall it doesn't seems to make the typeshare binary available in typescript project so I generate these from rust project but the generated file exists in typescript project.

**Comment by milesj** [comment]
I think something like this may work?

```
tasks:
	ts-build:
		command: '...'
		deps:
			- 'typeshare:build'
		inputs:
			- '/path/to/typeshare/output/**/*'
```

Each TS task that requires the types depends on the Rust task that generates the files (`typeshare:build` here). The consuming task should have inputs for the generated files (using workspace paths above), and the `typeshare:build` task should have inputs for the `.rs` files that would trigger a re-generate.

**Comment by milesj** [comment]
@prabirshrestha Is this still an issue?

**Comment by prabirshrestha** [comment]
This is more of a question than an issue.

In `/.moon.yml` (this uses rust workspace so it is in root)

```yaml
tasks:
  typeshare-typescript:
    command: typeshare crates/server --lang=typescript --output-file=apps/client/src/models/models.generated.ts
    inputs:
      - crates/server/src/models/*.rs
    outputs:
      - apps/client/src/modles/models.generated.ts
```

In `/apps/client/moon.yml`.

```
fileGroups:
  app:
    - 'src/**/*'
    - 'src/modles/models.generated.ts' # is this needed? I expect not since this file will be generated by myapp:typeshare-typescript
tasks:
  build:
    command: 'pnpm build'
    deps:
      - myapp:typeshare-typescript
    inputs:
      - '@group(app)'
    outputs:
      - 'dist'
```

I'm curious how inputs are handled for generated files. For example, if moon calculates the fileGroups before the dependencies then it models.generated.ts won't exist but if it waits for the deps to calculate it will exist. I'm curious when the inputs are calculated. If it is after the deps have finished then that works and can close the issue.
